#!/usr/bin/env python3
"""Data for batch 8: sections 59–61 advanced vocab lists."""

ADVANCED = [
    ("Garrulous", "Very talkative"),
    ("Austere", "Simple and strict in manner"),
    ("Nebulous", "Unclear or vague"),
    ("Lethargic", "Without energy"),
    ("Clandestine", "Done in secret"),
    ("Eloquent", "Fluent in speaking"),
    ("Futile", "Useless or pointless"),
    ("Mitigate", "To reduce severity"),
    ("Impeccable", "Flawless"),
    ("Ephemeral", "Lasting a short time"),
    ("Insatiable", "Impossible to satisfy"),
    ("Magnanimous", "Generous and forgiving"),
    ("Revere", "Deeply respect"),
    ("Apathy", "Lack of interest"),
    ("Decrepit", "Old and weak"),
    ("Ubiquitous", "Present everywhere"),
    ("Vindicate", "Prove someone right"),
    ("Bolster", "Support or strengthen"),
    ("Galvanize", "Motivate to take action"),
    ("Oblivious", "Unaware"),
    ("Perilous", "Very dangerous"),
    ("Ravenous", "Extremely hungry"),
    ("Sporadic", "Occasional"),
    ("Tenacious", "Very determined"),
    ("Cajole", "Persuade with flattery"),
    ("Deride", "Make fun of"),
    ("Insolent", "Boldly disrespectful"),
    ("Lucid", "Clear-minded"),
    ("Resilient", "Able to recover quickly"),
    ("Stoic", "Showing no emotion"),
    ("Vehement", "Strongly passionate"),
    ("Wary", "Cautious and alert"),
    ("Zealous", "Very enthusiastic"),
    ("Ambiguous", "Having two meanings"),
    ("Candor", "Honesty"),
    ("Debunk", "Expose a lie"),
    ("Elude", "Escape or avoid"),
    ("Frugal", "Using resources carefully"),
    ("Hinder", "Slow down or block"),
    ("Illicit", "Illegal or forbidden"),
    ("Jubilant", "Joyful"),
    ("Keen", "Sharp or eager"),
    ("Lament", "Express sadness"),
    ("Meager", "Very small in amount"),
    ("Nefarious", "Wicked or evil"),
    ("Obsolete", "Outdated"),
    ("Pragmatic", "Practical"),
    ("Quell", "To calm or stop"),
    ("Reckless", "Careless or risky"),
    ("Sanguine", "Cheerful in hardship"),
    ("Trepidation", "Fear or worry"),
    ("Vivid", "Clear and bright"),
    ("Withdrawn", "Quiet and shy"),
    ("Yearn", "Strongly desire"),
    ("Zephyr", "Gentle breeze"),
    ("Abridge", "Shorten without losing meaning"),
    ("Benevolent", "Kind-hearted"),
    ("Concur", "Agree"),
    ("Disdain", "Disrespect"),
    ("Enigma", "Mystery"),
    ("Fathom", "Understand deeply"),
    ("Grimace", "Facial expression of pain"),
    ("Heed", "Pay attention"),
    ("Inane", "Silly or foolish"),
    ("Juxtapose", "Compare side by side"),
    ("Kudos", "Praise"),
    ("Lurk", "Hide while waiting"),
    ("Morose", "Gloomy or sad"),
    ("Nomadic", "Moving from place to place"),
    ("Overt", "Obvious or open"),
    ("Ponder", "Think deeply"),
    ("Quaint", "Attractively old-fashioned"),
    ("Rebuke", "Criticize sharply"),
    ("Serene", "Calm and peaceful"),
    ("Tangible", "Can be touched"),
    ("Unscathed", "Without injury"),
    ("Venture", "Risky journey"),
    ("Whimsical", "Playfully unusual"),
    ("Yearning", "Deep longing"),
    ("Zest", "Enthusiasm"),
    ("Affluent", "Wealthy"),
    ("Blatant", "Very obvious"),
    ("Cursory", "Quick and careless"),
    ("Diligent", "Hardworking"),
    ("Erratic", "Unpredictable"),
    ("Flourish", "Grow successfully"),
    ("Grueling", "Extremely tiring"),
    ("Hostile", "Unfriendly"),
    ("Impartial", "Fair and neutral"),
    ("Jeopardy", "In danger"),
    ("Knavery", "Dishonesty"),
    ("Lavish", "Luxurious"),
    ("Meander", "Wander aimlessly"),
    ("Notorious", "Famous for something bad"),
    ("Opaque", "Not transparent"),
    ("Plausible", "Believable"),
    ("Ruthless", "Without mercy"),
    ("Solitude", "Being alone"),
    ("Tranquil", "Peaceful"),
    ("Vulnerable", "Open to harm"),
]

GORGEOUS = [
    ("Adorable", "Lovably attractive"),
    ("Alluring", "Powerfully and mysteriously attractive"),
    ("Angelic", "Pure, heavenly beautiful"),
    ("Appealing", "Pleasantly attractive"),
    ("Arresting", "Strikingly noticeable and impressive"),
    ("Astonishing", "Surprisingly impressive"),
    ("Attractive", "Pleasing to look at"),
    ("Awe-inspiring", "Eliciting wonder and admiration"),
    ("Banging", "Extremely attractive; stunning"),
    ("Beautiful", "Pleasing in appearance"),
    ("Bedazzling", "Dazzlingly impressive"),
    ("Bewitching", "Enchantingly attractive"),
    ("Breathtaking", "Amazingly beautiful; stunning"),
    ("Captivating", "Holding attention with beauty"),
    ("Charming", "Delightfully pleasing"),
    ("Chic", "Stylishly elegant"),
    ("Comely", "Pleasantly attractive"),
    ("Dainty", "Delicately pretty"),
    ("Dapper", "Neatly stylish and attractive"),
    ("Dazzling", "Brilliantly impressive"),
    ("Delightful", "Highly pleasing"),
    ("Divine", "Exquisitely beautiful"),
    ("Drop-dead gorgeous", "Extremely stunning"),
    ("Elegant", "Gracefully stylish"),
    ("Enchanting", "Delightfully magical and attractive"),
    ("Engaging", "Charming; pleasingly interesting"),
    ("Entrancing", "Captivating to the point of trance"),
    ("Exquisite", "Exceptionally beautiful and refined"),
    ("Eye-catching", "Immediately noticeable and attractive"),
    ("Fabulous", "Amazingly impressive"),
    ("Fair", "Beautiful; pleasing in appearance"),
    ("Fetchingly", "Attractively appealing"),
    ("Fine-looking", "Handsome; attractive"),
    ("Foxy", "Sexily attractive"),
    ("Glamorous", "Attractively stylish and exciting"),
    ("Gleaming", "Shining brightly; radiant"),
    ("Glorious", "Magnificently beautiful"),
    ("Good-looking", "Attractive in appearance"),
    ("Graceful", "Elegantly poised and smooth"),
    ("Grand", "Impressively magnificent"),
    ("Handsome", "Good-looking; attractive"),
    ("Heavenly", "Wonderfully beautiful"),
    ("Hot", "Highly sexually attractive"),
    ("Immaculate", "Spotlessly perfect-looking"),
    ("Impressive", "Evoking admiration"),
    ("Irresistible", "Too attractive to refuse"),
    ("Jaw-dropping", "Amazingly shocking and beautiful"),
    ("Killer", "Exceptionally impressive; stunning"),
    ("Knockout", "Stunningly attractive"),
    ("Lavish", "Richly impressive and beautiful"),
    ("Lissome", "Slim, graceful, attractive"),
    ("Lovely", "Delightfully beautiful"),
    ("Luminous", "Radiating light; glowing"),
    ("Magnificent", "Grandly beautiful"),
    ("Majestic", "Regally impressive and beautiful"),
    ("Marvelous", "Wonderfully impressive"),
    ("Mesmerizing", "Fascinatingly captivating"),
    ("Mind-blowing", "Astonishingly impressive"),
    ("Nifty", "Neat and appealing"),
    ("On fleek", "Perfectly styled; flawless-looking"),
    ("Opulent", "Luxuriously rich and impressive"),
    ("Ornate", "Elaborately decorated; beautiful"),
    ("Out-of-this-world", "Amazingly extraordinary and beautiful"),
    ("Picturesque", "Pretty like a picture"),
    ("Polished", "Refined and well-presented"),
    ("Posh", "Stylishly luxurious"),
    ("Precious", "Charming and dearly appealing"),
    ("Pretty", "Pleasantly attractive"),
    ("Pulchritudinous", "Physically beautiful"),
    ("Radiant", "Glowing with beauty"),
    ("Ravishing", "Delightfully stunning"),
    ("Refined", "Elegant and cultured-looking"),
    ("Resplendent", "Shining brilliantly; splendid"),
    ("Riveting", "Compellingly captivating"),
    ("Sassy", "Boldly stylish and attractive"),
    ("Seductive", "Enticingly attractive"),
    ("Sensational", "Thrillingly impressive"),
    ("Show-stopping", "So stunning it halts attention"),
    ("Sleek", "Smooth, stylish, and elegant"),
    ("Smashing", "Extremely impressive; stunning"),
    ("Snazzy", "Flashily stylish"),
    ("Spectacular", "Dramatically impressive"),
    ("Splendid", "Magnificently fine-looking"),
    ("Statuesque", "Tall, impressively beautiful"),
    ("Stellar", "Outstandingly impressive"),
    ("Striking", "Noticeably attractive"),
    ("Stunning", "Amazingly impressive and beautiful"),
    ("Stylish", "Fashionably attractive"),
    ("Sublime", "Exalted, awe-inspiring beauty"),
    ("Superb", "Exceptionally good-looking"),
    ("Svelte", "Slim and elegant"),
    ("Sweet", "Pleasantly charming"),
    ("Tempting", "Enticingly appealing"),
    ("To die for", "Extremely desirable and beautiful"),
    ("Transcendent", "Beyond ordinary beauty"),
    ("Unbelievable", "Hard to believe; amazing"),
    ("Unreal", "Amazingly perfect-looking"),
    ("Winsome", "Charming in a sweet way"),
    ("Wondrous", "Astonishingly beautiful"),
    ("Wow-worthy", "Impressively stunning"),
]

RAREWORDS = [
    ("Abrogate", "Formally repeal or annul a law or agreement."),
    ("Acrimony", "Bitterness or sharpness in speech or manner."),
    ("Ad hoc", "Created for a specific purpose or situation."),
    ("Aesthetic", "Concerned with beauty or artistic taste."),
    ("Affidavit", "Written statement sworn to be true."),
    ("Allegory", "Story conveying hidden moral or political meaning."),
    ("Ambivalent", "Having mixed feelings or contradictory ideas."),
    ("Amortize", "Pay off a debt in scheduled installments."),
    ("Anachronism", "Something out of its proper historical time."),
    ("Anathema", "Something intensely disliked or formally condemned."),
    ("Antithesis", "Direct contrast of ideas for emphasis."),
    ("Apocryphal", "Of doubtful authenticity; widely believed but false."),
    ("Arbitrage", "Profit from price differences across markets."),
    ("Arcane", "Understood by few; mysterious or obscure."),
    ("Assiduous", "Showing persistent, careful effort and attention."),
    ("Auspicious", "Favorable; suggesting a positive outcome."),
    ("Banal", "So ordinary it becomes uninteresting."),
    ("Bellwether", "Indicator of future trends or direction."),
    ("Benevolent", "Kindly and well-meaning; charitable in intent."),
    ("Bifurcate", "Split into two branches or parts."),
    ("Bloviate", "Speak at length in a pompous way."),
    ("Bona fide", "Genuine; made in good faith."),
    ("Bourgeois", "Middle-class; conventional in values or tastes."),
    ("Cacophony", "Harsh, discordant mixture of sounds."),
    ("Capitulate", "Surrender or yield after resistance."),
    ("Catharsis", "Emotional release leading to relief or renewal."),
    ("Caveat", "Warning or condition attached to an agreement."),
    ("Chicanery", "Deception by trickery or legalistic quibbling."),
    ("Circumlocution", "Using many words to avoid direct expression."),
    ("Cliché", "Overused expression lacking original impact."),
    ("Cogent", "Clear, logical, and convincing in argument."),
    ("Cognizant", "Aware of; having knowledge or understanding."),
    ("Conflagration", "Large, destructive fire; great blaze."),
    ("Conundrum", "Confusing problem; difficult question to solve."),
    ("Corroborate", "Confirm with evidence or supporting information."),
    ("Credence", "Belief accepted as true; trust."),
    ("Cryptic", "Mysterious; having a hidden or unclear meaning."),
    ("Culpable", "Deserving blame; responsible for wrongdoing."),
    ("De facto", "Existing in practice, not officially recognized."),
    ("Debacle", "Sudden, humiliating failure; complete fiasco."),
    ("Decorum", "Proper behavior; social appropriateness and politeness."),
    ("Defenestration", "Act of throwing someone out a window."),
    ("Delineate", "Describe or outline precisely and clearly."),
    ("Demagogue", "Leader who manipulates emotions to gain power."),
    ("Denouement", "Final resolution of a narrative's plot."),
    ("Depravity", "Moral corruption; extreme wickedness."),
    ("Desideratum", "Something desired as essential or needed."),
    ("Diatribe", "Forceful, bitter verbal attack or criticism."),
    ("Dichotomy", "Division into two contrasting or opposed parts."),
    ("Didactic", "Intended to teach, often moral instruction."),
    ("Disparate", "Fundamentally different; not comparable."),
    ("Dogma", "Principle accepted as authoritative without proof."),
    ("Ebullient", "Cheerful and full of energy."),
    ("Eclectic", "Selecting from many sources; varied in style."),
    ("Efficacy", "Ability to produce the intended result."),
    ("Egregious", "Outstandingly bad; shockingly offensive."),
    ("Eloquence", "Fluent, persuasive speaking or writing."),
    ("Embellish", "Add details to make more attractive or interesting."),
    ("Empirical", "Based on observation or experiment, not theory."),
    ("Enigma", "Person or thing that is puzzling."),
    ("Ephemeral", "Lasting a very short time."),
    ("Epistemology", "Study of knowledge: its nature, sources, limits."),
    ("Equivocate", "Use ambiguous language to avoid commitment."),
    ("Esoteric", "Intended for or understood by a few."),
    ("Euphemism", "Mild term replacing a harsh or blunt one."),
    ("Exacerbate", "Make a problem or situation worse."),
    ("Exculpate", "Clear from blame or guilt."),
    ("Exegesis", "Critical explanation or interpretation of a text."),
    ("Exorbitant", "Unreasonably high, especially in price."),
    ("Extant", "Still existing; not lost or destroyed."),
    ("Facetious", "Treating serious matters with inappropriate humor."),
    ("Fallacy", "Mistaken belief or flawed reasoning."),
    ("Fastidious", "Very attentive to detail; hard to please."),
    ("Fatuous", "Silly and pointless; lacking intelligence."),
    ("Feckless", "Lacking initiative or effectiveness; irresponsible."),
    ("Fiduciary", "Legally bound to act in another's interests."),
    ("Florid", "Excessively elaborate or flowery in style."),
    ("Forbearance", "Patient self-control; restraint under provocation."),
    ("Fortuitous", "Happening by chance, often luckily."),
    ("Garrulous", "Excessively talkative, especially about trivial matters."),
    ("Germane", "Relevant and appropriate to the subject."),
    ("Gerrymander", "Manipulate voting districts to favor a party."),
    ("Grandiloquent", "Pompous, high-flown language or style."),
    ("Hackneyed", "Overused and lacking original freshness."),
    ("Hegemony", "Dominance or leadership by one group or state."),
    ("Heuristic", "Practical method for quick problem-solving."),
    ("Hubris", "Excessive pride leading to downfall."),
    ("Iconoclast", "Person who attacks cherished beliefs or institutions."),
    ("Idiosyncrasy", "Unusual personal habit or distinctive trait."),
    ("Imbroglio", "Confusing, complicated situation; messy entanglement."),
    ("Impunity", "Freedom from punishment or consequences."),
    ("Inchoate", "Not fully formed; rudimentary or vague."),
    ("Incontrovertible", "Impossible to deny or dispute."),
    ("Ineffable", "Too great to be expressed in words."),
    ("Innuendo", "Indirect suggestion, often negative or sexual."),
    ("Insidious", "Proceeding subtly but harmfully over time."),
    ("Interlocutor", "Participant in a conversation or dialogue."),
    ("Intransigent", "Unwilling to compromise; stubbornly inflexible."),
    ("Irony", "Meaning opposite of what is expected or said."),
    ("Juggernaut", "Overwhelming force that crushes opposition."),
]

SECTIONS = [
    (
        59,
        "advanced",
        "Advanced Vocabularies (100)",
        "Useful advanced words with short definitions, numbered 1–100.",
        ADVANCED,
    ),
    (
        60,
        "gorgeous",
        "100 Other Words for &ldquo;Gorgeous&rdquo;",
        "Beauty and attractiveness synonyms, numbered 1–100.",
        GORGEOUS,
    ),
    (
        61,
        "rarewords",
        "100 Words Everyone Hears but Few Can Explain",
        "Heard-often vocabulary with clear definitions, numbered 1–100.",
        RAREWORDS,
    ),
]
