#!/usr/bin/env python3
"""Data for batch 6: section 52 quick reactions."""

SECTIONS = [
    (
        52,
        "quickreactions",
        "100 Quick Reactions",
        "Short exclamations and conversational reactions, numbered 1\u2013100.",
        [
            ("Absolutely!", "Strong agreement or confirmation."),
            ("All right!", "Acceptance; okay."),
            ("And?", "Prompt to continue."),
            ("Are you kidding me?", "Disbelief; shocked reaction."),
            ("As if!", "Dismissive disbelief."),
            ("Aw, man!", "Disappointed reaction."),
            ("Awesome!", "Excited approval."),
            ("Ay, caramba!", "Surprised or frustrated exclamation."),
            ("Bingo!", "You got it exactly."),
            ("Blimey!", "Mild surprise."),
            ("Boy, oh boy!", "Surprise or disbelief."),
            ("Brilliant!", "Strong approval."),
            ("Bullseye!", "Exactly right."),
            ("Bummer!", "Disappointment or bad luck."),
            ("But why?", "Asking for a reason."),
            ("Come again?", "Please repeat that."),
            ("Come on!", "Impatience or disbelief."),
            ("Cool!", "Approval; impressed."),
            ("Crazy!", "Amazed or shocked."),
            ("Dang!", "Mild frustration or surprise."),
            ("Definitely!", "Strong yes."),
            ("Did you?", "Prompting confirmation."),
            ("Do tell!", "Invite more details."),
            ("Duh!", "That was obvious."),
            ("Eek!", "Sudden fright or surprise."),
            ("Enough already!", "Stop; that\u2019s too much."),
            ("Exactly!", "Perfect agreement."),
            ("Excuse me?", "Offended or surprised query."),
            ("Fantastic!", "Very pleased."),
            ("For real?", "Is that true?"),
            ("Geez!", "Annoyance or surprise."),
            ("Get out!", "I don\u2019t believe it."),
            ("Go on\u2026", "Continue speaking."),
            ("Good grief!", "Exasperation or surprise."),
            ("Great!", "Positive reaction."),
            ("Gross!", "Disgusted reaction."),
            ("Ha!", "Amused or triumphant reaction."),
            ("Hallelujah!", "Relief or joy."),
            ("Hang on!", "Wait a moment."),
            ("Hardly!", "Strong disagreement."),
            ("Heck no!", "Emphatic no."),
            ("Here we go again!", "Not this again."),
            ("Holy cow!", "Surprised amazement."),
            ("Holy crap!", "Strong surprise."),
            ("How come?", "Why is that?"),
            ("How so?", "Explain your reasoning."),
            ("How terrible!", "Sympathetic shock."),
            ("Huh?", "Confused; didn\u2019t catch that."),
            ("I can\u2019t believe it!", "Shocked disbelief."),
            ("I knew it!", "Confirmation of suspicion."),
            ("I mean\u2026 wow.", "Speechless amazement."),
            ("I\u2019m in!", "Eager agreement."),
            ("I\u2019m out!", "Refusal; not participating."),
            ("I\u2019m serious!", "Not joking."),
            ("I\u2019m sorry!", "Sympathy or apology."),
            ("Incredible!", "Hard to believe."),
            ("Is that so?", "Skeptical acknowledgment."),
            ("Isn\u2019t it?", "Seeking agreement."),
            ("Jeez Louise!", "Surprised or annoyed reaction."),
            ("Just great!", "Sarcastic annoyance."),
            ("Just my luck!", "Bad luck reaction."),
            ("Kidding!", "I was joking."),
            ("Kill me now.", "Overwhelmed embarrassment."),
            ("Let me get this straight\u2026", "Clarifying understanding."),
            ("Look at that!", "Pointing out surprise."),
            ("Lucky you!", "You\u2019re fortunate."),
            ("Makes sense.", "That\u2019s logical."),
            ("Man!", "Emphasis; surprise or frustration."),
            ("Marvelous!", "Delighted approval."),
            ("Me too!", "Same here."),
            ("My goodness!", "Mild shock."),
            ("My word!", "Surprised reaction."),
            ("Nah.", "No; not really."),
            ("No kidding!", "Really? I\u2019m surprised."),
            ("No way!", "Strong disbelief or refusal."),
            ("No wonder!", "That explains it."),
            ("Not a chance!", "Definitely not."),
            ("Not again!", "Frustrated repetition."),
            ("Not bad!", "Approval; decent."),
            ("Oh dear!", "Concern or dismay."),
            ("Oh great!", "Sarcastic disappointment."),
            ("Oh my!", "Surprised reaction."),
            ("Oh no!", "Alarm or dismay."),
            ("Oh, come on!", "Disbelief; pushback."),
            ("Oh, wow!", "Amazement."),
            ("Okay then!", "Acceptance; moving on."),
            ("Oof!", "Pain or discomfort."),
            ("Ouch!", "Pain or hurt feelings."),
            ("Phew!", "Relief."),
            ("Please!", "Dismissive disbelief."),
            ("Seriously?", "Questioning truth or intent."),
            ("Shut up!", "Playful disbelief; stop talking."),
            ("So what?", "Dismissive; why it matters?"),
            ("Stop it!", "Disbelief; cut it out."),
            ("Sure!", "Agreement."),
            ("Tell me more.", "Request more details."),
            ("That figures.", "As expected; typical."),
            ("That\u2019s amazing!", "Impressed surprise."),
            ("That\u2019s awful!", "Sympathetic dismay."),
            ("That\u2019s hilarious!", "Very funny."),
        ],
    ),
]
