"""Batch 5 word-bank sections 48–51."""

SMELLS = [
    ('Acrid', 'sharp, biting, irritating smell'),
    ('Airy', 'light, open, barely-there scent'),
    ('Alcoholic', 'smelling of spirits or ethanol'),
    ('Almondy', 'sweet, nutlike, marzipan scent'),
    ('Ammoniacal', 'pungent, urine-like ammonia odor'),
    ('Animalic', 'musky, bodily, fur-like odor'),
    ('Aniseed', 'sweet, licorice-like spice smell'),
    ('Antiseptic', 'clean, medicinal, disinfectant odor'),
    ('Aromatic', 'pleasantly fragrant, spice-tinged'),
    ('Ashen', 'dry, sooty, fireplace-like smell'),
    ('Balsamic', 'resinous, sweet, wood-and-amber scent'),
    ('Barnyard', 'earthy, manure-tinged farm smell'),
    ('Bitter', 'sharp, sour-leaning unpleasant odor'),
    ('Brackish', 'salty, stagnant, sea-tinged smell'),
    ('Burnt', 'charred, scorched, smoke-heavy odor'),
    ('Buttery', 'rich, creamy, melted-fat scent'),
    ('Camphorous', 'cool, medicinal, mothball-like aroma'),
    ('Candy-sweet', 'sugary, confection-like fragrance'),
    ('Carbolic', 'phenolic, disinfectant-like odor'),
    ('Cedarwood', 'dry, pencil-shaving wood scent'),
    ('Chlorinous', 'bleachy, pool-chemical smell'),
    ('Citrusy', 'bright, zesty, peel-like scent'),
    ('Cloying', 'overly sweet, suffocating fragrance'),
    ('Cocoa-rich', 'deep, chocolatey, roasted aroma'),
    ('Damp', 'wet, musty, moisture-heavy smell'),
    ('Decaying', 'rotting, breaking-down organic odor'),
    ('Diesel', 'oily, fuel-like exhaust smell'),
    ('Dirty', 'grimy, unwashed, stale odor'),
    ('Disinfectant', 'sterile, chemical-clean smell'),
    ('Doggy', 'wet-fur, kennel-like odor'),
    ('Dried-herbal', 'crushed leaves, haylike aroma'),
    ('Dusty', 'powdery, old-paper smell'),
    ('Earthy', 'soil-like, grounded, loamy scent'),
    ('Eggy', 'sulfurous, boiled-egg smell'),
    ('Elderflower', 'lightly floral, green-sweet scent'),
    ('Exhausty', 'fume-heavy, traffic-like odor'),
    ('Faint', 'barely noticeable, subdued smell'),
    ('Feculent', 'filthy, sewage-like stench'),
    ('Fermented', 'yeasty, souring, brewing odor'),
    ('Fetid', 'intensely foul, putrid smell'),
    ('Fishy', 'briny, marine, stale-seafood odor'),
    ('Floral', 'flowerlike, perfumed scent'),
    ('Fragrant', 'pleasing, noticeable aroma'),
    ('Gamy', 'wild-meat, musky, bloody odor'),
    ('Garlicky', 'pungent, savory, allium smell'),
    ('Gaseous', 'chemical, fume-like odor'),
    ('Gingered', 'warm, spicy, sharp scent'),
    ('Greasy', 'oily, fried-fat smell'),
    ('Green', 'fresh-cut plant, leafy scent'),
    ('Grimy', 'soiled, sweat-tinged odor'),
    ('Harsh', 'rough, stinging, abrasive smell'),
    ('Headachey', 'overpowering, sickly strong scent'),
    ('Heady', 'intoxicatingly strong, lush aroma'),
    ('Herbal', 'leafy, medicinal-plant scent'),
    ('Honeyed', 'sweet, nectar-like fragrance'),
    ('Hot-metal', 'heated iron, workshop-like odor'),
    ('Incensey', 'smoky, resinous, temple-like scent'),
    ('Inky', 'sharp, chemical, pen-ink smell'),
    ('Iodine', 'briny, antiseptic, sea-medicinal'),
    ('Jammy', 'cooked fruit, thick-sweet smell'),
    ('Jasmine', 'rich, white-floral, narcotic scent'),
    ('Jerky-like', 'smoky, cured-meat aroma'),
    ('Juniper', 'piney, gin-like, resinous scent'),
    ('Kerosene', 'sharp, oily lamp-fuel smell'),
    ('Kitchen-stale', 'old cooking odors lingering'),
    ('Lavender', 'clean, calming, floral-herbal scent'),
    ('Leathery', 'tanned hide, warm, dry odor'),
    ('Lemony', 'bright, tart citrus smell'),
    ('Malodorous', 'noticeably unpleasant smell'),
    ('Manurey', 'strong dung, farmyard odor'),
    ('Medicinal', 'drugstore-like, antiseptic scent'),
    ('Mildewy', 'musty, damp-mold smell'),
    ('Minty', 'cool, sharp, refreshing scent'),
    ('Mossy', 'green, damp-forest smell'),
    ('Musk', 'warm, animal-skin fragrance'),
    ('Nauseating', 'sickeningly foul or cloying'),
    ('Nutty', 'toasted, seedlike aroma'),
    ('Oaky', 'dry barrel-wood scent'),
    ('Oily', 'slick, fatty, petroleum-tinged'),
    ('Oniony', 'sharp, sulfurous allium smell'),
    ('Ozone', 'sharp, clean, after-storm scent'),
    ('Peppery', 'spicy, prickling, sharp aroma'),
    ('Perfumed', 'artificially fragrant, cosmetic smell'),
    ('Petrichor', 'earthy scent after rain'),
    ('Piney', 'resinous evergreen smell'),
    ('Pungent', 'strong, sharp, penetrating odor'),
    ('Putrid', 'rotten, rancid, vile smell'),
    ('Rancid', 'spoiled fat, sour-oily odor'),
    ('Resinous', 'saplike, sticky, balsam scent'),
    ('Ripe', 'fully developed, sweet-strong odor'),
    ('Rotten', 'decomposed, foul organic smell'),
    ('Salty', 'sea-air, mineral tang scent'),
    ('Savory', 'meaty, brothlike, appetizing smell'),
    ('Sewerish', 'drain, waste, sewage odor'),
    ('Skunky', 'sharp, sulfurous spray smell'),
    ('Smoky', 'woodsmoke, ash, burnt scent'),
    ('Soapy', 'clean, detergent-like smell'),
    ('Spicy', 'warm, peppered, aromatic scent'),
    ('Stale', 'old, flat, airless smell'),
    ('Stinking', 'strongly unpleasant odor'),
]

DRAMA = [
    ('acrimonious', 'angry and bitter'),
    ('agitated', 'nervous, upset, or excited'),
    ('agonizing', 'causing intense emotional pain'),
    ('anguished', 'showing severe mental pain'),
    ('anxious', 'worried and tense'),
    ('bitter', 'full of resentment or pain'),
    ('boiling', 'full of anger or excitement'),
    ('breathless', 'excitingly fast or intense'),
    ('brooding', 'deeply troubled and moody'),
    ('captivating', 'very attractive and engaging'),
    ('chaotic', 'completely disordered and confused'),
    ('charged', 'full of strong emotion'),
    ('combative', 'ready to fight or argue'),
    ('compelling', 'powerfully interesting or convincing'),
    ('confrontational', 'inclined toward conflict'),
    ('contentious', 'likely to cause argument'),
    ('critical', 'at a dangerous turning point'),
    ('dark', 'serious, grim, or threatening'),
    ('devastating', 'causing severe shock or grief'),
    ('dire', 'extremely serious or urgent'),
    ('disquieting', 'causing unease or anxiety'),
    ('disturbing', 'causing worry or discomfort'),
    ('do-or-die', 'allowing no failure'),
    ('dramatic', 'full of excitement or emotion'),
    ('edge-of-your-seat', 'extremely suspenseful and exciting'),
    ('electrifying', 'thrillingly exciting and intense'),
    ('emotional', 'showing strong feelings'),
    ('epic', 'grand and dramatic in scale'),
    ('exaggerated', 'made larger than reality'),
    ('explosive', 'likely to erupt suddenly'),
    ('fierce', 'intensely aggressive or strong'),
    ('fiery', 'full of strong emotion'),
    ('foreboding', 'feeling of coming trouble'),
    ('frantic', 'wild with fear or urgency'),
    ('fraught', 'full of tension or anxiety'),
    ('frenzied', 'wildly excited or uncontrolled'),
    ('grandiose', 'overly grand or ambitious'),
    ('grave', 'very serious or solemn'),
    ('grim', 'serious and depressing'),
    ('gripping', 'holding attention intensely'),
    ('gut-wrenching', 'causing deep emotional pain'),
    ('harrowing', 'deeply distressing or disturbing'),
    ('heartbreaking', 'causing great sadness'),
    ('heartfelt', 'deeply sincere and emotional'),
    ('heated', 'full of anger or excitement'),
    ('high-stakes', 'involving serious consequences'),
    ('histrionic', 'excessively dramatic or emotional'),
    ('hostile', 'showing anger or opposition'),
    ('hysterical', 'wildly emotional or frantic'),
    ('incendiary', 'likely to provoke conflict'),
    ('inflamed', 'aroused to anger or passion'),
    ('intense', 'very strong or extreme'),
    ('jaw-dropping', 'astonishingly impressive or shocking'),
    ('larger-than-life', 'strikingly vivid or exaggerated'),
    ('life-or-death', 'involving survival itself'),
    ('loaded', 'charged with hidden meaning'),
    ('manic', 'wildly energetic or emotional'),
    ('melodramatic', 'overly emotional and sensational'),
    ('momentous', 'very important and serious'),
    ('moving', 'causing strong emotion'),
    ('nerve-racking', 'causing great stress'),
    ('ominous', 'suggesting something bad ahead'),
    ('oppressive', 'heavy, harsh, and controlling'),
    ('overblown', 'exaggerated beyond reason'),
    ('overwhelming', 'too powerful to handle'),
    ('overwrought', 'too emotional or agitated'),
    ('passionate', 'showing powerful feeling'),
    ('poignant', 'deeply affecting and sad'),
    ('powerful', 'having strong emotional impact'),
    ('pregnant', 'full of meaning or tension'),
    ('provocative', 'causing strong reactions'),
    ('pulse-pounding', 'causing intense excitement'),
    ('raucous', 'loud and disorderly'),
    ('raw', 'unfiltered and deeply emotional'),
    ('red-hot', 'extremely intense or exciting'),
    ('riveting', 'extremely engaging and exciting'),
    ('savage', 'fierce and brutal'),
    ('searing', 'intensely painful or emotional'),
    ('shattering', 'deeply upsetting or shocking'),
    ('soul-stirring', 'deeply emotionally affecting'),
    ('spellbinding', 'holding complete attention'),
    ('stormy', 'marked by conflict or turmoil'),
    ('suspenseful', 'creating anxious uncertainty'),
    ('sweeping', 'broad and dramatic in scope'),
    ('tempestuous', 'full of strong emotions'),
    ('tense', 'filled with strain or suspense'),
    ('theatrical', 'overly showy or exaggerated'),
    ('thrilling', 'causing excitement and pleasure'),
    ('tormented', 'suffering intense mental pain'),
    ('tragic', 'involving terrible sadness or loss'),
    ('troubling', 'causing concern or distress'),
    ('turbulent', 'full of disorder and conflict'),
    ('unnerving', 'making someone uneasy'),
    ('uproarious', 'noisy and wildly excited'),
    ('upsetting', 'causing emotional distress'),
    ('venomous', 'full of malice or spite'),
    ('volatile', 'likely to change explosively'),
    ('white-hot', 'at peak intensity'),
    ('wild', 'uncontrolled and intense'),
    ('wrenching', 'causing deep emotional pain'),
]

USELESS = [
    ('a burden', 'something that hinders or weighs down'),
    ('a drag', 'something that holds you back'),
    ('a lemon', 'a defective, disappointing item'),
    ('a lost cause', 'impossible to improve or fix'),
    ('a waste', 'not worth the time or effort'),
    ('a write-off', 'not worth saving or using'),
    ('abortive', 'failing to produce the intended result'),
    ('absurd', 'wildly unreasonable; pointless'),
    ('baggage', 'a burden; not helpful'),
    ('ballast', 'unneeded weight; no benefit'),
    ('banal', 'so dull as to be useless'),
    ('broken', 'not working properly'),
    ('cheap', 'low quality; not effective'),
    ('counterproductive', 'having the opposite of intended effect'),
    ('crummy', 'poor in quality'),
    ('dead', 'no longer working or active'),
    ('deadwood', 'useless people or things'),
    ('defective', 'having a fault; not working'),
    ('doomed', 'certain to fail'),
    ('dud', 'something that fails to work'),
    ('dumb', 'foolish; not useful'),
    ('empty', 'lacking meaning or value'),
    ('extraneous', 'irrelevant; not needed'),
    ('faulty', 'not working correctly'),
    ('feckless', 'ineffective and irresponsible'),
    ('flimsy', 'weak and not useful'),
    ('for naught', 'without result or benefit'),
    ('fruitless', 'producing no results'),
    ('futile', 'incapable of producing results'),
    ('good-for-nothing', 'of no use or value'),
    ('gratuitous', 'unnecessary and uncalled for'),
    ('hackneyed', 'overused; lacking impact'),
    ('helpless', 'unable to do anything useful'),
    ('hollow', 'lacking real value or meaning'),
    ('hopeless', 'unlikely to succeed or improve'),
    ('idiotic', 'extremely foolish or pointless'),
    ('impractical', 'not workable in practice'),
    ('ineffective', 'not producing the desired result'),
    ('ineffectual', 'not effective; lacking impact'),
    ('inefficacious', 'not producing the desired effect'),
    ('inferior', 'lower in quality or value'),
    ('inoperable', 'not functioning or working'),
    ('inoperative', 'not in working order'),
    ('laughable', 'so bad it\'s funny'),
    ('lousy', 'very bad or poor'),
    ('low-grade', 'of poor quality'),
    ('malfunctioning', 'not operating as intended'),
    ('marginal', 'small and of little value'),
    ('meager', 'too small to be useful'),
    ('meaningless', 'without meaning or purpose'),
    ('measly', 'contemptibly small or inadequate'),
    ('minor', 'not important; of little use'),
    ('miserable', 'very poor in quality'),
    ('misguided', 'based on bad judgment; unhelpful'),
    ('needless', 'not needed; pointless'),
    ('negligible', 'so small as to be unimportant'),
    ('nominal', 'in name only; not real'),
    ('nonfunctional', 'not working or operating'),
    ('nonsensical', 'not making sense; pointless'),
    ('obsolete', 'out of date; no longer useful'),
    ('outdated', 'no longer current or useful'),
    ('outmoded', 'old-fashioned; no longer useful'),
    ('paltry', 'small or inadequate in value'),
    ('pathetic', 'pitifully inadequate or weak'),
    ('pitiful', 'very poor; deserving pity'),
    ('played out', 'no longer effective or relevant'),
    ('pointless', 'having no purpose or meaning'),
    ('powerless', 'unable to produce an effect'),
    ('puny', 'small and ineffective'),
    ('redundant', 'no longer needed or useful'),
    ('ridiculous', 'deserving mockery; pointless'),
    ('scant', 'not enough to be useful'),
    ('second-rate', 'not of the best quality'),
    ('senseless', 'lacking sense or purpose'),
    ('shoddy', 'badly made or done'),
    ('skimpy', 'insufficient; not adequate'),
    ('slipshod', 'careless and of poor quality'),
    ('sorry', 'poor in quality or value'),
    ('substandard', 'below an acceptable standard'),
    ('thin', 'lacking substance or strength'),
    ('third-rate', 'very poor in quality'),
    ('tired', 'overused; no longer effective'),
    ('to no avail', 'without success or effect'),
    ('token', 'having little practical value'),
    ('trite', 'overused; lacking value'),
    ('trivial', 'too small to matter'),
    ('unavailing', 'not achieving the intended result'),
    ('unfit', 'not suitable for a purpose'),
    ('unhelpful', 'not providing help or benefit'),
    ('unnecessary', 'not needed; serving no purpose'),
    ('unproductive', 'not yielding results or output'),
    ('unsuitable', 'not appropriate for the use'),
    ('unusable', 'not able to be used'),
    ('unworkable', 'not able to function'),
    ('vacuous', 'empty of thought or meaning'),
    ('vain', 'producing no useful result'),
    ('weak', 'lacking strength or effectiveness'),
    ('worn-out', 'used up; no longer useful'),
    ('worthless', 'having no value or use'),
    ('wretched', 'very poor or miserable'),
]

OR = [
    ('A choice of', 'an option between two or more'),
    ('A choice between', 'selecting from two things'),
    ('Alternative', 'another possibility'),
    ('Alternatively', 'in a different way'),
    ('An alternative', 'one of two or more possibilities'),
    ('Another option', 'a different choice'),
    ('As a substitute', 'instead of something else'),
    ('As a choice', 'representing a possibility'),
    ('As an alternative', 'serving as a different option'),
    ('At your discretion', 'based on your choice'),
    ('Better yet', 'a preferred alternative'),
    ('But', 'used to introduce a contrast'),
    ('By comparison', 'when compared with'),
    ('By contrast', 'in an opposite way'),
    ('Choice', 'the act of choosing'),
    ('Conversely', 'in an opposite way'),
    ('Differently', 'in another manner'),
    ('Either', 'used to refer to one of two'),
    ('Either-or', 'a choice between two'),
    ('Even if', 'despite the possibility'),
    ('Except', 'not including'),
    ('Failing that', 'if that does not happen'),
    ('Howbeit', 'nevertheless; however'),
    ('However', 'in whatever way'),
    ('If', 'on condition that'),
    ('If not', 'providing the opposite case'),
    ('In lieu of', 'instead of'),
    ('In other words', 'expressed differently'),
    ('In place of', 'substituting for'),
    ('Instead', 'as an alternative'),
    ('Instead of', 'in place of'),
    ('Lest', 'to avoid the risk of'),
    ('Moreover', 'as a further matter'),
    ('Neither', 'not one nor the other'),
    ('Nevertheless', 'in spite of that'),
    ('Nor', 'and not'),
    ('On the contrary', 'in opposition to'),
    ('On the flip side', 'looking at the opposite'),
    ('On the other hand', 'from another perspective'),
    ('Option', 'a thing that is or may be chosen'),
    ('Optionally', 'by choice'),
    ('Or else', 'otherwise'),
    ('Or rather', 'more accurately'),
    ('Otherwise', 'in different circumstances'),
    ('Preferred', 'liked better'),
    ('Rather', 'more precisely'),
    ('Rather than', 'instead of'),
    ('Replacement', 'a thing that takes the place of'),
    ('Substitute', 'a person or thing acting in place of'),
    ('Unless', 'except if'),
    ('Variant', 'a version of something'),
    ('Whereas', 'in contrast or comparison'),
    ('Whether', 'expressing a doubt or choice'),
    ('Withal', 'nevertheless; in addition'),
    ('Yet', 'but at the same time'),
    ('Along with', 'in addition to'),
    ('And/or', 'either or both'),
    ('Another way', 'a different method'),
    ('Apart from', 'except for'),
    ('As well as', 'in addition to'),
    ('Aside from', 'besides'),
    ('Besides', 'in addition to'),
    ('But also', 'used with "not only"'),
    ('Contrariwise', 'in the opposite way'),
    ('Contrarily', 'in a contrary manner'),
    ('Differing', 'being unlike'),
    ('Diversely', 'in various ways'),
    ('Else', 'in addition; otherwise'),
    ('Even', 'used for emphasis'),
    ('Excluding', 'not including'),
    ('Generally', 'in most cases'),
    ('Instead', 'in place of'),
    ('Like', 'similar to'),
    ('More', 'a greater amount'),
    ('Much', 'a large amount'),
    ('Neither', 'not either'),
    ('Next', 'immediately following'),
    ('Non', 'prefix meaning not'),
    ('Not', 'used to express negation'),
    ('Opposite', 'completely different'),
    ('Other', 'different from the one mentioned'),
    ('Otherwise', 'in another way'),
    ('Out', 'away from'),
    ('Outside', 'not within'),
    ('Plus', 'in addition to'),
    ('Rather', 'to a certain degree'),
    ('Side', 'a position or aspect'),
    ('So', 'to such a great extent'),
    ('Still', 'nevertheless'),
    ('Than', 'used in comparisons'),
    ('Then', 'at that time'),
    ('Though', 'despite the fact'),
    ('Through', 'by means of'),
    ('Unless', 'if not'),
    ('Unlike', 'not like'),
    ('Until', 'up to the time'),
    ('Versus', 'against'),
    ('Via', 'by way of'),
    ('What', 'which thing'),
    ('Whether', 'indicating choice between alternatives'),
]

SECTIONS = [
    (48, "smells", "100 Words to Describe Smells in Writing", "Scent and odor descriptors for prose, numbered 1–100.", SMELLS),
    (49, "drama", "100 Words to Describe Drama", "Intensity, conflict, and emotional stakes, numbered 1–100.", DRAMA),
    (50, "useless", "100 Words to Use Instead of &ldquo;Useless&rdquo;", "Worthless, ineffective, and pointless descriptors, numbered 1–100.", USELESS),
    (51, "or", "100 Other Words for &ldquo;Or&rdquo;", "Alternatives and choice phrasing, numbered 1–100.", OR),
]
