#!/usr/bin/env python3
"""Data for batch 9: sections 62–64 sentence-starter lists."""

CLARIFY = [
    ("Above all,", "used to stress highest importance"),
    ("All this means is", "used to explain implication"),
    ("Another way to say it is", "used to reword an idea"),
    ("As an example,", "used to illustrate a point"),
    ("As follows:", "used to introduce details"),
    ("At a basic level,", "used to explain simply"),
    ("At heart,", "used to state essence"),
    ("At its core,", "used to show central idea"),
    ("At the simplest level,", "used to simplify greatly"),
    ("Basically,", "used to simplify broadly"),
    ("Bottom line:", "used to state conclusion"),
    ("Briefly,", "used to explain concisely"),
    ("By comparison,", "used to clarify through contrast"),
    ("By contrast,", "used to show difference"),
    ("By that, I mean", "used to define a point"),
    ("By this, I mean", "used to define a term"),
    ("By way of example,", "used to provide illustration"),
    ("Chief among these is", "used to highlight top point"),
    ("Chiefly,", "used to identify main factor"),
    ("Concretely,", "used to make specific"),
    ("Consider this:", "used to focus on example"),
    ("Conversely,", "used to show opposite case"),
    ("Crucially,", "used to stress importance"),
    ("Essentially,", "used to give the gist"),
    ("For clarity,", "used to prevent confusion"),
    ("For example,", "used to introduce an example"),
    ("For instance,", "used to introduce an example"),
    ("Fundamentally,", "used to show basic meaning"),
    ("Here\u2019s how:", "used to explain method"),
    ("Here\u2019s the point:", "used to state main idea"),
    ("Here\u2019s what I mean:", "used to clarify meaning"),
    ("Here\u2019s what that means:", "used to explain significance"),
    ("Here\u2019s why:", "used to explain reason"),
    ("Imagine this:", "used to clarify through scenario"),
    ("In concrete terms,", "used to make specific"),
    ("In essence,", "used to state core meaning"),
    ("In other words,", "used to restate simply"),
    ("In plain English,", "used to explain simply"),
    ("In practical terms,", "used to explain real effect"),
    ("In that sense,", "used to clarify perspective"),
    ("In this case,", "used to narrow situation"),
    ("In this context,", "used to frame meaning"),
    ("In this sense,", "used to clarify meaning"),
    ("In this way,", "used to explain manner"),
    ("Instead,", "used to correct direction"),
    ("Let me clarify,", "used to clear up confusion"),
    ("Let me explain,", "used to introduce explanation"),
    ("Let\u2019s say", "used to introduce scenario"),
    ("Meaning,", "used to explain implication"),
    ("Mind you,", "used to add clarification"),
    ("More accurately,", "used to correct imprecision"),
    ("More precisely,", "used to state more exactly"),
    ("More specifically,", "used to add precision"),
    ("Most importantly,", "used to stress top priority"),
    ("My point is,", "used to stress intended point"),
    ("Namely,", "used to identify exactly"),
    ("Notably,", "used to draw attention"),
    ("On the other hand,", "used to show contrast"),
    ("Or rather,", "used to correct wording"),
    ("Otherwise stated,", "used to restate differently"),
    ("Overall,", "used to give big picture"),
    ("Practically speaking,", "used to explain realistically"),
    ("Primarily,", "used to identify main factor"),
    ("Put another way,", "used to rephrase clearly"),
    ("Put simply,", "used to simplify an idea"),
    ("Quite simply,", "used to simplify strongly"),
    ("Rather,", "used to refine a statement"),
    ("Say, for example,", "used to offer example"),
    ("Significantly,", "used to stress importance"),
    ("Specifically,", "used to name exact details"),
    ("Stated plainly,", "used to say directly"),
    ("Strictly speaking,", "used to be exact"),
    ("Suppose that", "used to set up scenario"),
    ("Take this example:", "used to present illustration"),
    ("Technically speaking,", "used to be technically exact"),
    ("That is,", "used to explain more exactly"),
    ("That means", "used to explain implication"),
    ("The idea here is", "used to explain purpose"),
    ("The key point is,", "used to stress main idea"),
    ("The main idea is,", "used to state central idea"),
    ("The point is,", "used to highlight main idea"),
    ("This means that", "used to explain implication"),
    ("To be clear,", "used to avoid misunderstanding"),
    ("To clarify,", "used to make meaning clearer"),
    ("To explain,", "used to introduce explanation"),
    ("To give an example,", "used to illustrate clearly"),
    ("To illustrate,", "used to make clearer"),
    ("To rephrase,", "used to say differently"),
    ("To restate,", "used to say again clearly"),
    ("To spell it out,", "used to explain fully"),
    ("Underneath it all,", "used to reveal core idea"),
    ("What I mean is,", "used to explain intended meaning"),
    ("What I\u2019m getting at is", "used to explain intended point"),
    ("What I\u2019m referring to is", "used to identify exact meaning"),
    ("What I\u2019m saying is", "used to explain intended point"),
    ("What I\u2019m trying to say is", "used to clarify intent"),
    ("What this comes down to is", "used to state essence"),
    ("What this means is", "used to explain significance"),
    ("What this shows is", "used to explain significance"),
    ("What this tells us is", "used to explain implication"),
]

TRANSITIONS = [
    ("Afterward,", "shows later time"),
    ("All the same,", "shows concession"),
    ("Also,", "adds information"),
    ("As a matter of fact,", "adds factual emphasis"),
    ("As a result,", "shows consequence"),
    ("As an illustration,", "introduces an example"),
    ("As such,", "shows resulting status"),
    ("At any rate,", "shifts to the main point"),
    ("At first,", "shows beginning stage"),
    ("At the same time,", "shows simultaneity or balance"),
    ("Because of this,", "shows cause of result"),
    ("Besides,", "adds another reason"),
    ("Beyond that,", "adds further point"),
    ("Briefly,", "signals short treatment"),
    ("By and large,", "shows general view"),
    ("By comparison,", "shows similarity or difference"),
    ("By contrast,", "shows opposing difference"),
    ("By the same token,", "shows parallel reasoning"),
    ("Consequently,", "shows logical outcome"),
    ("Conversely,", "shows reverse relation"),
    ("Correspondingly,", "shows matching relation"),
    ("Despite this,", "shows concession"),
    ("Even so,", "shows concession despite that"),
    ("Even though,", "introduces concession"),
    ("Finally,", "signals the last point"),
    ("First,", "signals the opening point"),
    ("For example,", "introduces an example"),
    ("For instance,", "introduces a specific example"),
    ("For this reason,", "shows cause for result"),
    ("Furthermore,", "adds stronger support"),
    ("However,", "shows contrast or exception"),
    ("In a similar vein,", "continues a related idea"),
    ("In addition,", "adds another point"),
    ("In any case,", "returns to the main point"),
    ("In brief,", "signals short summary"),
    ("In comparison,", "shows relation between things"),
    ("In conclusion,", "signals ending summary"),
    ("In contrast,", "shows clear difference"),
    ("In effect,", "shows practical result"),
    ("In either case,", "covers both possibilities"),
    ("In fact,", "adds emphasis or correction"),
    ("In general,", "broadens the statement"),
    ("In other words,", "restates more clearly"),
    ("In particular,", "narrows to a specific point"),
    ("In response,", "shows reaction"),
    ("In short,", "signals brief summary"),
    ("In summary,", "signals a brief recap"),
    ("In that case,", "shows conditional result"),
    ("In the end,", "shows final outcome"),
    ("In the final analysis,", "shows ultimate judgment"),
    ("In the first place,", "introduces first reason"),
    ("In the meantime,", "shows interval or overlap"),
    ("In the next place,", "moves to next point"),
    ("In the same way,", "shows similarity"),
    ("In the second place,", "introduces second reason"),
    ("In turn,", "shows sequential effect"),
    ("Instead,", "shows replacement or alternative"),
    ("Likewise,", "shows similarity"),
    ("Meanwhile,", "shows something happening simultaneously"),
    ("More importantly,", "with greater importance"),
    ("Moreover,", "adds further support"),
    ("Most importantly,", "above all in importance"),
    ("Namely,", "that is to say"),
    ("Nevertheless,", "despite that"),
    ("Next,", "shows following point or step"),
    ("Nonetheless,", "even so"),
    ("Notably,", "worth special attention"),
    ("Now,", "at this point"),
    ("On balance,", "all things considered"),
    ("On that note,", "moving from that point"),
    ("On the other hand,", "shows an alternative contrast"),
    ("Otherwise,", "if not; in another case"),
    ("Similarly,", "shows likeness"),
    ("Still,", "shows continued contrast"),
    ("That said,", "adds a qualifying contrast"),
    ("Then,", "shows next step or time"),
    ("Therefore,", "shows result or conclusion"),
    ("To be sure,", "grants a point"),
    ("To begin with,", "starts a sequence or discussion"),
    ("To clarify,", "makes meaning clearer"),
    ("To conclude,", "signals the ending"),
    ("To elaborate,", "adds more detail"),
    ("To emphasize,", "adds stress"),
    ("To explain,", "introduces explanation"),
    ("To illustrate,", "introduces an example"),
    ("To put it another way,", "restates differently"),
    ("To put it differently,", "restates in another way"),
    ("To put it simply,", "restates more simply"),
    ("To restate,", "says again differently"),
    ("To specify,", "narrows the point"),
    ("To sum up,", "signals concise summary"),
    ("To that end,", "shows intended goal"),
    ("To this end,", "shows intended purpose"),
    ("Ultimately,", "shows final result"),
    ("Under those circumstances,", "shows situational condition"),
    ("Up to a point,", "shows limited agreement"),
    ("What is more,", "adds stronger support"),
    ("Whereas,", "shows contrast between clauses"),
    ("While,", "shows contrast or simultaneity"),
    ("Yet,", "shows contrast despite that"),
]

CAUSEEFFECT = [
    ("A further consequence is", "adds another outcome"),
    ("A long-term effect is", "introduces later effect"),
    ("A major reason is that", "introduces a cause"),
    ("Accordingly,", "shows a fitting result"),
    ("An immediate result is", "introduces direct effect"),
    ("Another effect is", "adds another outcome"),
    ("Arising from this,", "shows the source cause"),
    ("As a consequence,", "shows an outcome"),
    ("As a direct result,", "shows immediate outcome"),
    ("As a result,", "shows an outcome"),
    ("As an indirect result,", "shows secondary outcome"),
    ("Because", "introduces a reason"),
    ("Bringing about", "shows resulting effect"),
    ("Brought on by", "shows originating cause"),
    ("By bringing about", "shows causation"),
    ("By causing", "shows causation"),
    ("By increasing", "shows causal mechanism"),
    ("By influencing", "shows causal mechanism"),
    ("By leading to", "shows causation"),
    ("By reducing", "shows causal mechanism"),
    ("By resulting in", "shows causation"),
    ("By triggering", "shows causation"),
    ("Caused by", "shows originating cause"),
    ("Causing", "shows resulting effect"),
    ("Chiefly because", "shows main reason"),
    ("Consequently,", "shows a result"),
    ("Contributing to", "shows partial effect"),
    ("Driven by this,", "shows motivating cause"),
    ("Due to this,", "shows a cause"),
    ("For that reason,", "shows why something follows"),
    ("For this reason,", "shows why something follows"),
    ("From this, it follows that", "draws a conclusion"),
    ("Given this,", "shows a basis"),
    ("Giving rise to", "shows resulting effect"),
    ("Hence,", "shows a result"),
    ("In consequence,", "shows a result"),
    ("In doing so,", "shows mechanism and result"),
    ("In light of this,", "shows a reasoned result"),
    ("In part because", "shows partial reason"),
    ("In reaction to this,", "shows response cause"),
    ("In response,", "shows reaction effect"),
    ("In this way,", "shows means and result"),
    ("In turn,", "shows a follow-on effect"),
    ("Influenced by", "shows originating cause"),
    ("It follows that", "states a logical result"),
    ("Largely because", "shows main reason"),
    ("Leading to", "shows resulting effect"),
    ("Mainly because", "shows main reason"),
    ("On account of this,", "shows a cause"),
    ("One consequence is", "introduces an outcome"),
    ("One effect of this is", "introduces an effect"),
    ("One factor was", "introduces a cause"),
    ("One reason is that", "introduces a cause"),
    ("Owing to this,", "shows a cause"),
    ("Partly because", "shows partial reason"),
    ("Primarily because", "shows main reason"),
    ("Prompted by this,", "shows what triggered it"),
    ("Resulting from this,", "shows the source cause"),
    ("Resulting in", "shows resulting effect"),
    ("Since", "introduces a reason"),
    ("Stemming from this,", "shows the source cause"),
    ("That explains why", "links cause and effect"),
    ("That is why", "explains the reason"),
    ("The consequence was that", "states the outcome"),
    ("The effect was that", "states the outcome"),
    ("The immediate effect was", "states direct outcome"),
    ("The long-term result was", "states later outcome"),
    ("The reason is that", "introduces a cause"),
    ("The result was that", "states the outcome"),
    ("Therefore,", "shows a logical result"),
    ("This accounts for", "explains an effect"),
    ("This arises from", "links effect to cause"),
    ("This brought about", "introduces an effect"),
    ("This can be attributed to", "links effect to cause"),
    ("This can be traced to", "links effect to cause"),
    ("This caused", "introduces an effect"),
    ("This contributed to", "shows partial cause"),
    ("This eventually led to", "shows delayed effect"),
    ("This explains why", "links cause and effect"),
    ("This follows from", "shows logical result"),
    ("This gave rise to", "introduces an effect"),
    ("This helps explain", "offers causal explanation"),
    ("This is because", "gives a reason"),
    ("This is due to", "shows a cause"),
    ("This is why", "states the reason"),
    ("This led to", "introduces an effect"),
    ("This resulted in", "introduces an effect"),
    ("This stems from", "links effect to cause"),
    ("This, in turn,", "shows chain reaction"),
    ("Thus,", "shows a result"),
    ("Triggered by this,", "shows what caused it"),
    ("Under these circumstances,", "shows context for result"),
    ("What caused this was", "introduces a cause"),
    ("What led to this was", "introduces a cause"),
    ("What resulted from this was", "introduces an effect"),
    ("Which caused", "shows linked effect"),
    ("Which contributed to", "shows linked partial cause"),
    ("Which led to", "shows linked effect"),
    ("Which resulted in", "shows linked effect"),
    ("With the result that", "shows resulting outcome"),
]

SECTIONS = [
    (
        62,
        "clarify",
        "100 Sentence Starters for Clarifying Ideas",
        "Reword, simplify, and pinpoint meaning, numbered 1\u2013100.",
        CLARIFY,
    ),
    (
        63,
        "transitions",
        "100 Sentence Starters for Transitions",
        "Connect and shift between ideas, numbered 1\u2013100.",
        TRANSITIONS,
    ),
    (
        64,
        "causeeffect",
        "100 Sentence Starters for Cause-and-Effect Essays",
        "Cause, effect, and consequence openers, numbered 1\u2013100.",
        CAUSEEFFECT,
    ),
]
