"""Batch 4 word-bank sections 36–47."""

COOL = [
    ('acceptable', 'satisfactory or allowed'),
    ('ace', 'excellent or skilled'),
    ('all right', 'acceptable or satisfactory'),
    ('amazing', 'surprisingly good or impressive'),
    ('awesome', 'extremely good or impressive'),
    ('badass', 'impressively tough or excellent'),
    ('bang-up', 'excellent or first-rate'),
    ('boss', 'excellent or impressive'),
    ('brill', 'excellent or brilliant'),
    ('brilliant', 'excellent or clever'),
    ('calm', 'not upset or excited'),
    ('chic', 'elegantly stylish'),
    ('choice', 'of superior quality'),
    ('classy', 'stylish and sophisticated'),
    ('collected', 'calm and in control'),
    ('composed', 'calm and self-controlled'),
    ('copacetic', 'fine, acceptable, or satisfactory'),
    ('cracking', 'excellent or impressive'),
    ('dandy', 'very good or fine'),
    ('decent', 'acceptable or fairly good'),
    ('delightful', 'highly pleasing'),
    ('divine', 'extremely wonderful'),
    ('dope', 'excellent or stylish'),
    ('edgy', 'boldly modern or unconventional'),
    ('elegant', 'gracefully stylish'),
    ('epic', 'impressively great'),
    ('excellent', 'exceptionally good'),
    ('exceptional', 'unusually good'),
    ('extraordinary', 'very unusual and impressive'),
    ('fabulous', 'extremely pleasing or impressive'),
    ('fantastic', 'wonderfully good'),
    ('fashionable', 'currently stylish'),
    ('fine', 'good or satisfactory'),
    ('first-class', 'excellent or superior'),
    ('first-rate', 'of the highest quality'),
    ('five-star', 'of top quality'),
    ('fresh', 'new, stylish, and appealing'),
    ('glorious', 'splendid or wonderful'),
    ('great', 'very good'),
    ('groovy', 'stylish, enjoyable, or excellent'),
    ('happening', 'fashionable and exciting'),
    ('high-quality', 'well made or excellent'),
    ('hip', 'fashionably aware or stylish'),
    ('impressive', 'deserving admiration'),
    ('in', 'fashionable at present'),
    ('incredible', 'hard to believe; amazing'),
    ('keen', 'excellent or attractive'),
    ('killer', 'extremely impressive or effective'),
    ('laid-back', 'relaxed and easygoing'),
    ('legit', 'genuinely good or valid'),
    ('levelheaded', 'calm and sensible'),
    ('lit', 'exciting or excellent'),
    ('lovely', 'very pleasant or attractive'),
    ('lush', 'very pleasing or excellent'),
    ('magnificent', 'grandly impressive or excellent'),
    ('marvelous', 'wonderfully impressive'),
    ('mint', 'excellent or perfect'),
    ('modern', 'current in style'),
    ('modish', 'fashionable or stylish'),
    ('neat', 'pleasantly good or clever'),
    ('nice', 'pleasant or good'),
    ('nifty', 'clever, stylish, or good'),
    ('okay', 'satisfactory or acceptable'),
    ('on trend', 'currently fashionable'),
    ('outstanding', 'exceptionally good'),
    ('peachy', 'fine or excellent'),
    ('phenomenal', 'extraordinarily good'),
    ('placid', 'calm and undisturbed'),
    ('pleasing', 'giving satisfaction or enjoyment'),
    ('polished', 'refined and well presented'),
    ('posh', 'elegant and expensive-looking'),
    ('rad', 'excellent or exciting'),
    ('refined', 'elegant and polished'),
    ('relaxed', 'calm and free from tension'),
    ('remarkable', 'notably impressive'),
    ('restrained', 'held back or controlled'),
    ('sensational', 'excitingly excellent'),
    ('solid', 'reliable and good'),
    ('spectacular', 'dramatically impressive'),
    ('splendid', 'impressive and very good'),
    ('stellar', 'exceptionally good'),
    ('super', 'very good'),
    ('superb', 'of excellent quality'),
    ('sweet', 'pleasing or excellent'),
    ('swell', 'very good or pleasing'),
    ('terrific', 'very good or impressive'),
    ('tight', 'excellent or impressive'),
    ('top-notch', 'excellent in quality'),
    ('top-tier', 'among the best'),
    ('tranquil', 'peaceful and calm'),
    ('trendy', 'currently fashionable'),
    ('unfazed', 'not affected or upset'),
    ('unflustered', 'calm despite pressure'),
    ('unperturbed', 'not worried or disturbed'),
    ('unruffled', 'not disturbed or upset'),
    ('voguish', 'fashionable or trendy'),
    ('wicked', 'excellent or impressive'),
    ('with-it', 'aware of current trends'),
    ('wonderful', 'very pleasing or good'),
    ('world-class', 'among the best globally'),
]

REFUSE = [
    ('Abandon', 'Leave behind; give up.'),
    ('Abjure', 'Formally renounce or reject.'),
    ('Abnegate', 'Deny oneself; reject a claim.'),
    ('Abstain', 'Choose not to take part.'),
    ('Avoid', 'Keep away from; not engage.'),
    ('Back out', 'Withdraw from an agreement.'),
    ('Balk', 'Hesitate and stop; resist.'),
    ('Bar', 'Prevent entry or participation.'),
    ('Block', 'Stop progress; obstruct.'),
    ('Boycott', 'Withdraw support as protest.'),
    ('Brush off', 'Dismiss casually; ignore.'),
    ('Call off', 'Cancel; stop planned event.'),
    ('Cancel', 'Call off; revoke.'),
    ('Cease', 'Stop doing something.'),
    ('Challenge', 'Question and oppose.'),
    ('Cold-shoulder', 'Deliberately ignore someone.'),
    ('Countermand', 'Revoke an order.'),
    ('Cut out', 'Stop; discontinue involvement.'),
    ('Decline', 'Politely say no.'),
    ('Defer', 'Postpone; delay action.'),
    ('Deny', 'State something is not true.'),
    ('Disallow', 'Not permit.'),
    ('Disavow', 'Deny responsibility or support.'),
    ('Dismiss', 'Send away; reject as unworthy.'),
    ('Disown', "Refuse to acknowledge as one's."),
    ('Dispute', 'Argue against; contest.'),
    ('Ditch', 'Abandon; drop.'),
    ('Dodge', 'Avoid by quick movement or tactics.'),
    ('Drop', 'Stop pursuing; abandon.'),
    ('Elude', 'Avoid capture or notice.'),
    ('Evade', 'Avoid dealing with directly.'),
    ('Exclude', 'Keep out; not include.'),
    ('Exit', 'Leave; withdraw from.'),
    ('Fend off', 'Repel; keep at bay.'),
    ('Forbear', 'Restrain oneself; refrain.'),
    ('Forbid', 'Order not to do.'),
    ('Forego', 'Go without; give up.'),
    ('Frown on', 'Disapprove of.'),
    ('Gainsay', 'Deny or contradict.'),
    ('Give a miss', 'Skip; not attend.'),
    ('Give up', 'Stop trying; relinquish.'),
    ('Hold back', 'Restrain; not proceed.'),
    ('Hold off', 'Delay; wait.'),
    ('Hold out', 'Resist; not yield.'),
    ('Ignore', 'Pay no attention to.'),
    ('Impede', 'Hinder; slow down.'),
    ('Invalidate', 'Make legally void.'),
    ('Jettison', 'Discard; abandon.'),
    ('Knock back', 'Reject an offer or request.'),
    ('Knock down', 'Defeat; overrule.'),
    ('Lay aside', 'Put away; set aside.'),
    ('Leave off', 'Stop; discontinue.'),
    ('Let pass', 'Allow to go by; skip.'),
    ('Naysay', 'Say no; oppose.'),
    ('Negate', 'Nullify; make ineffective.'),
    ('Object', 'Express opposition.'),
    ('Obstruct', 'Block; hinder.'),
    ('Omit', 'Leave out.'),
    ('Oppose', 'Act against; resist.'),
    ('Opt out', 'Choose not to participate.'),
    ('Overrule', 'Reject by higher authority.'),
    ('Pass on', 'Decline; not accept.'),
    ('Pass up', 'Decline to accept.'),
    ('Plead off', 'Avoid by giving an excuse.'),
    ('Preclude', 'Prevent from happening.'),
    ('Prohibit', 'Formally ban.'),
    ('Protest', 'Express strong objection.'),
    ('Put down', 'Reject harshly; dismiss.'),
    ('Put off', 'Postpone; defer.'),
    ('Rebuff', 'Reject bluntly.'),
    ('Recant', 'Take back a statement.'),
    ('Reject', 'Not accept; dismiss.'),
    ('Renounce', 'Give up a right or claim.'),
    ('Repel', 'Drive back; resist.'),
    ('Repudiate', 'Reject as invalid or untrue.'),
    ('Rescind', 'Cancel officially.'),
    ('Resist', 'Oppose force; withstand.'),
    ('Restrict', 'Limit; hold back.'),
    ('Rule out', 'Decide is impossible or excluded.'),
    ('Say no', 'Decline; not agree.'),
    ('Scorn', 'Reject with contempt.'),
    ('Scrap', 'Discard; abandon.'),
    ('Shun', 'Avoid deliberately.'),
    ('Side-step', 'Avoid an issue.'),
    ('Sit out', 'Not take part.'),
    ('Skip', 'Omit; not do.'),
    ('Snub', 'Reject by ignoring.'),
    ('Spurn', 'Reject with disdain.'),
    ('Stand firm', 'Not yield under pressure.'),
    ('Stonewall', 'Delay by refusing cooperation.'),
    ('Suspend', 'Temporarily stop.'),
    ('Turn away', 'Send away; reject entry.'),
    ('Turn down', 'Decline; reject.'),
    ('Turn off', 'Disincline; repel interest.'),
    ("Turn one's back", 'Reject; abandon support.'),
    ('Unsubscribe', 'Stop receiving a service.'),
    ('Veto', 'Officially prohibit.'),
    ('Void', 'Invalidate; cancel.'),
    ('Waive', 'Give up a right voluntarily.'),
    ('Ward off', 'Prevent; keep away.'),
]

EMPATHETICALLY = [
    ('acceptingly', 'with openness rather than judgment'),
    ('anxiously', 'with worried concern'),
    ('apologetically', 'with regretful sensitivity'),
    ('appreciatively', 'with understanding and valuing'),
    ('attentively', 'with careful, caring attention'),
    ('attunedly', 'with sensitive emotional awareness'),
    ('benevolently', 'with goodwill and kindness'),
    ('benignly', 'with gentle kindness'),
    ('bigheartedly', 'with generous kindness'),
    ('carefully', 'with attentive consideration'),
    ('caringly', 'in a caring manner'),
    ('cautiously', 'with careful sensitivity'),
    ('charitably', 'with generous understanding'),
    ('civilly', 'with respectful politeness'),
    ('comfortingly', 'in a reassuring, soothing way'),
    ('commiseratively', 'with shared sorrow or sympathy'),
    ('compassionately', 'with sympathetic concern and kindness'),
    ('considerately', 'with thought for others’ feelings'),
    ('consolingly', 'in a comforting way'),
    ('courteously', 'with polite consideration'),
    ('decently', 'with basic kindness and respect'),
    ('delicately', 'with tact and sensitivity'),
    ('diplomatically', 'with tactful consideration'),
    ('discreetly', 'with tactful carefulness'),
    ('earnestly', 'with sincere seriousness'),
    ('encouragingly', 'with supportive hope or confidence'),
    ('feelingly', 'with emotional sincerity'),
    ('forbearingly', 'with patient restraint and tolerance'),
    ('forgivingly', 'with readiness to forgive'),
    ('from the heart', 'with sincere feeling'),
    ('generously', 'with kind, open-hearted understanding'),
    ('gently', 'with softness and care'),
    ('genuinely', 'with real care or feeling'),
    ('goodheartedly', 'with honest kindness'),
    ('graciously', 'with kindness and courteous warmth'),
    ('heartfully', 'with deep sincere feeling'),
    ('helpfully', 'in a useful, supportive way'),
    ('humanely', 'with compassion and decency'),
    ('humbly', 'with modest, respectful feeling'),
    ('insightfully', 'with deep understanding'),
    ('intuitively', 'with instinctive understanding'),
    ('judiciously', 'with wise, careful understanding'),
    ('kindheartedly', 'with a kind heart'),
    ('kindly', 'in a kind and caring way'),
    ('knowingly', 'with aware understanding'),
    ('largeheartedly', 'with generous compassion'),
    ('leniently', 'with merciful tolerance'),
    ('magnanimously', 'with generous forgiveness and nobility'),
    ('meekly', 'with humble gentleness'),
    ('mercifully', 'with compassion and forgiveness'),
    ('mindfully', 'with thoughtful awareness'),
    ('movingly', 'in an emotionally touching way'),
    ('neighborly', 'with friendly helpfulness'),
    ('nonjudgmentally', 'without criticizing or condemning'),
    ('nurturingly', 'in a caring, supportive way'),
    ('observantly', 'with attentive awareness'),
    ('open-mindedly', 'with willingness to understand'),
    ('openheartedly', 'with sincere kindness and warmth'),
    ('patiently', 'with calm tolerance and understanding'),
    ('penitently', 'with sincere regret'),
    ('perceptively', 'with quick, sensitive understanding'),
    ('pityingly', 'with sorrow for another’s suffering'),
    ('poignantly', 'with touching emotional force'),
    ('politely', 'with courteous respect'),
    ('protectively', 'with caring protection'),
    ('reasonably', 'with fair understanding'),
    ('reassuringly', 'in a way that eases worry'),
    ('receptively', 'with openness to feelings'),
    ('remorsefully', 'with deep regret'),
    ('respectfully', 'with regard for dignity'),
    ('responsively', 'with attentive reaction to needs'),
    ('sensitively', 'with awareness of feelings'),
    ('sincerely', 'with genuine feeling'),
    ('softheartedly', 'with tender sympathy'),
    ('softly', 'in a gentle manner'),
    ('solicitously', 'with attentive concern'),
    ('soothingly', 'in a calming, comforting way'),
    ('soulfully', 'with deep emotional feeling'),
    ('supportively', 'in an encouraging, helpful way'),
    ('sweetly', 'with gentle kindness'),
    ('sympathetically', 'with understanding and shared concern'),
    ('tactfully', 'with sensitive social skill'),
    ('tenderheartedly', 'with gentle compassion'),
    ('tenderly', 'with gentleness and warmth'),
    ('thoughtfully', 'with careful, considerate attention'),
    ('tolerantly', 'with acceptance of differences'),
    ('touchingly', 'in a moving, tender way'),
    ('uncritically', 'without harsh judgment'),
    ('understandingly', 'with patient understanding'),
    ('uneasily', 'with troubled concern'),
    ('warmheartedly', 'with affectionate kindness'),
    ('warmly', 'with friendly sympathy'),
    ('wholeheartedly', 'with sincere, full concern'),
    ('wisely', 'with sound, considerate judgment'),
    ('with care', 'in a caring manner'),
    ('with compassion', 'in a compassionate manner'),
    ('with kindness', 'in a kind manner'),
    ('with sensitivity', 'in a sensitive manner'),
    ('with sympathy', 'in a sympathetic manner'),
    ('with understanding', 'in an understanding manner'),
]

WHEREAS = [
    ('actually', 'in fact; really'),
    ('admittedly', 'it is accepted that'),
    ('against', 'compared with; versus'),
    ('all the same', 'nevertheless; despite that'),
    ('although', 'despite the fact that'),
    ('anyhow', 'nevertheless; regardless'),
    ('anyway', 'nevertheless; regardless'),
    ('as', 'while; because'),
    ('assuming that', 'if it is true that'),
    ('at any rate', 'regardless; nevertheless'),
    ('because', 'for the reason that'),
    ('but', 'introduces a contrast'),
    ('by contrast', 'introduces a difference'),
    ('come what may', 'whatever happens'),
    ('compared to', 'in contrast with'),
    ('compared with', 'in contrast with'),
    ('concurrently', 'at the same time'),
    ('considering', 'taking into account that'),
    ('contrarily', 'in an opposite manner'),
    ('contrasted with', 'compared against'),
    ('conversely', 'from the opposite viewpoint'),
    ('despite that', 'although that is true'),
    ('despite the fact that', 'although that is true'),
    ('different from', 'unlike; not the same as'),
    ('differing from', 'being different from'),
    ('distinguished from', 'set apart from'),
    ('during the time that', 'while that happens'),
    ('during which time', 'while that happens'),
    ('even as', 'just when; while'),
    ('even so', 'nevertheless; despite that'),
    ('even though', 'despite the fact that'),
    ('for all that', 'despite that'),
    ('forasmuch as', 'considering that'),
    ('given', 'considering that'),
    ('granted', 'admittedly; even so'),
    ('granting that', 'assuming or admitting that'),
    ('having said that', 'however; despite that'),
    ('however', 'nevertheless; on the other hand'),
    ('if', 'on the condition that'),
    ('in any case', 'regardless; nevertheless'),
    ('in cases where', 'where; when'),
    ('in circumstances where', 'where; when'),
    ('in contexts where', 'where; in situations where'),
    ('in contrast', 'introduces an opposing comparison'),
    ('in fact', 'actually; in reality'),
    ('in instances where', 'where; when'),
    ('in reality', 'actually; in fact'),
    ('in situations where', 'where; when'),
    ('in spite of that', 'despite that'),
    ('in that case', 'if that is so'),
    ('in which case', 'if that happens'),
    ('inasmuch as', 'to the extent that'),
    ('irrespective', 'regardless of that'),
    ('meanwhile', 'at the same time'),
    ('much as', 'although; despite how much'),
    ('nevertheless', 'despite that; however'),
    ('no matter that', 'despite the fact that'),
    ('nonetheless', 'nevertheless; despite that'),
    ('notwithstanding', 'despite; nevertheless'),
    ('on another point', 'introducing a different contrast'),
    ('on the contrary', 'introduces the opposite point'),
    ('on the other hand', 'introduces an opposing point'),
    ('opposed to', 'in contrast with'),
    ('over against', 'as contrasted with'),
    ('presuming that', 'assuming that'),
    ('provided that', 'on condition that'),
    ('providing that', 'on condition that'),
    ('rather', 'instead; more accurately'),
    ('regardless', 'despite everything'),
    ('relative to', 'compared with'),
    ('seeing', 'considering that'),
    ('separate from', 'distinct from'),
    ('simultaneously', 'at the same time'),
    ('since', 'given that; because'),
    ('so far as', 'to the extent that'),
    ('so long as', 'during the time that'),
    ('still', 'nevertheless; even so'),
    ('supposing that', 'if it is true that'),
    ('that being said', 'even so; however'),
    ('that said', 'even so; however'),
    ('though', 'although; however'),
    ('to such extent as', 'to the degree that'),
    ('to the contrary', 'in the opposite direction'),
    ('to the extent that', 'as far as'),
    ('to the opposite effect', 'with an opposite meaning'),
    ('under conditions where', 'in conditions in which'),
    ('under which', 'in circumstances in which'),
    ('unlike', 'in contrast to'),
    ('versus', 'as contrasted with'),
    ('vis-à-vis', 'in relation to; compared with'),
    ('vs.', 'versus; compared with'),
    ('whatever the case', 'regardless of circumstances'),
    ('when', 'in the case that'),
    ('whenever', 'every time that'),
    ('where', 'in a case in which'),
    ('wherever', 'in any situation where'),
    ('while', 'at the same time; although'),
    ('whilst', 'while; although'),
    ('with that said', 'however; nevertheless'),
    ('yet', 'but; nevertheless'),
]

FLY = [
    ('abscond', 'leave secretly to avoid capture'),
    ('airlift', 'transport by aircraft'),
    ('ascend', 'move upward'),
    ('aviate', 'operate or travel by aircraft'),
    ('avoid', 'keep away from'),
    ('beat', 'move wings rhythmically'),
    ('blast', 'move very fast'),
    ('bolt', 'run away suddenly'),
    ('bounce', 'spring back or up'),
    ('bound', 'move by leaping'),
    ('break away', 'escape from control'),
    ('break loose', 'escape restraint'),
    ('buzz', 'move with a humming sound'),
    ('circle', 'move around in a circle'),
    ('circumvent', 'avoid by clever means'),
    ('clear out', 'leave a place quickly'),
    ('climb', 'move upward steadily'),
    ('course', 'move along a path'),
    ('cross', 'go across'),
    ('dart', 'move suddenly and quickly'),
    ('dash', 'move quickly and suddenly'),
    ('decamp', 'leave suddenly or secretly'),
    ('depart', 'leave a place'),
    ('descend', 'move downward'),
    ('dive', 'plunge downward through air'),
    ('drift', 'move slowly with currents'),
    ('drop', 'fall downward'),
    ('elapse', 'pass, as time'),
    ('elude', 'escape from someone'),
    ('escape', 'get away from danger'),
    ('evacuate', 'leave a dangerous place'),
    ('evade', 'avoid or escape'),
    ('fall', 'move downward through air'),
    ('flap', 'move wings up and down'),
    ('flash by', 'pass in an instant'),
    ('flee', 'run away from danger'),
    ('flit', 'move lightly and quickly'),
    ('float', 'move gently in air'),
    ('flow', 'move smoothly and continuously'),
    ('flutter', 'move with quick wingbeats'),
    ('get away', 'escape or leave quickly'),
    ('glide', 'move smoothly through air'),
    ('go', 'move or travel'),
    ('hasten', 'move or act quickly'),
    ('hop', 'make a short jump'),
    ('hover', 'remain suspended in air'),
    ('hum', 'move with a humming sound'),
    ('hurry', 'move with urgency'),
    ('jet', 'travel by jet aircraft'),
    ('journey', 'travel from one place to another'),
    ('jump', 'spring off the ground'),
    ('lapse', 'pass gradually, as time'),
    ('leap', 'rise or move suddenly'),
    ('leave', 'go away from a place'),
    ('lift off', 'rise from the ground'),
    ('loop', 'move in a loop'),
    ('make off', 'leave hurriedly, often secretly'),
    ('mount', 'rise upward'),
    ('navigate', 'steer a course through air'),
    ('orbit', 'move around a body'),
    ('pass', 'move or go by'),
    ('pilot', 'control an aircraft'),
    ('plunge', 'move suddenly downward'),
    ('propel', 'drive forward'),
    ('race', 'move at high speed'),
    ('retreat', 'move back or withdraw'),
    ('ride the air', 'move supported by air'),
    ('rise', 'move upward'),
    ('rocket', 'move upward or fast'),
    ('run away', 'flee from a place'),
    ('run off', 'leave or flee'),
    ('rush', 'move or go quickly'),
    ('sail', 'move smoothly through air'),
    ('scarper', 'run away quickly'),
    ('scram', 'leave quickly'),
    ('skedaddle', 'run away hurriedly'),
    ('skim', 'move lightly over a surface'),
    ('soar', 'rise or glide high in air'),
    ('speed', 'move rapidly'),
    ('swoop', 'descend suddenly through air'),
    ('take flight', 'start flying or fleeing'),
    ('take off', 'leave the ground'),
    ('take wing', 'begin flying away'),
    ('tear', 'move very quickly'),
    ('transfer', 'move from one place to another'),
    ('travel', 'go from place to place'),
    ('traverse', 'travel across'),
    ('vamoose', 'leave quickly'),
    ('vanish', 'disappear suddenly'),
    ('vault', 'leap over something'),
    ('waft', 'move gently through air'),
    ('whirl by', 'pass quickly in a blur'),
    ('whirr', 'move with a rapid buzzing sound'),
    ('whiz', 'move quickly with a sound'),
    ('whizz', 'move quickly with a whirring sound'),
    ('whoosh', 'move swiftly with a rushing sound'),
    ('wing', 'travel through the air'),
    ('withdraw', 'move away or back'),
    ('zip', 'move very quickly'),
    ('zoom', 'move or travel very fast'),
]

FURIOUS = [
    ('Abrasive', 'Harshly angry; rough in manner.'),
    ('Aggravated', 'Annoyed and increasingly angry.'),
    ('Agitated', 'Upset; unable to stay calm.'),
    ('Angered', 'Made angry; provoked.'),
    ('Antagonistic', 'Hostile and combative.'),
    ('Apoplectic', 'Overcome with rage.'),
    ('Ashen with anger', 'Pale from intense anger.'),
    ('Ballistic', 'Suddenly extremely angry.'),
    ('Berserk', 'Wildly violent with rage.'),
    ('Biting', 'Sharp, angry, and cutting.'),
    ('Blazing', 'Burning with anger.'),
    ('Boiling', 'Seething with rage.'),
    ('Brimful of rage', 'Filled to the top with anger.'),
    ('Burning up', 'Getting very angry.'),
    ('Choleric', 'Bad-tempered; easily angered.'),
    ('Combative', 'Ready to fight or argue.'),
    ('Cranky', 'Bad-tempered; easily annoyed.'),
    ('Crazed with anger', 'Acting wildly from rage.'),
    ('Cross', 'Irritable and angry.'),
    ('Demented', 'Wildly irrational with anger.'),
    ('Displeased', 'Annoyed; not satisfied.'),
    ('Distempered', 'Out of temper; irritable.'),
    ('Distraught', 'Deeply upset and angry.'),
    ('Dog-mad', 'Extremely angry; enraged.'),
    ('Drawn tight', 'Tense with held-in anger.'),
    ('Dyspeptic', 'Irritably discontented; peevish.'),
    ('Edgy', 'Tense and easily angered.'),
    ('Enflamed', 'Inflamed with anger.'),
    ('Enraged', 'Filled with intense anger.'),
    ('Exasperated', 'Irritated beyond patience.'),
    ('Explosive', 'Likely to erupt in anger.'),
    ('Fiery', 'Passionately angry; hot-tempered.'),
    ('Fighting mad', 'Angry enough to fight.'),
    ('Fuming', 'Showing anger and annoyance.'),
    ('Furious at heart', 'Angry deep down.'),
    ('Galled', 'Bitterly annoyed; resentful.'),
    ('Glowering', 'Staring angrily; scowling.'),
    ('Gravely offended', 'Deeply insulted and angry.'),
    ('Grim with anger', 'Stern and angry.'),
    ('Grinding rage', 'Slow, relentless anger.'),
    ('Hacked off', 'Very annoyed; angry.'),
    ('Hard-bitten', 'Tough, resentful, and angry.'),
    ('Hateful', 'Full of hostility.'),
    ('Heated', 'Angry and intense.'),
    ('Hot under the collar', 'Noticeably angry or upset.'),
    ('Hotheaded', 'Quick to anger.'),
    ('Incandescent', 'Glowing with intense anger.'),
    ('Incensed', 'Made very angry.'),
    ('Indignant', 'Angry at unfairness or insult.'),
    ('Inflamed', 'Aroused to anger or passion.'),
    ('Irate', 'Very angry.'),
    ('Irked', 'Annoyed; mildly angry.'),
    ('Irritable', 'Easily angered.'),
    ('Jealous-angry', 'Angry from jealousy.'),
    ('Jolted', 'Suddenly angered or upset.'),
    ('Jumped-up', 'Angry and confrontational.'),
    ('Justifiably angry', 'Angry for a good reason.'),
    ('Keenly offended', 'Sharply insulted; angry.'),
    ('Livid', 'Furiously angry.'),
    ('Livid with rage', 'Extremely angry.'),
    ('Loaded for bear', 'Ready for an angry confrontation.'),
    ('Losing it', 'Becoming uncontrollably angry.'),
    ('Mad', 'Angry; upset.'),
    ('Maddened', 'Driven into anger.'),
    ('Malignant', 'Spitefully hostile.'),
    ('Miffed', 'Slightly offended; annoyed.'),
    ('Molten', 'Intensely angry beneath the surface.'),
    ('Mouthy', 'Rudely argumentative; angry.'),
    ('Nasty', 'Mean-spirited and angry.'),
    ('Nettled', 'Irritated; provoked to anger.'),
    ('Offended', 'Hurt and angry.'),
    ('Outraged', 'Angry and shocked.'),
    ('Overwrought', 'Overly upset; prone to anger.'),
    ('Peeved', 'Annoyed; irritated.'),
    ('Pissed', 'Angry; irritated.'),
    ('Pissed off', 'Very angry; fed up.'),
    ('Provoked', 'Stirred to anger.'),
    ('Quarrelsome', 'Prone to arguing angrily.'),
    ('Raging', 'Violently angry.'),
    ('Rankled', 'Persistently annoyed; resentful.'),
    ('Riled', 'Annoyed and angered.'),
    ('Riled up', 'Stirred into anger.'),
    ('Ropeable', 'Extremely angry.'),
    ('Searing', 'Intensely angry; scorching.'),
    ('Seething', 'Angry but restrained.'),
    ('Shirty', 'Bad-tempered; irritable.'),
    ('Sore', 'Upset and resentful.'),
    ('Spitting mad', 'Furiously angry.'),
    ('Steamed', 'Angry; worked up.'),
    ('Steaming', 'Very angry.'),
    ('Stormy', 'Angry and turbulent.'),
    ('Strained', 'Tense from anger.'),
    ('Sulky', 'Silent and resentful.'),
    ('Sullen', 'Gloomy and resentful.'),
    ('Testy', 'Easily irritated; touchy.'),
    ('Tetchy', 'Bad-tempered; easily annoyed.'),
    ('Thin-skinned', 'Easily offended and angered.'),
    ('Touchy', 'Easily upset or angered.'),
    ('Turbulent', 'Unstable; full of anger.'),
    ('Ulcerated', 'Bitterly resentful; angry.'),
]

ELIMINATE = [
    ('Abolish', 'Officially end or cancel.'),
    ('Abrogate', 'Formally repeal or end.'),
    ('Absorb', 'Take in; remove by uptake.'),
    ('Abstain from', 'Choose not to do or use.'),
    ('Acquit', 'Clear from blame or charge.'),
    ('Amputate', 'Surgically remove a limb.'),
    ('Annihilate', 'Destroy completely.'),
    ('Annul', 'Declare invalid or void.'),
    ('Avert', 'Prevent from happening.'),
    ('Axe', 'Cut or cancel abruptly.'),
    ('Banish', 'Send away; expel.'),
    ('Bar', 'Prevent entry or access.'),
    ('Blacklist', 'Exclude from approval or access.'),
    ('Block', 'Stop movement or progress.'),
    ('Blot out', 'Obscure or erase completely.'),
    ('Break up', 'Separate into pieces or parts.'),
    ('Cancel', 'Call off; invalidate.'),
    ('Cauterize', 'Burn to seal or remove tissue.'),
    ('Censor', 'Suppress unacceptable content.'),
    ('Chop', 'Cut into pieces.'),
    ('Clear', 'Remove obstacles or unwanted items.'),
    ('Cull', 'Selectively remove.'),
    ('Curtail', 'Reduce or cut short.'),
    ('Deactivate', 'Turn off; make inactive.'),
    ('Debar', 'Exclude from participation.'),
    ('Debug', 'Remove errors from software.'),
    ('Debulk', 'Reduce mass or volume.'),
    ('Defang', 'Remove harmful power.'),
    ('Defeat', 'Overcome; put an end to.'),
    ('Defuse', 'Remove danger or tension.'),
    ('Deinstall', 'Remove installed software.'),
    ('Delete', 'Remove from a record or text.'),
    ('Demolish', 'Tear down completely.'),
    ('Deny', 'Refuse to grant or allow.'),
    ('Depose', 'Remove from office or power.'),
    ('Deprive', 'Take away something needed.'),
    ('Deracinate', 'Uproot; remove completely.'),
    ('Destroy', 'Ruin beyond repair.'),
    ('Deter', 'Discourage; prevent action.'),
    ('Disband', 'Break up an organization.'),
    ('Discard', 'Throw away; reject.'),
    ('Discharge', 'Release; dismiss from duty.'),
    ('Discontinue', 'Stop providing or producing.'),
    ('Discredit', 'Undermine trust or belief.'),
    ('Disempower', 'Remove authority or influence.'),
    ('Disengage', 'Separate; detach from involvement.'),
    ('Disinfect', 'Remove germs from surfaces.'),
    ('Dislodge', 'Force out of position.'),
    ('Dismantle', 'Take apart piece by piece.'),
    ('Dismiss', 'Send away; reject.'),
    ('Dissipate', 'Cause to disperse or fade.'),
    ('Dissolve', 'End; break up; liquefy.'),
    ('Eject', 'Force out; expel.'),
    ('End', 'Bring to a close.'),
    ('Endorse not', 'Withhold approval or support.'),
    ('Eradicate', 'Wipe out completely.'),
    ('Erase', 'Remove all traces.'),
    ('Exclude', 'Keep out; omit.'),
    ('Exempt', 'Free from requirement.'),
    ('Expel', 'Drive out; eject.'),
    ('Exterminate', 'Destroy entirely, especially pests.'),
    ('Extinguish', 'Put out a fire or light.'),
    ('Extirpate', 'Root out completely.'),
    ('Extract', 'Remove by pulling out.'),
    ('Fade out', 'Gradually disappear or end.'),
    ('Filter out', 'Remove unwanted parts.'),
    ('Finish', 'Complete; bring to an end.'),
    ('Flush', 'Wash out with water.'),
    ('Forbid', 'Prohibit; bar.'),
    ('Forestall', 'Prevent by acting first.'),
    ('Get rid of', 'Dispose of; remove.'),
    ('Grind down', 'Wear away by abrasion.'),
    ('Gut', 'Remove essential contents.'),
    ('Halt', 'Stop completely.'),
    ('Hide', 'Conceal from view.'),
    ('Hollow out', 'Remove interior material.'),
    ('Immobilize', 'Prevent movement.'),
    ('Invalidate', 'Make legally or logically void.'),
    ('Isolate', 'Separate from others.'),
    ('Jettison', 'Throw overboard; discard.'),
    ('Knock out', 'Disable; remove from action.'),
    ('Lapse', 'End through inaction.'),
    ('Liquidate', 'Close and dispose of assets.'),
    ('Lock out', 'Prevent access by locking.'),
    ('Lop off', 'Cut off a protruding part.'),
    ('Muffle', 'Reduce sound; stifle.'),
    ('Neutralize', 'Render ineffective or harmless.'),
    ('Nullify', 'Make void; cancel.'),
    ('Obliterate', 'Erase or destroy utterly.'),
    ('Omit', 'Leave out intentionally.'),
    ('Outlaw', 'Make illegal.'),
    ('Overcome', 'Successfully defeat or surmount.'),
    ('Pardon', 'Forgive; release from penalty.'),
    ('Phase out', 'Gradually stop using or producing.'),
    ('Pluck out', 'Remove by pulling.'),
    ('Pound out', 'Hammer until removed or flattened.'),
    ('Purge', 'Remove unwanted elements.'),
    ('Quash', 'Suppress; put an end to.'),
    ('Quell', 'Calm or stop forcefully.'),
    ('Raze', 'Level to the ground.'),
]

EXCITEMENT = [
    ('agitation', 'nervous or emotional excitement'),
    ('alarm', 'sudden fear or excitement'),
    ('animation', 'lively energy and spirit'),
    ('anticipation', 'excited expectation of something'),
    ('ardor', 'strong enthusiasm or passion'),
    ('arousal', 'a stirred or excited state'),
    ('avidity', 'eager desire or enthusiasm'),
    ('bliss', 'perfect happiness or joy'),
    ('bounce', 'lively energy and cheer'),
    ('brio', 'spirited energy and liveliness'),
    ('bustle', 'energetic activity and movement'),
    ('butterflies', 'nervous excitement in the stomach'),
    ('buzz', 'lively excitement or energy'),
    ('captivation', 'strongly held interest or charm'),
    ('charge', 'a feeling of energized excitement'),
    ('cheer', 'happy and lively mood'),
    ('cheerfulness', 'bright happy spirit'),
    ('commotion', 'noisy excitement or disturbance'),
    ('delight', 'great pleasure and happiness'),
    ('delirium', 'wild excitement or confusion'),
    ('disquiet', 'uneasy excitement or worry'),
    ('drive', 'strong motivation or energy'),
    ('dynamism', 'active energy and force'),
    ('eagerness', 'keen desire or readiness'),
    ('ecstasy', 'overwhelming joy or pleasure'),
    ('elation', 'great happiness and uplift'),
    ('energy', 'lively force or vigor'),
    ('enjoyment', 'pleasure in an experience'),
    ('enthusiasm', 'eager and lively interest'),
    ('euphoria', 'intense happiness and well-being'),
    ('exhilaration', 'intense happiness and excitement'),
    ('fascination', 'intense interest and attraction'),
    ('fervor', 'intense and passionate enthusiasm'),
    ('fever', 'intense excitement or agitation'),
    ('feverishness', 'restless excitement or intensity'),
    ('fire', 'intense spirit or enthusiasm'),
    ('fizz', 'bubbling liveliness or excitement'),
    ('frenzy', 'wild excitement or activity'),
    ('furor', 'public excitement or uproar'),
    ('gaiety', 'cheerful liveliness or merriment'),
    ('glee', 'lively delight or happiness'),
    ('glow', 'warm pleasure or excitement'),
    ('good cheer', 'happy, optimistic spirit'),
    ('gusto', 'hearty enthusiasm and enjoyment'),
    ('heat', 'emotional intensity or passion'),
    ('high', 'a euphoric excited feeling'),
    ('hubbub', 'busy noise and excitement'),
    ('hurly-burly', 'busy noisy commotion'),
    ('hysteria', 'uncontrolled emotional excitement'),
    ('inspiration', 'a motivating excited feeling'),
    ('intensity', 'strength of feeling or action'),
    ('intrigue', 'curious fascination or interest'),
    ('jitteriness', 'nervous, shaky excitement'),
    ('jitters', 'nervous excitement or anxiety'),
    ('joie de vivre', 'joyful enthusiasm for life'),
    ('jollity', 'cheerful sociability and fun'),
    ('joy', 'strong happiness or pleasure'),
    ('jubilation', 'joyful celebration or triumph'),
    ('keenness', 'eager interest or enthusiasm'),
    ('kick', 'a brief exciting thrill'),
    ('liveliness', 'energetic and animated quality'),
    ('madness', 'wild excitement or foolishness'),
    ('mania', 'extreme enthusiasm or obsession'),
    ('merriment', 'cheerful fun and laughter'),
    ('merriness', 'cheerful happiness and fun'),
    ('mirth', 'joyful amusement or laughter'),
    ('nervousness', 'anxious or tense feeling'),
    ('passion', 'intense feeling or enthusiasm'),
    ('pep', 'lively energy and enthusiasm'),
    ('perkiness', 'cheerful lively energy'),
    ('pleasure', 'enjoyment or happy satisfaction'),
    ('rapture', 'intense joy or delight'),
    ('relish', 'keen enjoyment or appreciation'),
    ('restlessness', 'uneasy inability to stay calm'),
    ('rush', 'a sudden thrill or surge'),
    ('spark', 'a small burst of excitement'),
    ('sparkle', 'lively charm or excitement'),
    ('spirit', 'lively courage or enthusiasm'),
    ('stimulation', 'mental or physical arousal'),
    ('stir', 'a small excitement or commotion'),
    ('suspense', 'excited uncertainty about outcomes'),
    ('tension', 'nervous excitement or strain'),
    ('thrill', 'a strong feeling of excitement'),
    ('trepidation', 'fearful nervous anticipation'),
    ('tumult', 'confused noise and excitement'),
    ('turmoil', 'confusion and emotional agitation'),
    ('twitchiness', 'jumpy nervous excitement'),
    ('uproar', 'noisy excitement or protest'),
    ('urge', 'strong desire to act'),
    ('verve', 'lively enthusiasm and style'),
    ('vibrancy', 'bright, lively energy'),
    ('vigor', 'active strength and energy'),
    ('vitality', 'lively strength and energy'),
    ('vivacity', 'lively attractiveness or energy'),
    ('warmth', 'friendly enthusiasm or feeling'),
    ('zeal', 'eager enthusiasm for something'),
    ('zest', 'lively enjoyment and enthusiasm'),
    ('zestfulness', 'lively enthusiasm and enjoyment'),
    ('zing', 'lively excitement or appeal'),
    ('zip', 'energy, speed, and liveliness'),
]

HIGHLY = [
    ('absolutely', 'completely or very much'),
    ('acutely', 'intensely or sharply'),
    ('admirably', 'in an excellent way'),
    ('amazingly', 'to a surprising degree'),
    ('astonishingly', 'in a surprising degree'),
    ('astoundingly', 'to an astonishing degree'),
    ('astronomically', 'to an extremely high degree'),
    ('awfully', 'very; extremely'),
    ('brilliantly', 'extremely well'),
    ('colossally', 'to an enormous degree'),
    ('completely', 'to the fullest extent'),
    ('considerably', 'to a large degree'),
    ('decidedly', 'clearly and strongly'),
    ('deeply', 'to a profound degree'),
    ('distinctly', 'clearly and noticeably'),
    ('dramatically', 'to a striking degree'),
    ('drastically', 'to an extreme degree'),
    ('eminently', 'to a notable degree'),
    ('enormously', 'to a very large degree'),
    ('entirely', 'completely; wholly'),
    ('especially', 'more than usually'),
    ('exceedingly', 'to an extreme degree'),
    ('exceptionally', 'more than usual'),
    ('extraordinarily', 'to an unusual degree'),
    ('extremely', 'to a very great degree'),
    ('fairly', 'to a moderate degree'),
    ('fantastically', 'extremely well or greatly'),
    ('fiercely', 'with strong intensity'),
    ('firmly', 'strongly or securely'),
    ('forcefully', 'strongly and powerfully'),
    ('fully', 'to the complete extent'),
    ('gigantically', 'to an enormous degree'),
    ('gravely', 'seriously or severely'),
    ('greatly', 'to a large degree'),
    ('heartily', 'strongly and sincerely'),
    ('hugely', 'to a very large degree'),
    ('ideally', 'in the best possible way'),
    ('immensely', 'to a very great extent'),
    ('impressively', 'in an admirable degree'),
    ('incredibly', 'to an unbelievable degree'),
    ('insanely', 'extremely; very'),
    ('intensely', 'with great intensity'),
    ('jaw-droppingly', 'to an astonishing degree'),
    ('jolly', 'very; quite'),
    ('keenly', 'intensely or sharply'),
    ('ludicrously', 'absurdly or extremely'),
    ('madly', 'extremely or intensely'),
    ('magnificently', 'in an excellent way'),
    ('majorly', 'to a great extent'),
    ('markedly', 'in a clearly noticeable way'),
    ('marvelously', 'extremely well or pleasantly'),
    ('massively', 'to a very large degree'),
    ('mind-bogglingly', 'to an astonishing degree'),
    ('monumentally', 'to a huge degree'),
    ('notably', 'in a noticeable way'),
    ('optimally', 'in the best degree'),
    ('outrageously', 'extremely or shockingly'),
    ('outstandingly', 'exceptionally well or greatly'),
    ('overly', 'too much'),
    ('particularly', 'especially or notably'),
    ('perfectly', 'completely or ideally'),
    ('phenomenally', 'exceptionally or remarkably'),
    ('powerfully', 'with strong effect'),
    ('preposterously', 'absurdly or extremely'),
    ('pretty', 'fairly; quite'),
    ('primely', 'in a first-rate way'),
    ('profoundly', 'deeply or intensely'),
    ('quite', 'fairly or completely'),
    ('radically', 'to an extreme degree'),
    ('rarely', 'unusually or exceptionally'),
    ('rather', 'to a fairly great degree'),
    ('remarkably', 'in a notably high degree'),
    ('ridiculously', 'absurdly or extremely'),
    ('robustly', 'strongly and effectively'),
    ('significantly', 'to an important degree'),
    ('strikingly', 'in a noticeable degree'),
    ('strongly', 'with great force or intensity'),
    ('stunningly', 'in an impressive degree'),
    ('substantially', 'to a considerable degree'),
    ('superbly', 'in an excellent way'),
    ('supremely', 'to the highest degree'),
    ('surprisingly', 'more than expected'),
    ('terribly', 'very; extremely'),
    ('terrifically', 'extremely well or greatly'),
    ('thoroughly', 'completely and fully'),
    ('titanically', 'to a huge degree'),
    ('totally', 'completely or very much'),
    ('tremendously', 'to a huge degree'),
    ('ultimately', 'at the highest level'),
    ('unbelievably', 'to an astonishing degree'),
    ('uncommonly', 'unusually or exceptionally'),
    ('unduly', 'more than is proper'),
    ('unusually', 'more than is usual'),
    ('utterly', 'completely or extremely'),
    ('vastly', 'to a great extent'),
    ('vehemently', 'strongly and forcefully'),
    ('very', 'to a high degree'),
    ('vigorously', 'with great energy'),
    ('wildly', 'extremely or excessively'),
    ('wonderfully', 'extremely well or pleasantly'),
]

HOPELESS = [
    ('a dead loss', 'a complete failure'),
    ('a goner', 'certain to be lost'),
    ('a lost cause', 'something that cannot succeed'),
    ('a nonstarter', 'something that cannot begin'),
    ('adrift', 'without direction or hope'),
    ('aimless', 'without purpose or direction'),
    ('at a low ebb', 'at a very low point'),
    ('at rock bottom', 'at the lowest point'),
    ('beaten', 'overcome with no fight left'),
    ('beyond help', 'unable to be helped'),
    ('beyond hope', 'impossible to save or fix'),
    ('beyond recovery', 'unable to recover'),
    ('beyond repair', 'unable to be fixed'),
    ('beyond saving', 'too damaged to rescue'),
    ('black', 'very bleak and depressing'),
    ('bleak', 'offering little or no hope'),
    ('blocked', 'prevented from moving forward'),
    ('broken', 'spiritually or emotionally defeated'),
    ("can't be done", 'impossible to accomplish'),
    ('cheerless', 'lacking cheer or hope'),
    ('cornered', 'left with no good options'),
    ('crestfallen', 'sad and disappointed'),
    ('crushed', 'overwhelmed and defeated'),
    ('cynical', 'doubting good outcomes'),
    ('dead-end', 'leading nowhere'),
    ('defeated', 'beaten and demoralized'),
    ('demoralized', 'having lost confidence and hope'),
    ('despairing', 'feeling no hope'),
    ('desperate', 'having lost hope'),
    ('disheartened', 'having lost courage or hope'),
    ('done for', 'ruined beyond saving'),
    ('doomed', 'certain to fail'),
    ('downcast', 'sad and discouraged'),
    ('downhearted', 'feeling low and discouraged'),
    ('fatalistic', 'expecting failure as inevitable'),
    ('finished', 'ended with no chance'),
    ('foiled', 'stopped from succeeding'),
    ('forlorn', 'sad and without hope'),
    ('fruitless', 'producing no results'),
    ('futile', 'incapable of producing results'),
    ('gloomy', 'dark and without hope'),
    ('good-for-nothing', 'useless or ineffective'),
    ('grim', 'harsh and without hope'),
    ('hamstrung', 'severely limited in action'),
    ('hemmed in', 'restricted with no way out'),
    ('hobbled', 'made unable to progress'),
    ('immobilized', 'unable to move or act'),
    ('impossible', 'not able to be done'),
    ('impracticable', 'not practical to do'),
    ('in despair', 'without hope'),
    ('incurable', 'unable to be cured'),
    ('ineffectual', 'not producing the desired effect'),
    ('infeasible', 'not possible to do'),
    ('irredeemable', 'impossible to improve or save'),
    ('long-shot', 'very unlikely to succeed'),
    ('lost', 'unable to find a way forward'),
    ('never going to work', 'certain not to succeed'),
    ('no chance', 'no possibility of success'),
    ('no way', 'not possible at all'),
    ('nonviable', 'not able to succeed'),
    ('not a chance', 'no possibility of success'),
    ('not happening', 'not going to occur'),
    ('out of hope', 'having no hope left'),
    ('out of moves', 'having no actions left'),
    ('out of options', 'having no choices left'),
    ('out of reach', 'impossible to obtain'),
    ('out of the question', 'not possible or acceptable'),
    ('paralyzed', 'unable to act or decide'),
    ('pessimistic', 'expecting the worst'),
    ('pinned down', 'unable to move or act'),
    ('pointless', 'having no purpose or value'),
    ('powerless', 'unable to influence events'),
    ('remote', 'very unlikely to happen'),
    ('resigned', 'accepting defeat without hope'),
    ('rudderless', 'without guidance or direction'),
    ('ruined', 'damaged beyond repair'),
    ('shot', 'worn out beyond use'),
    ('slim', 'having little chance'),
    ('spiritless', 'lacking spirit or hope'),
    ('stuck', 'unable to make progress'),
    ('stymied', 'blocked and unable to proceed'),
    ('through', 'finished and unable to continue'),
    ('thwarted', 'prevented from succeeding'),
    ('trapped', 'unable to escape or change'),
    ('unachievable', 'not possible to accomplish'),
    ('unattainable', 'not possible to achieve'),
    ('unfeasible', 'not practical or possible'),
    ('unfixable', 'cannot be fixed'),
    ('unrealizable', 'not possible to make real'),
    ('unrecoverable', 'cannot be recovered'),
    ('unsalvageable', 'cannot be saved'),
    ('untenable', 'unable to be maintained'),
    ('unviable', 'not capable of working'),
    ('unworkable', 'not able to function'),
    ('valueless', 'having no value'),
    ('woeful', 'deeply sad and hopeless'),
    ('world-weary', 'tired and disillusioned'),
    ('worthless', 'having no value or use'),
    ('wrecked', 'badly damaged and useless'),
    ('wretched', 'very unhappy and hopeless'),
]

BURDEN = [
    ('accountability', 'Responsibility for actions or results.'),
    ('affliction', 'Something causing pain or hardship.'),
    ('albatross', 'A persistent, troublesome burden.'),
    ('answerability', 'Obligation to explain or justify.'),
    ('assignment', 'A task or duty given.'),
    ('baggage', 'Emotional or practical load carried.'),
    ('ball and chain', 'A heavy restraint or obligation.'),
    ('bane', 'A cause of distress or ruin.'),
    ('bar', 'Something that prevents or hinders.'),
    ('barrier', 'Something preventing movement or progress.'),
    ('bind', 'A restrictive obligation or tie.'),
    ('brake', 'Something that slows progress.'),
    ('burthen', 'An archaic form meaning burden.'),
    ('care', 'A worry or responsibility.'),
    ('challenge', 'A demanding task or situation.'),
    ('charge', 'A duty or responsibility entrusted.'),
    ('claim', 'A demand on attention or resources.'),
    ('commitment', 'A serious obligation or promise.'),
    ('concern', 'A matter causing worry.'),
    ('cost', 'A loss or sacrifice required.'),
    ('cross', 'A personal trial or suffering.'),
    ('curse', 'Something causing great trouble.'),
    ('deadweight', 'Something useless that weighs down.'),
    ('demand', 'A pressing requirement or claim.'),
    ('difficulty', 'Something hard to deal with.'),
    ('disadvantage', 'An unfavorable condition or obstacle.'),
    ('downside', 'A negative aspect or drawback.'),
    ('drag', 'Something that slows or weighs down.'),
    ('drawback', 'A disadvantage or unwanted difficulty.'),
    ('duty', 'A moral or legal responsibility.'),
    ('emotional baggage', 'Past issues carried emotionally.'),
    ('emotional load', 'Emotional weight or responsibility.'),
    ('encumbrance', 'Something that hinders or weighs down.'),
    ('exaction', 'An excessive demand or charge.'),
    ('exertion', 'Physical or mental effort.'),
    ('expense', 'A cost or charge.'),
    ('fallout', 'Unpleasant consequences.'),
    ('fetters', 'Restraints limiting freedom or progress.'),
    ('financial load', 'Money-related burden or pressure.'),
    ('freight', 'A heavy load or cargo.'),
    ('grind', 'Long, tedious hard work.'),
    ('handicap', 'A disadvantage that limits progress.'),
    ('hangover', 'Lingering effect causing difficulty.'),
    ('hardship', 'Severe difficulty or suffering.'),
    ('heaviness', 'A feeling of weight or seriousness.'),
    ('hindrance', 'Something that makes progress difficult.'),
    ('hitch', 'A temporary difficulty or delay.'),
    ('hurdle', 'An obstacle to overcome.'),
    ('impediment', 'Something that blocks or delays progress.'),
    ('imposition', 'An unfair or unwanted demand.'),
    ('indebtedness', 'State of owing money or duty.'),
    ('labor', 'Hard work or effort.'),
    ('legacy', 'Something troublesome inherited from the past.'),
    ('liability', 'A disadvantage or responsibility causing trouble.'),
    ('limitation', 'A restricting condition or weakness.'),
    ('load', 'Something heavy to carry or bear.'),
    ('loss', 'Something given up or suffered.'),
    ('mental load', 'Invisible planning and worry work.'),
    ('millstone', 'A heavy, oppressive responsibility.'),
    ('mission', 'An assigned task or duty.'),
    ('money pit', 'Something requiring endless spending.'),
    ('necessity', 'Something unavoidable or required.'),
    ('obligation', 'Something one is required to do.'),
    ('obstacle', 'Something blocking progress or success.'),
    ('onus', 'A duty or responsibility to bear.'),
    ('oppression', 'A heavy, crushing pressure.'),
    ('ordeal', 'A very difficult experience.'),
    ('overhead', 'Ongoing cost or administrative load.'),
    ('penalty', 'A disadvantage suffered as consequence.'),
    ('plague', 'A persistent source of trouble.'),
    ('pressure', 'Demand or stress placed on someone.'),
    ('price', 'A cost paid for something.'),
    ('problem', 'A matter causing difficulty.'),
    ('psychic weight', 'Heavy mental or emotional pressure.'),
    ('repercussion', 'An indirect, troublesome consequence.'),
    ('requirement', 'Something that must be done.'),
    ('resource drain', 'Something consuming valuable resources.'),
    ('responsibility', 'A duty one must handle.'),
    ('restraint', 'Something limiting freedom or action.'),
    ('restriction', 'A limiting rule or condition.'),
    ('shackle', 'A restraint or limiting burden.'),
    ('slog', 'A long, difficult effort.'),
    ('snag', 'A small problem or obstacle.'),
    ('stewardship', 'Responsible care or management.'),
    ('strain', 'Pressure that is hard to bear.'),
    ('stress', 'Mental or emotional pressure.'),
    ('stumbling block', 'A difficulty that prevents progress.'),
    ('task', 'A piece of work required.'),
    ('tax', 'A heavy demand or strain.'),
    ('tether', 'A restraint limiting freedom.'),
    ('tie', 'A binding duty or connection.'),
    ('toll', 'A damaging cost or strain.'),
    ('trammel', 'A restriction or hindrance.'),
    ('trial', 'A difficult test or experience.'),
    ('trouble', 'Difficulty, worry, or inconvenience.'),
    ('undertaking', 'A task or project taken on.'),
    ('weight', 'A heavy pressure or responsibility.'),
    ('workload', 'Amount of work to handle.'),
    ('worry', 'A source of anxiety or concern.'),
    ('yoke', 'An oppressive duty or restraint.'),
]

MASSIVE = [
    ('abundant', 'more than enough; plentiful'),
    ('ample', 'more than enough; plentiful'),
    ('amplified', 'made greater in size or effect'),
    ('astonishing', 'very surprising in size or degree'),
    ('astounding', 'very surprising; extremely great'),
    ('astronomical', 'extremely large, especially numbers'),
    ('behemoth', 'something very large and powerful'),
    ('big', 'large in size or amount'),
    ('bountiful', 'large in quantity; generous'),
    ('brawny', 'big and strong-looking'),
    ('broad', 'wide; large across'),
    ('Brobdingnagian', 'gigantic; enormous'),
    ('bulky', 'large and hard to handle'),
    ('burly', 'large and strong'),
    ('chunky', 'thick and solidly built'),
    ('colossal', 'extremely large and impressive'),
    ('consequential', 'important; having big effects'),
    ('considerable', 'fairly large in size or amount'),
    ('copious', 'large in quantity'),
    ('countless', 'too many to count'),
    ('deep', 'extending far downward or inward'),
    ('drawn-out', 'lasting longer than expected'),
    ('earthshaking', 'very great and important'),
    ('elephantine', 'very large and heavy'),
    ('enormity', 'great size or extent'),
    ('enormous', 'extremely large'),
    ('epic', 'very large and impressive'),
    ('expansive', 'covering a wide area'),
    ('extensive', 'covering a large area or amount'),
    ('extraordinary', 'very unusual and great'),
    ('gargantuan', 'enormously large'),
    ('generous', 'more than usual in amount'),
    ('giant', 'very large; enormous'),
    ('gigantic', 'very large; giant-sized'),
    ('ginormous', 'very large; enormous'),
    ('good-sized', 'quite large'),
    ('grand', 'large and impressive'),
    ('great', 'large in amount or degree'),
    ('hefty', 'large, heavy, or substantial'),
    ('heightened', 'increased in degree'),
    ('Herculean', 'requiring great strength; huge'),
    ('huge', 'very large in size or amount'),
    ('hulking', 'large, heavy, and awkward'),
    ('humongous', 'very large; huge'),
    ('immeasurable', 'too large to measure'),
    ('immense', 'extremely large or great'),
    ('immensity', 'great size; vastness'),
    ('incalculable', 'too great to calculate'),
    ('inflated', 'made larger than normal'),
    ('innumerable', 'too many to be counted'),
    ('jam-packed', 'completely full'),
    ('jaw-dropping', 'astonishingly large or impressive'),
    ('jumbo', 'very large'),
    ('king-size', 'very large; extra large'),
    ('large', 'of great size'),
    ('lavish', 'very large or generous'),
    ('legendary', 'remarkably great in scale'),
    ('lengthy', 'long in time or length'),
    ('Leviathan', 'very large and powerful'),
    ('limitless', 'without limit; extremely great'),
    ('long', 'measuring a great distance'),
    ('magnitude', 'great size or importance'),
    ('major', 'very important or large-scale'),
    ('mammoth', 'very large; huge'),
    ('meaningful', 'important; substantial'),
    ('mega', 'very large; extremely big'),
    ('mind-blowing', 'extremely impressive or large'),
    ('monstrous', 'very large and frightening'),
    ('monumental', 'very large and important'),
    ('notable', 'worth noticing; significant'),
    ('outsize', 'unusually large'),
    ('overflowing', 'so full it spills over'),
    ('oversized', 'larger than the usual size'),
    ('packed', 'filled tightly; very full'),
    ('phenomenal', 'very great; remarkable'),
    ('plentiful', 'existing in large amounts'),
    ('prodigious', 'remarkably large in size or degree'),
    ('profuse', 'very great in amount'),
    ('protracted', 'lasting a long time'),
    ('ramped-up', 'increased quickly or strongly'),
    ('remarkable', 'unusually large or notable'),
    ('sheer', 'nothing but; very great'),
    ('sizeable', 'fairly large'),
    ('staggering', 'so large it shocks'),
    ('strapping', 'tall and strongly built'),
    ('stupendous', 'extremely large or impressive'),
    ('substantial', 'large in amount or size'),
    ('supersized', 'made much larger than usual'),
    ('sweeping', 'wide-ranging in scope'),
    ('tall', 'having great height'),
    ('teeming', 'full of; very abundant'),
    ('thickset', 'broad and solidly built'),
    ('titanic', 'of enormous size or power'),
    ('towering', 'very tall or large'),
    ('tremendous', 'very large or great'),
    ('unlimited', 'without any limit'),
    ('vast', 'very great in size or extent'),
    ('vastness', 'great size or extent'),
    ('weighty', 'important; serious; substantial'),
    ('whopping', 'very large or impressive'),
]

SECTIONS = [
    (36, "cool", "100 Best Synonyms for &ldquo;Cool&rdquo;", "Alternatives for cool or stylish/calm, numbered 1\u2013100.", COOL),
    (37, "refuse", "100 Words to Use Instead of &ldquo;Refuse&rdquo;", "Decline, reject, and avoid verbs, numbered 1\u2013100.", REFUSE),
    (38, "empathetically", "100 Best Synonyms for &ldquo;Empathetically&rdquo;", "Adverbs for sympathetic speech or action, numbered 1\u2013100.", EMPATHETICALLY),
    (39, "whereas", "100 Best Synonyms for &ldquo;Whereas&rdquo;", "Contrast and transition words, numbered 1\u2013100.", WHEREAS),
    (40, "fly", "100 Best Synonyms for &ldquo;Fly&rdquo;", "Move through air or leave quickly, numbered 1\u2013100.", FLY),
    (41, "furious", "100 Words to Use Instead of &ldquo;Furious&rdquo;", "Anger and rage descriptors, numbered 1\u2013100.", FURIOUS),
    (42, "eliminate", "100 Words to Use Instead of &ldquo;Eliminate&rdquo;", "Remove, destroy, or end verbs, numbered 1\u2013100.", ELIMINATE),
    (43, "excitement", "100 Best Synonyms for &ldquo;Excitement&rdquo;", "Thrills, energy, and eager feeling, numbered 1\u2013100.", EXCITEMENT),
    (44, "highly", "100 Best Synonyms for &ldquo;Highly&rdquo;", "Intensifying adverbs, numbered 1\u2013100.", HIGHLY),
    (45, "hopeless", "100 Words to Use Instead of &ldquo;Hopeless&rdquo;", "No hope / impossible descriptors, numbered 1\u2013100.", HOPELESS),
    (46, "burden", "100 Best Synonyms for &ldquo;Burden&rdquo;", "Weight, duty, and hardship nouns, numbered 1\u2013100.", BURDEN),
    (47, "massive", "100 Words to Use Instead of &ldquo;Massive&rdquo;", "Size and scale words, numbered 1\u2013100.", MASSIVE),
]

