#!/usr/bin/env python3

"""Data for batch 10: sections 65–71 dialogue and synonym lists."""

SAIDALTS = [
    ('accepted', 'Agreed to something offered or proposed.'),
    ('acknowledged', 'Recognized or admitted something as true.'),
    ('added', 'Included extra information after speaking.'),
    ('admitted', 'Confessed or conceded something reluctantly.'),
    ('advised', 'Suggested a course of action.'),
    ('affirmed', 'Stated firmly; confirmed as true.'),
    ('agreed', 'Expressed the same opinion; consented.'),
    ('alleged', 'Claimed without proof; asserted.'),
    ('announced', 'Made information publicly known.'),
    ('answered', 'Replied to a question or statement.'),
    ('argued', 'Gave reasons in support or opposition.'),
    ('asked', 'Requested information or an action.'),
    ('asserted', 'Stated confidently, often forcefully.'),
    ('assured', 'Told someone to remove doubt.'),
    ('begged', 'Asked urgently or desperately.'),
    ('blurted', 'Spoke suddenly without thinking.'),
    ('boasted', 'Spoke with excessive pride.'),
    ('breathed', 'Spoke softly, as if exhaling.'),
    ('broke in', 'Interrupted to speak suddenly.'),
    ('brought up', 'Introduced a topic for discussion.'),
    ('called', 'Spoke loudly to get attention.'),
    ('cautioned', 'Warned someone to be careful.'),
    ('chatted', 'Talked casually in a friendly way.'),
    ('chimed in', 'Added a comment to a conversation.'),
    ('clarified', 'Made something easier to understand.'),
    ('commanded', 'Gave an authoritative order.'),
    ('commented', 'Made a remark or observation.'),
    ('complained', 'Expressed dissatisfaction or annoyance.'),
    ('conceded', 'Admitted a point after resisting.'),
    ('confessed', 'Admitted something, often wrongdoing.'),
    ('confirmed', 'Verified something as accurate or true.'),
    ('continued', 'Kept speaking without stopping.'),
    ('countered', 'Responded with an opposing argument.'),
    ('cried', 'Spoke loudly with strong emotion.'),
    ('declared', 'Announced formally or emphatically.'),
    ('demanded', 'Asked forcefully; insisted on compliance.'),
    ('denied', 'Stated something is not true.'),
    ('described', 'Gave details about something.'),
    ('disclosed', 'Revealed information previously hidden.'),
    ('drawled', 'Spoke slowly with prolonged sounds.'),
    ('echoed', 'Repeated someone’s words or sentiment.'),
    ('elaborated', 'Added more detail or explanation.'),
    ('emphasized', 'Gave special importance to something said.'),
    ('encouraged', 'Gave support or confidence through words.'),
    ('ended', 'Concluded speaking; brought to a close.'),
    ('exclaimed', 'Spoke suddenly with strong feeling.'),
    ('explained', 'Made something clear by describing reasons.'),
    ('faltered', 'Spoke hesitantly; lost confidence briefly.'),
    ('fumed', 'Spoke angrily, showing intense irritation.'),
    ('gasped', 'Spoke while catching breath in shock.'),
    ('gestured', 'Communicated partly through a physical motion.'),
    ('grumbled', 'Spoke in a low, complaining tone.'),
    ('guessed', 'Offered an uncertain answer or estimate.'),
    ('hinted', 'Suggested indirectly without stating plainly.'),
    ('hollered', 'Shouted loudly, often from a distance.'),
    ('hummed', 'Spoke with a low, indistinct sound.'),
    ('inquired', 'Asked for information formally or politely.'),
    ('insisted', 'Demanded firmly; refused to yield.'),
    ('interjected', 'Inserted a remark abruptly.'),
    ('joked', 'Said something humorous or playful.'),
    ('jotted', 'Wrote down quickly, as if saying.'),
    ('lamented', 'Expressed sorrow or regret aloud.'),
    ('laughed', 'Spoke while laughing; showed amusement.'),
    ('mumbled', 'Spoke unclearly in a low voice.'),
    ('murmured', 'Spoke softly, almost under the breath.'),
    ('mused', 'Spoke thoughtfully; reflected aloud.'),
    ('muttered', 'Spoke in a low, irritated way.'),
    ('nagged', 'Repeatedly complained or urged persistently.'),
    ('narrated', 'Told a story or sequence of events.'),
    ('noted', 'Mentioned briefly; pointed out.'),
    ('objected', 'Expressed disagreement or opposition.'),
    ('observed', 'Remarked after noticing something.'),
    ('offered', 'Proposed something for consideration.'),
    ('ordered', 'Gave a command with authority.'),
    ('pleaded', 'Begged earnestly for something.'),
    ('pointed out', 'Drew attention to a specific detail.'),
    ('promised', 'Committed to do something in future.'),
    ('proposed', 'Suggested an idea or plan.'),
    ('protested', 'Objected strongly; expressed disapproval.'),
    ('questioned', 'Asked or challenged the truth of something.'),
    ('quipped', 'Made a witty, brief remark.'),
    ('quoted', 'Repeated exact words from a source.'),
    ('ranted', 'Spoke at length in an angry way.'),
    ('recalled', 'Spoke from memory; remembered aloud.'),
    ('remarked', 'Made a comment, often casually.'),
    ('replied', 'Responded to someone’s words.'),
    ('reported', 'Gave information about an event or issue.'),
    ('responded', 'Answered or reacted verbally.'),
    ('retorted', 'Replied sharply or angrily.'),
    ('revealed', 'Made something previously unknown known.'),
    ('shouted', 'Spoke very loudly.'),
    ('sighed', 'Spoke while exhaling in tiredness.'),
    ('snapped', 'Spoke suddenly in an angry tone.'),
    ('stated', 'Expressed something clearly and directly.'),
    ('suggested', 'Proposed an idea for consideration.'),
    ('swore', 'Spoke an oath; vowed strongly.'),
    ('teased', 'Spoke playfully to provoke or mock.'),
    ('told', 'Informed someone; narrated information.'),
    ('urged', 'Encouraged strongly; pressed for action.'),
    ('uttered', 'Spoke a word or sound.'),
]

STRONG = [
    ('Able-bodied', 'Physically fit and healthy'),
    ('Adamant', 'Unyielding; hard to persuade'),
    ('Aggressive', 'Forceful; ready to attack'),
    ('Airtight', 'Impossible to refute; watertight'),
    ('Athletic', 'Fit; physically powerful'),
    ('Authoritative', 'Commanding respect; decisive'),
    ('Beefy', 'Big and muscular'),
    ('Brawny', 'Strongly built; muscular'),
    ('Brutal', 'Harshly forceful; severe'),
    ('Bulky', 'Large and solidly built'),
    ('Capable', 'Having ability; competent'),
    ('Compact', 'Densely packed; solid'),
    ('Courageous', 'Brave under pressure'),
    ('Dauntless', 'Fearless; undeterred'),
    ('Decisive', 'Quick and firm in action'),
    ('Deep-rooted', 'Firmly established; ingrained'),
    ('Defiant', 'Boldly resisting authority'),
    ('Dependable', 'Reliable; can be trusted'),
    ('Determined', 'Resolved; persistent in purpose'),
    ('Dominant', 'Exerting control; prevailing'),
    ('Durable', 'Long-lasting; hard-wearing'),
    ('Dynamic', 'Energetic; forcefully active'),
    ('Enduring', 'Lasting; able to withstand'),
    ('Energetic', 'Full of vigor and activity'),
    ('Enforced', 'Made effective by authority'),
    ('Excellent', 'Of outstanding quality'),
    ('Exceptional', 'Unusually good; remarkable'),
    ('Fearless', 'Without fear; bold'),
    ('Ferocious', 'Fiercely intense; savage'),
    ('Firm', 'Solid; not easily moved'),
    ('Forceful', 'Powerful; compelling'),
    ('Formidable', 'Inspiring fear or respect'),
    ('Fortified', 'Strengthened; reinforced'),
    ('Hardy', 'Robust; able to endure'),
    ('Hearty', 'Robust; vigorous'),
    ('Heavy-duty', 'Built for tough use'),
    ('Herculean', 'Requiring great strength'),
    ('High-powered', 'Very effective or influential'),
    ('Immovable', 'Not able to be moved'),
    ('Impenetrable', 'Impossible to pass through'),
    ('Impervious', 'Unaffected; not penetrable'),
    ('Indomitable', 'Impossible to subdue'),
    ('Inflexible', 'Not bending; unyielding'),
    ('Influential', 'Able to affect others greatly'),
    ('Intense', 'Extremely strong in degree'),
    ('Ironclad', 'Firmly protected; unbreakable'),
    ('Jaw-dropping', 'Astonishingly impressive'),
    ('Keen', 'Highly developed; intense'),
    ('Knightly', 'Brave; honorable'),
    ('Lasting', 'Continuing for a long time'),
    ('Lionhearted', 'Very brave and bold'),
    ('Macho', 'Tough; aggressively masculine'),
    ('Major', 'Very important; significant'),
    ('Mighty', 'Very powerful or strong'),
    ('Muscular', 'Having well-developed muscles'),
    ('Nerve', 'Courage; boldness'),
    ('Nerved-up', 'Made bold; steeled oneself'),
    ('Notable', 'Worthy of attention; significant'),
    ('Obdurate', 'Stubbornly refusing to change'),
    ('Onerous', 'Hard to bear; burdensome'),
    ('Optimized', 'Made as effective as possible'),
    ('Overpowering', 'Overwhelming in strength'),
    ('Potent', 'Highly effective; strong'),
    ('Powerful', 'Having great power or force'),
    ('Prowess', 'Great skill and strength'),
    ('Punchy', 'Vigorous; impactful'),
    ('Resilient', 'Quick to recover; tough'),
    ('Resolute', 'Firmly determined'),
    ('Robust', 'Strong and healthy; sturdy'),
    ('Rock-solid', 'Very firm and dependable'),
    ('Rugged', 'Tough; able to withstand'),
    ('Stalwart', 'Loyal; strong and brave'),
    ('Steadfast', 'Firmly fixed; unwavering'),
    ('Steely', 'Hard; showing determination'),
    ('Stern', 'Strict and uncompromising'),
    ('Stout', 'Strongly built; sturdy'),
    ('Strapping', 'Tall, strong, and sturdy'),
    ('Sturdy', 'Solidly built; strong'),
    ('Tenacious', 'Holding firm; persistent'),
    ('Tough', 'Able to endure hardship'),
    ('Toughened', 'Made stronger by strain'),
    ('Towering', 'Very tall; imposing'),
    ('Unbending', 'Not yielding; rigid'),
    ('Unbreakable', 'Impossible to break; very tough'),
    ('Uncompromising', 'Not making concessions'),
    ('Undaunted', 'Not discouraged; fearless'),
    ('Undefeated', 'Never beaten; unbeaten'),
    ('Unfaltering', 'Not wavering; steady'),
    ('Unflinching', 'Not shrinking from danger'),
    ('Unshakable', 'Not easily disturbed; firm'),
    ('Valiant', 'Brave and determined'),
    ('Vigorous', 'Strong and active'),
    ('Virile', 'Having great energy or vigor'),
    ('Vital', 'Essential; full of life'),
    ('Volcanic', 'Explosively intense'),
    ('Weighty', 'Heavy; important'),
    ('Well-built', 'Solidly and strongly made'),
    ('Well-founded', 'Based on good evidence'),
    ('Well-knit', 'Closely connected; sturdy'),
    ('Wholesome', 'Health-giving; robust'),
]

PETTY = [
    ('A for effort.', 'Patronizing praise.'),
    ('Actually…', 'Pedantic, petty correction.'),
    ('Almost impressive.', 'Backhanded compliment.'),
    ('And?', 'Demands relevance rudely.'),
    ('As if.', 'Scornful disbelief.'),
    ('Big deal.', 'Mocks something unimpressive.'),
    ('Bless your heart.', 'A sugary put-down.'),
    ('Blessed with confidence.', 'Mocks unwarranted self-belief.'),
    ('Bold of you.', 'Sarcastic criticism.'),
    ('Boo hoo.', 'Mocks someone’s distress.'),
    ('Brave choice.', 'Backhanded comment on taste.'),
    ('Calm down.', 'Patronizing command.'),
    ('Congrats, I guess.', 'Reluctant, petty praise.'),
    ('Convenient.', 'Suggests suspicious self-interest.'),
    ('Cool story.', 'Sarcastically dismisses a story.'),
    ('Cry me a river.', 'Mocks someone’s complaint.'),
    ('Cute.', 'Condescending reaction.'),
    ('Embarrassing.', 'Petty condemnation.'),
    ('Figures.', 'Shows contemptuous expectation.'),
    ('For future reference.', 'Condescending advice preface.'),
    ('Get over yourself.', 'Stop acting self-important.'),
    ('Good for you.', 'A smug, minimizing remark.'),
    ('Good luck with that.', 'Doubts success sarcastically.'),
    ('Good to know.', 'Dismissive acknowledgment.'),
    ('Groundbreaking.', 'Sarcastically mocks banality.'),
    ('Happy for you.', 'Can sound resentfully polite.'),
    ('Hard pass.', 'Strong dismissive refusal.'),
    ('Heaven forbid.', 'Sarcastic exaggeration.'),
    ('Here we go again.', 'Annoyed, petty complaint.'),
    ('How convenient.', 'Suggests self-serving timing.'),
    ('How original.', 'Mocks lack of originality.'),
    ('How petty.', 'A dismissive put-down.'),
    ('How predictable.', 'Mocks lack of surprise.'),
    ('I’ll pass.', 'Rejects with cool disdain.'),
    ('I’ve had better.', 'Petty criticism of quality.'),
    ('I’ve seen better.', 'Dismissive criticism.'),
    ('I’ve seen worse.', 'Faint, petty approval.'),
    ('If you say so.', 'Dismissive lack of respect.'),
    ('Imagine that.', 'Sarcastic lack of surprise.'),
    ('In your dreams.', 'Dismisses a desire mockingly.'),
    ('Interesting choice.', 'Judges a decision snidely.'),
    ('Jealous much?', 'Taunting accusation of envy.'),
    ('Join the club.', 'Minimizes someone’s complaint.'),
    ('Just saying.', 'Petty cover for criticism.'),
    ('Keep dreaming.', 'Mocks unrealistic hopes.'),
    ('Keep telling yourself that.', 'Mocks self-delusion.'),
    ('Love that for you.', 'Often sarcastically approving.'),
    ('Mad about it?', 'Taunts emotional reaction.'),
    ('Makes sense.', 'Can sound cuttingly dismissive.'),
    ('Maybe next time.', 'Soft but petty brush-off.'),
    ('Mediocre at best.', 'Harshly dismissive judgment.'),
    ('Must be nice.', 'Envious, belittling comment.'),
    ('My heart bleeds for you.', 'Sarcastic fake sympathy.'),
    ('Nice try.', 'Dismisses a weak attempt.'),
    ('No offense, but...', 'Introduces a rude remark.'),
    ('No thanks.', 'Curt rejection.'),
    ('Nobody cares.', 'Harshly minimizes importance.'),
    ('Not everyone can pull that off.', 'Backhanded style criticism.'),
    ('Not exactly.', 'Pointed correction.'),
    ('Not my problem.', 'Cold, dismissive response.'),
    ('Not surprised.', 'Petty lack of sympathy.'),
    ('Noted.', 'Cold, curt acknowledgment.'),
    ('Of course you did.', 'Petty, unsurprised criticism.'),
    ('Okay then.', 'Dismissive closure.'),
    ('Please.', 'Scoffing dismissal.'),
    ('Poor you.', 'Sarcastic fake sympathy.'),
    ('Real classy.', 'Sarcastic criticism of behavior.'),
    ('Riveting.', 'Sarcastically calls it boring.'),
    ('Same old story.', 'Dismisses as repetitive.'),
    ('So?', 'Minimizes importance.'),
    ('Someone’s cranky.', 'Belittles irritation.'),
    ('Sounds about right.', 'Snide confirmation.'),
    ('Sure you did.', 'Accuses someone of lying.'),
    ('Sure, Jan.', 'Sarcastic disbelief.'),
    ('Technically...', 'Nitpicky correction opener.'),
    ('Tell me something new.', 'Dismisses as obvious.'),
    ('Thanks for nothing.', 'Bitterly dismisses help.'),
    ('That’s cute.', 'Condescending dismissal.'),
    ('That’s one way to do it.', 'Backhanded criticism.'),
    ('That’s rich.', 'Hypocritical or ironic criticism.'),
    ('There you go again.', 'Petty criticism of repetition.'),
    ('Touchy, aren’t we?', 'Mocks emotional reaction.'),
    ('Typical.', 'Dismissive criticism of pattern.'),
    ('Underwhelming.', 'Flatly unimpressed.'),
    ('Very on brand.', 'Snide comment on pattern.'),
    ('Welcome to reality.', 'Condescending correction.'),
    ('Well, obviously.', 'Condescending correction.'),
    ('Well, that’s something.', 'Faint, dismissive reaction.'),
    ('What a shock.', 'Sarcastically unsurprised.'),
    ('What else is new?', 'Dismissive lack of surprise.'),
    ('Whatever helps you sleep.', 'Snide disbelief or contempt.'),
    ('Who asked?', 'Dismisses unwanted input.'),
    ('With all due respect...', 'Polite preface to disrespect.'),
    ('Yawn.', 'Shows bored contempt.'),
    ('You do you.', 'Dismissive nonapproval.'),
    ('You really wore that?', 'Petty fashion jab.'),
    ('You tried.', 'Belittles effort.'),
    ('You wish.', 'Taunting rejection.'),
    ('You’re so sensitive.', 'Belittles hurt feelings.'),
    ('Your point?', 'Dismisses an argument.'),
]

TRY = [
    ('address', 'try to deal with'),
    ('aim', 'direct effort toward'),
    ('apply oneself', 'work hard at trying'),
    ('approach', 'begin to deal with'),
    ('assay', 'attempt or test'),
    ('attack', 'try to solve aggressively'),
    ('attempt', 'make an effort to do'),
    ('battle', 'try hard against difficulty'),
    ('bid for', 'attempt to obtain'),
    ('carry on', 'continue trying'),
    ('chance', 'risk attempting'),
    ('confront', 'try to face directly'),
    ('contend with', 'try to deal with'),
    ('cope', 'try to deal successfully'),
    ('court', 'try to win favor'),
    ('crack', 'try to solve'),
    ('dare', 'be bold enough to attempt'),
    ('deal with', 'try to handle'),
    ('do your best', 'try as hard as possible'),
    ('encourage', 'try to inspire action'),
    ('endeavor', 'try hard to do'),
    ('essay', 'attempt or try out'),
    ('exert oneself', 'make strong effort'),
    ('experiment', 'try something to learn'),
    ('explore', 'look into by trying'),
    ('face', 'try to deal with'),
    ('fight', 'try hard against'),
    ('figure out', 'try to understand or solve'),
    ('forge ahead', 'continue trying boldly'),
    ('gamble', 'attempt with risk'),
    ('give a whirl', 'try it informally'),
    ('give another shot', 'try once more'),
    ('give it a whirl', 'try it informally'),
    ('go after', 'try to get'),
    ('go for it', 'attempt it boldly'),
    ('go on', 'continue trying'),
    ('grapple with', 'try hard to handle'),
    ('have a bash', 'make an attempt'),
    ('have a crack', 'make an attempt'),
    ('have a go', 'make an attempt'),
    ('have a run at', 'attempt energetically'),
    ('have another crack', 'try once more'),
    ('have another go', 'try once more'),
    ('hazard', 'venture to attempt'),
    ('hunt for', 'try to find'),
    ('improve', 'try to make better'),
    ('improvise', 'try by making up'),
    ('induce', 'try to cause'),
    ('iron out', 'try to resolve problems'),
    ('keep at it', 'continue trying'),
    ('labor', 'work hard at'),
    ('look for', 'try to find'),
    ('make a bid', 'attempt to achieve'),
    ('make a play for', 'try to obtain'),
    ('make a run at', 'attempt energetically'),
    ('make a start', 'begin trying'),
    ('make an effort', 'try with effort'),
    ('make another attempt', 'try once more'),
    ('make for', 'try to reach'),
    ('persist', 'continue trying despite difficulty'),
    ('persuade', 'try to convince'),
    ('plug away', 'keep trying steadily'),
    ('practice', 'try repeatedly to improve'),
    ('press', 'try to persuade insistently'),
    ('probe', 'investigate by testing'),
    ('pursue', 'work toward achieving'),
    ('put to the test', 'test in practice'),
    ('reach for', 'try to attain'),
    ('refine', 'try to improve slightly'),
    ('resume', 'start trying again'),
    ('retry', 'try again'),
    ('revise', 'try to improve by changing'),
    ('revisit', 'try again with review'),
    ('rework', 'try to improve again'),
    ('road-test', 'test in real use'),
    ('sample', 'use or taste briefly'),
    ('search for', 'try to find'),
    ('see if you can', 'attempt if possible'),
    ('seek', 'try to obtain or achieve'),
    ('set out to', 'begin trying to'),
    ('shoot for', 'aim to achieve'),
    ('sort out', 'try to resolve'),
    ('strive', 'make great efforts toward'),
    ('tackle', 'try to deal with'),
    ('take a chance', 'attempt despite uncertainty'),
    ('take a shot', 'make an attempt'),
    ('take a stab', 'make an attempt'),
    ('take another stab', 'try once more'),
    ('take on', 'undertake and attempt'),
    ('test', 'use to see if works'),
    ('toil', 'work hard at'),
    ('undertake', 'begin and attempt'),
    ('urge', 'try to persuade strongly'),
    ('venture', 'dare to attempt'),
    ('wing it', 'try without preparation'),
    ('work at', 'make effort on'),
    ('work out', 'try to solve or settle'),
    ('work through', 'try to deal with'),
    ('work toward', 'try to achieve'),
    ('wrestle with', 'struggle to handle or solve'),
]

THING = [
    ('Accessory', 'Extra item added for use.'),
    ('Act', 'A specific deed or action.'),
    ('Activity', 'Something done; an undertaking.'),
    ('Adapter', 'Device enabling connection or use.'),
    ('Adjustment', 'A small change made.'),
    ('Agent', 'Something that causes an effect.'),
    ('Agreement', 'A mutual understanding or contract.'),
    ('Aim', 'A goal or intended outcome.'),
    ('Alternative', 'Another option or choice.'),
    ('Amenity', 'Feature providing comfort or convenience.'),
    ('Apparatus', 'Equipment for a particular purpose.'),
    ('Application', 'A program or practical use.'),
    ('Approach', 'A method or way of doing.'),
    ('Arrangement', 'An organized setup or plan.'),
    ('Artifact', 'An object made by humans.'),
    ('Aspect', 'A particular part or feature.'),
    ('Assignment', 'A task given to someone.'),
    ('Attachment', 'An added part or supplement.'),
    ('Attribute', 'A quality or characteristic.'),
    ('Avenue', 'A possible route or means.'),
    ('Background', 'Context or underlying information.'),
    ('Badge', 'A small identifying emblem.'),
    ('Benefit', 'A helpful result or advantage.'),
    ('Blueprint', 'A detailed plan or design.'),
    ('Body', 'A physical mass or main part.'),
    ('Booklet', 'A small informational publication.'),
    ('Breakdown', 'A detailed analysis or separation.'),
    ('Bundle', 'A group of items together.'),
    ('Business', 'A matter requiring attention.'),
    ('Case', 'An instance or example.'),
    ('Category', 'A class or grouping.'),
    ('Cause', 'A reason something happens.'),
    ('Challenge', 'A difficult task or problem.'),
    ('Characteristic', 'A distinguishing quality or trait.'),
    ('Choice', 'A selected option.'),
    ('Circumstance', 'A condition affecting a situation.'),
    ('Clause', 'A distinct part of a text.'),
    ('Component', 'A part of a larger whole.'),
    ('Concept', 'An idea or mental model.'),
    ('Concern', 'A matter of interest or worry.'),
    ('Condition', 'A state or requirement.'),
    ('Configuration', 'An arrangement of parts or settings.'),
    ('Consideration', 'A factor taken into account.'),
    ('Constraint', 'A limiting rule or condition.'),
    ('Construction', 'Something built or assembled.'),
    ('Content', 'What is contained or expressed.'),
    ('Context', 'Surrounding circumstances or setting.'),
    ('Contraption', 'A strange or complex device.'),
    ('Contribution', 'Something given to help.'),
    ('Core', 'The central or essential part.'),
    ('Craft', 'A skilled making activity.'),
    ('Creation', 'Something made or produced.'),
    ('Criterion', 'A standard for judgment.'),
    ('Data point', 'A single piece of information.'),
    ('Deal', 'An agreement or arrangement.'),
    ('Decision', 'A choice made after thought.'),
    ('Detail', 'A small specific part.'),
    ('Device', 'A tool made for a purpose.'),
    ('Difficulty', 'A problem or obstacle.'),
    ('Dimension', 'An aspect or measurable extent.'),
    ('Document', 'A written or recorded item.'),
    ('Element', 'A basic part or factor.'),
    ('Endeavor', 'A serious effort or project.'),
    ('Entity', 'Something that exists independently.'),
    ('Equipment', 'Tools used for a task.'),
    ('Essence', 'The most important quality.'),
    ('Event', 'Something that happens.'),
    ('Example', 'A representative instance.'),
    ('Exercise', 'A practice activity or drill.'),
    ('Experience', 'An event lived through.'),
    ('Experiment', 'A test to learn something.'),
    ('Fact', 'A true piece of information.'),
    ('Factor', 'Something influencing an outcome.'),
    ('Feature', 'A notable part or characteristic.'),
    ('Fixture', 'A fixed installed item.'),
    ('Format', 'A particular arrangement or style.'),
    ('Framework', 'A supporting structure or system.'),
    ('Function', 'A purpose or role.'),
    ('Gadget', 'A small useful device.'),
    ('Gear', 'Equipment needed for an activity.'),
    ('Goal', 'An intended result.'),
    ('Good', 'An item for sale or use.'),
    ('Handle', 'A part used to hold.'),
    ('Hardware', 'Physical tools or computer components.'),
    ('Headline', 'Main title or key point.'),
    ('Idea', 'A thought or suggestion.'),
    ('Implementation', 'The act of putting into effect.'),
    ('Improvement', 'A change that makes better.'),
    ('Incident', 'An occurrence, often notable.'),
    ('Indicator', 'A sign pointing to something.'),
    ('Information', 'Knowledge communicated or received.'),
    ('Ingredient', 'A component in a mixture.'),
    ('Initiative', 'A new plan or effort.'),
    ('Input', 'Something contributed to a process.'),
    ('Instance', 'A particular occurrence or case.'),
    ('Instrument', 'A tool for precise work.'),
    ('Issue', 'A problem or topic.'),
    ('Item', 'A single article or unit.'),
    ('Job', 'A task or piece of work.'),
    ('Key', 'A crucial element or solution.'),
]

INDIRECT = [
    ('Can I ask where you got that?', 'Asks about the source politely.'),
    ('Can you tell me how she feels?', 'Asks about her feelings.'),
    ('Can you tell me how this works?', 'Asks for an explanation indirectly.'),
    ('Can you tell me if she’s okay?', 'Asks whether she is okay.'),
    ('Can you tell me what he does?', 'Asks about occupation indirectly.'),
    ('Can you tell me what you saw?', 'Asks about what was seen.'),
    ('Can you tell me when lunch is?', 'Asks about lunch time.'),
    ('Can you tell me when to stop?', 'Asks about stopping time.'),
    ('Can you tell me where to park?', 'Asks for parking location.'),
    ('Can you tell me who is next?', 'Asks about order indirectly.'),
    ('Can you tell me who paid?', 'Asks about the payer.'),
    ('Can you tell me who to contact?', 'Asks for the right contact.'),
    ('Can you tell me why it matters?', 'Asks for importance indirectly.'),
    ('Can you tell me why she cried?', 'Asks for the reason.'),
    ('Can you tell me why she left?', 'Asks for her reason indirectly.'),
    ('Could you tell me how old he is?', 'Asks about age politely.'),
    ('Could you tell me how to start?', 'Asks for starting method.'),
    ('Could you tell me if they won?', 'Asks whether they won.'),
    ('Could you tell me what she said?', 'Asks about her words.'),
    ('Could you tell me what to do?', 'Asks for guidance politely.'),
    ('Could you tell me when to leave?', 'Asks about departure time.'),
    ('Could you tell me where he is?', 'Asks for his location indirectly.'),
    ('Could you tell me where he went?', 'Asks about destination indirectly.'),
    ('Could you tell me where to wait?', 'Asks about waiting place.'),
    ('Could you tell me who that is?', 'Asks about a person’s identity.'),
    ('Do you have any idea who won?', 'Asks about the winner indirectly.'),
    ('Do you know how far it is?', 'Asks about distance indirectly.'),
    ('Do you know how much it costs?', 'Asks about cost indirectly.'),
    ('Do you know how she did it?', 'Asks about method indirectly.'),
    ('Do you know how to reach her?', 'Asks how to contact her.'),
    ('Do you know what caused this?', 'Asks about the cause.'),
    ('Do you know what she wants?', 'Asks about her wishes.'),
    ('Do you know what this is for?', 'Asks about purpose indirectly.'),
    ('Do you know what time it is?', 'Asks for the time indirectly.'),
    ('Do you know when they met?', 'Asks about meeting time.'),
    ('Do you know where she works?', 'Asks about workplace indirectly.'),
    ('Do you know where the keys are?', 'Asks about key location.'),
    ('Do you know where to turn?', 'Asks for direction indirectly.'),
    ('Do you know whether he called?', 'Asks if he called.'),
    ('Do you know whether it’s safe?', 'Asks if something is safe.'),
    ('Do you know whether they agree?', 'Asks if they agree.'),
    ('Do you know which one is mine?', 'Asks about ownership indirectly.'),
    ('Do you know who made this?', 'Asks about the maker.'),
    ('Do you know why he’s upset?', 'Asks for his reason.'),
    ('Do you know why they canceled?', 'Asks for the cancellation reason.'),
    ('Do you remember how it ended?', 'Asks about the ending.'),
    ('Do you remember what he said?', 'Asks about past words.'),
    ('Do you remember where we met?', 'Asks about a past place.'),
    ('Do you remember who invited us?', 'Asks about the inviter.'),
    ('I was wondering how you knew.', 'Asks about source of knowledge.'),
    ('I was wondering if it’s true.', 'Asks whether something is true.'),
    ('I was wondering what to wear.', 'Asks for clothing guidance.'),
    ('I was wondering what you think.', 'Asks for an opinion politely.'),
    ('I was wondering where to sit.', 'Asks about seating politely.'),
    ('I was wondering who sent it.', 'Asks about the sender politely.'),
    ('I wonder how she managed.', 'Asks about method indirectly.'),
    ('I wonder if he understands.', 'Asks whether he understands.'),
    ('I wonder if she agrees.', 'Asks whether she agrees.'),
    ('I wonder if they are ready.', 'Expresses uncertainty about readiness.'),
    ('I wonder what he meant.', 'Asks about intended meaning.'),
    ('I wonder when they will decide.', 'Asks about decision time.'),
    ('I wonder where this road leads.', 'Asks about destination indirectly.'),
    ('I wonder whether he noticed.', 'Asks if he noticed.'),
    ('I wonder whether it’s open.', 'Asks if something is open.'),
    ('I wonder who she is with.', 'Asks about her company.'),
    ('I wonder why they laughed.', 'Asks for the reason indirectly.'),
    ('I’d like to ask what happened.', 'Asks about an event politely.'),
    ('I’d like to find out who called.', 'Asks about the caller.'),
    ('I’d like to know how it began.', 'Asks about the beginning.'),
    ('I’d like to know how many came.', 'Asks about number of people.'),
    ('I’d like to know if he’s here.', 'Asks whether he is present.'),
    ('I’d like to know what changed.', 'Asks about a change.'),
    ('I’d like to know what he wants.', 'Asks about his wishes.'),
    ('I’d like to know what you need.', 'Asks about someone’s needs.'),
    ('I’d like to know when it starts.', 'Asks about the starting time.'),
    ('I’d like to know when to begin.', 'Asks about start time.'),
    ('I’d like to know where to begin.', 'Asks about starting point.'),
    ('I’d like to know who is coming.', 'Asks about expected people.'),
    ('I’d like to know who wrote it.', 'Asks about the writer.'),
    ('I’d like to know why he stayed.', 'Asks for his reason.'),
    ('I’d like to know why they left.', 'Asks for their reason.'),
    ('May I ask how this happened?', 'Polite question about the cause.'),
    ('May I ask what you mean?', 'Polite request for clarification.'),
    ('May I ask when you’re free?', 'Polite question about availability.'),
    ('May I ask where this goes?', 'Polite question about destination.'),
    ('May I know if it’s ready?', 'Polite question about readiness.'),
    ('May I know what this says?', 'Polite question about meaning.'),
    ('May I know who approved it?', 'Polite question about responsibility.'),
    ('Might I ask why that is?', 'Very polite question about reason.'),
    ('Please tell me what went wrong.', 'Request for an explanation.'),
    ('Please tell me when it ends.', 'Request for the ending time.'),
    ('Please tell me where it hurts.', 'Request for pain location.'),
    ('Please tell me who to see.', 'Request for the right person.'),
    ('Would you explain who won?', 'Asks for the winner indirectly.'),
    ('Would you explain why it failed?', 'Asks for the reason indirectly.'),
    ('Would you mind saying why?', 'Polite indirect request for a reason.'),
    ('Would you say how it works?', 'Polite question about operation.'),
    ('Would you say what changed?', 'Polite question about differences.'),
    ('Would you tell us what happened?', 'Asks for events indirectly.'),
    ('Would you tell us who called?', 'Asks for caller indirectly.'),
]

REPLIED = [
    ('Acknowledged', 'Showed receipt or recognition.'),
    ('Added', 'Included extra information.'),
    ('Addressed', 'Responded to a point raised.'),
    ('Admitted', 'Accepted as true or valid.'),
    ('Advised', 'Gave guidance in response.'),
    ('Affirmed', 'Stated agreement or confirmation.'),
    ('Agreed', 'Expressed concurrence.'),
    ('Answered', 'Gave a response to a question.'),
    ('Appealed', 'Made a request in response.'),
    ('Argued', 'Responded with reasons or objections.'),
    ('Assented', 'Expressed agreement.'),
    ('Assured', 'Gave confidence or certainty.'),
    ('Attested', 'Confirmed as accurate.'),
    ('Backed up', 'Supported a claim in response.'),
    ('Barked back', 'Replied sharply or rudely.'),
    ('Beckoned back', 'Called back in response.'),
    ('Blurted', 'Spoke suddenly without planning.'),
    ('Bridged', 'Linked back with a response.'),
    ('Broadcast', 'Sent a reply widely.'),
    ('Cabled', 'Sent a reply by cable.'),
    ('Called back', 'Returned a phone response.'),
    ('Came back', 'Returned with a response.'),
    ('Came back with', 'Produced an answer or retort.'),
    ('Cautioned', 'Warned in response.'),
    ('Chimed in', 'Added a brief response.'),
    ('Clapped back', 'Responded with a sharp retort.'),
    ('Clarified', 'Made a response clearer.'),
    ('Commented', 'Gave a remark in response.'),
    ('Conceded', 'Yielded a point in response.'),
    ('Concurred', 'Agreed in response.'),
    ('Confirmed', 'Verified or validated in response.'),
    ('Countered', 'Answered with an opposing point.'),
    ('Cracked', 'Made a quick remark.'),
    ('Declared', 'Stated firmly in response.'),
    ('Deflected', 'Avoided by shifting the response.'),
    ('Denied', 'Stated something was untrue.'),
    ('Disagreed', 'Expressed a differing view.'),
    ('Dished back', 'Returned an insult or jab.'),
    ('Echoed', 'Repeated or mirrored a response.'),
    ('Elaborated', 'Added detail to the response.'),
    ('Emphasized', 'Stressed a point in response.'),
    ('Encouraged', 'Offered support in response.'),
    ('Engaged', 'Responded by participating.'),
    ('Explained', 'Made reasons or details clear.'),
    ('Fired back', 'Replied quickly and forcefully.'),
    ('Fired off', 'Sent a quick response.'),
    ('Followed up', 'Responded with additional contact.'),
    ('Gave feedback', 'Provided evaluative response.'),
    ('Gave word', 'Promised in response.'),
    ('Granted', 'Allowed or conceded in response.'),
    ('Greeted back', 'Returned a greeting.'),
    ('Hollered back', 'Shouted a response back.'),
    ('Implied', 'Responded indirectly by suggestion.'),
    ('Inquired back', 'Asked a question in response.'),
    ('Interjected', 'Inserted a remark in response.'),
    ('Issued a statement', 'Released an official response.'),
    ('Joked', 'Responded with humor.'),
    ('Justified', 'Gave reasons to defend.'),
    ('Kicked back', 'Returned a response or reaction.'),
    ('Lashed back', 'Replied angrily or harshly.'),
    ('Let on', 'Revealed in response.'),
    ('Messaged back', 'Sent a response message.'),
    ('Mumbled', 'Replied quietly and unclearly.'),
    ('Nodded back', 'Responded with a nod.'),
    ('Noted', 'Mentioned briefly in response.'),
    ('Objected', 'Expressed opposition in response.'),
    ('Offered', 'Presented something in response.'),
    ('Opined', 'Gave an opinion in response.'),
    ('Parried', 'Avoided or deflected a remark.'),
    ('Piped up', 'Spoke up with a response.'),
    ('Pled', 'Made an earnest request.'),
    ('Pointed out', 'Highlighted a detail in response.'),
    ('Posted back', 'Replied via an online post.'),
    ('Protested', 'Responded with strong objection.'),
    ('Queried', 'Asked in response.'),
    ('Quipped', 'Made a witty response.'),
    ('Quoted', 'Replied by citing words.'),
    ('Reassured', 'Comforted in response.'),
    ('Rebuffed', 'Rejected a request or advance.'),
    ('Reciprocated', 'Returned a response in kind.'),
    ('Rejoined', 'Made a reply, often quickly.'),
    ('Reminded', 'Brought back to attention.'),
    ('Reported back', 'Gave results in response.'),
    ('Responded', 'Gave an answer or reaction.'),
    ('Retorted', 'Replied sharply or wittily.'),
    ('Returned', 'Gave back an answer.'),
    ('Revealed', 'Disclosed information in response.'),
    ('Roared back', 'Shouted an intense response.'),
    ('Said back', 'Spoke in return.'),
    ('Seconded', 'Expressed support for a motion.'),
    ('Sent word', 'Communicated a response.'),
    ('Shot back', 'Replied quickly and sharply.'),
    ('Shrugged off', 'Dismissed with a minimal response.'),
    ('Signaled back', 'Responded with a signal.'),
    ('Snapped back', 'Replied irritably or abruptly.'),
    ('Spoke up', 'Answered audibly or assertively.'),
    ('Stated', 'Expressed in words clearly.'),
    ('Submitted', 'Provided an answer formally.'),
    ('Suggested', 'Proposed an idea in response.'),
    ('Texted back', 'Replied by text message.'),
]

SECTIONS = [
    (65, "saidalts", "100 Words to Use Instead of &ldquo;Said&rdquo;",
     "Dialogue-tag alternatives with meanings, numbered 1–100. Complements section 1.", SAIDALTS),
    (66, "strong", "100 Best Synonyms for &ldquo;Strong&rdquo;",
     "Strength, power, and resolve words, numbered 1–100.", STRONG),
    (67, "petty", "100 Petty Comments",
     "Snide, sarcastic, and dismissive lines, numbered 1–100.", PETTY),
    (68, "try", "100 Best Synonyms for &ldquo;Try&rdquo;",
     "Effort and attempt verbs, numbered 1–100.", TRY),
    (69, "thing", "100 Words to Use Instead of &ldquo;Thing&rdquo;",
     "More precise nouns than thing, numbered 1–100.", THING),
    (70, "indirect", "100 Examples of Indirect Questions",
     "Polite and soft question forms, numbered 1–100.", INDIRECT),
    (71, "replied", "100 Other Words for &ldquo;Replied&rdquo;",
     "Response verbs and reply beats, numbered 1–100.", REPLIED),
]

