#!/usr/bin/env python3
"""Data for batch 7: sections 53–58 dialogue and craft lists."""

CONDOLENCES = [
    ("A loss felt by us all", "Acknowledges that others share the sorrow."),
    ("Accept my heartfelt condolences", "Formally offers warm, sincere condolences."),
    ("Accept my sincere sympathy", "Formally offers genuine personal compassion."),
    ("All my love in your sorrow", "Offers wholehearted affection during sadness."),
    ("All my sympathy is with you", "Offers complete compassion and emotional support."),
    ("Awfully sorry about your loss", "Expresses sincere sorrow in everyday language."),
    ("Be assured of my sympathy", "Formally promises heartfelt support and concern."),
    ("Beside you in sorrow", "Offers companionship during deep sadness."),
    ("Comfort and peace be with you", "Offers continuing consolation and tranquility."),
    ("Condolences to you and yours", "Extends sympathy to the bereaved family."),
    ("Deep sorrow at your loss", "Conveys profound sadness about the death."),
    ("Deepest condolences on your loss", "Offers strong and formal sympathy."),
    ("Deepest sympathies to you", "Directly offers profound sympathy."),
    ("Every comfort to you and yours", "Wishes solace for the entire family."),
    ("Expressing sorrow for your loss", "Directly communicates sadness and sympathy."),
    ("Extending sympathy at this time", "Offers formal support during bereavement."),
    ("God be with you in your grief", "Invokes divine presence during mourning."),
    ("God bless you in this sorrow", "Invokes divine care during sadness."),
    ("Grieving with you", "Expresses companionship in grief."),
    ("Heartfelt condolences to you", "Directly offers warm and sincere condolences."),
    ("I can’t imagine your pain", "Recognizes the likely depth of suffering."),
    ("I grieve with you", "Joins the bereaved in their grief."),
    ("I mourn with you", "Expresses shared mourning after a death."),
    ("I share in your sorrow", "Acknowledges and participates in their sadness."),
    ("I share your grief", "Expresses solidarity with someone who is grieving."),
    ("I was deeply saddened to hear", "Expresses profound sadness upon learning of death."),
    ("I was heartbroken to hear", "Expresses intense sadness upon hearing the news."),
    ("I wish you strength and comfort", "Offers resilience and reassurance during mourning."),
    ("I’m deeply saddened", "Expresses profound sadness about the death."),
    ("I’m heartbroken for you", "Expresses intense compassion and sadness."),
    ("I’m saddened by your loss", "Shares sadness over the person’s death."),
    ("I’m so sorry for your loss", "A warm, standard expression of sympathy."),
    ("I’m sorry to hear this sad news", "Responds sympathetically to news of death."),
    ("Love and prayers are with you", "Offers affection and continuing spiritual support."),
    ("Love and strength to you", "Offers affection and resilience during grief."),
    ("May comfort surround you", "Wishes abundant reassurance and support."),
    ("May God comfort you", "A religious wish for divine consolation."),
    ("May God grant you peace", "A religious wish for divine peace."),
    ("May love surround you", "Wishes loving support throughout bereavement."),
    ("May memories bring you comfort", "Hopes memories ease the person’s grief."),
    ("May peace be with you", "Offers a gentle wish for peace."),
    ("May their memory comfort you", "Hopes remembrance provides consolation."),
    ("May their soul rest in peace", "A religious wish for the deceased."),
    ("May you find comfort", "Wishes consolation during grief."),
    ("My heart aches for you", "Expresses heartfelt pain for the bereaved."),
    ("My heart goes out to you", "Conveys deep compassion for someone’s suffering."),
    ("My thoughts are with you", "Expresses attentive care and emotional support."),
    ("Our deepest sympathies", "A concise collective expression of profound sympathy."),
    ("Our heartfelt condolences", "A warm collective condolence message."),
    ("Our hearts are with you", "Collectively expresses emotional closeness and support."),
    ("Our hearts go out to you", "Collectively conveys deep compassion."),
    ("Our love is with you", "Collectively offers affection during bereavement."),
    ("Our prayers are with you", "Collectively offers continuing spiritual support."),
    ("Our sincere condolences", "A genuine and formal collective message."),
    ("Our sympathy is with you", "Collectively offers compassion and support."),
    ("Peace and comfort to you", "A concise wish for consolation and calm."),
    ("Peace to you as you mourn", "Offers calm and comfort during mourning."),
    ("Please accept my sympathy", "A formal expression of personal sympathy."),
    ("Please know how sorry I am", "Emphasizes genuine personal sorrow."),
    ("Prayers and sympathy to you", "Combines spiritual support with compassion."),
    ("Praying for peace and strength", "Seeks spiritual calm and resilience."),
    ("Praying for you and your family", "Offers prayer for the entire grieving family."),
    ("Praying for your comfort", "Seeks spiritual consolation for the bereaved."),
    ("Profound sympathy for your loss", "Expresses exceptionally deep compassion."),
    ("Rest in peace", "A traditional farewell to the deceased."),
    ("Sending comfort and strength", "Wishes emotional support during bereavement."),
    ("Sending heartfelt condolences", "Offers warm and genuine condolences."),
    ("Sending love and sympathy", "Combines affection with compassionate support."),
    ("Sending my deepest sympathy", "Sends a strong message of compassion."),
    ("Sharing in your grief", "Expresses solidarity in the grieving process."),
    ("Sharing your sadness", "Expresses participation in the person’s sorrow."),
    ("Sincere condolences to you", "Directly offers genuine condolences."),
    ("So sorry for this painful loss", "Recognizes both the death and resulting pain."),
    ("Strength and peace to you", "Wishes resilience and calm during bereavement."),
    ("There are no words", "Acknowledges that the loss defies expression."),
    ("Thinking of you at this time", "Gently expresses care during mourning."),
    ("This is such heartbreaking news", "Responds with sorrow to news of death."),
    ("This loss saddens us all", "Shows that the sorrow is widely shared."),
    ("This news breaks my heart", "Shows intense sorrow upon hearing the news."),
    ("We grieve alongside you", "Offers collective companionship in grief."),
    ("We keep you in our prayers", "Promises continued collective prayer."),
    ("We mourn your loss", "Collectively expresses sorrow over the death."),
    ("We send love and comfort", "Collectively offers affection and consolation."),
    ("We send our deepest sympathy", "Collectively sends profound compassion."),
    ("We stand with you in grief", "Expresses solidarity throughout mourning."),
    ("We’re deeply sorry for your loss", "Collectively expresses profound sorrow."),
    ("We’re heartbroken for you", "Collectively expresses intense sorrow and compassion."),
    ("We’re holding you in our hearts", "Offers tender collective emotional support."),
    ("We’re saddened by your loss", "Collectively acknowledges sadness over the death."),
    ("We’re so sorry for your loss", "Collectively expresses sorrow about the death."),
    ("We’re thinking of you", "Collectively expresses caring attention."),
    ("Wishing you comfort and peace", "Offers consolation and calm during grief."),
    ("Wishing you healing and comfort", "Hopes grief gradually becomes more bearable."),
    ("Wishing you peace and strength", "Offers calm and resilience after loss."),
    ("With deepest sympathy", "A concise, formal condolence message."),
    ("With heartfelt sympathy", "A brief message of sincere compassion."),
    ("With sincere sympathy", "A restrained, genuine expression of sympathy."),
    ("You have my deepest sympathy", "Directly offers profound personal sympathy."),
    ("You remain in our prayers", "Promises ongoing collective spiritual remembrance."),
    ("Your sorrow touches my heart", "Expresses personal compassion for another’s grief."),
]

CONDOLENCE_GROUPS = [
    (
        "Personal sympathy (I / My)",
        [
            (3, "Accept my sincere sympathy", "Formally offers genuine personal compassion."),
            (4, "All my love in your sorrow", "Offers wholehearted affection during sadness."),
            (5, "All my sympathy is with you", "Offers complete compassion and emotional support."),
            (6, "Awfully sorry about your loss", "Expresses sincere sorrow in everyday language."),
            (8, "Beside you in sorrow", "Offers companionship during deep sadness."),
            (15, "Expressing sorrow for your loss", "Directly communicates sadness and sympathy."),
            (19, "Grieving with you", "Expresses companionship in grief."),
            (20, "Heartfelt condolences to you", "Directly offers warm and sincere condolences."),
            (21, "I can’t imagine your pain", "Recognizes the likely depth of suffering."),
            (22, "I grieve with you", "Joins the bereaved in their grief."),
            (23, "I mourn with you", "Expresses shared mourning after a death."),
            (24, "I share in your sorrow", "Acknowledges and participates in their sadness."),
            (25, "I share your grief", "Expresses solidarity with someone who is grieving."),
            (29, "I’m deeply saddened", "Expresses profound sadness about the death."),
            (30, "I’m heartbroken for you", "Expresses intense compassion and sadness."),
            (31, "I’m saddened by your loss", "Shares sadness over the person’s death."),
            (32, "I’m so sorry for your loss", "A warm, standard expression of sympathy."),
            (45, "My heart aches for you", "Expresses heartfelt pain for the bereaved."),
            (46, "My heart goes out to you", "Conveys deep compassion for someone’s suffering."),
            (47, "My thoughts are with you", "Expresses attentive care and emotional support."),
            (59, "Please know how sorry I am", "Emphasizes genuine personal sorrow."),
            (68, "Sending love and sympathy", "Combines affection with compassionate support."),
            (69, "Sending my deepest sympathy", "Sends a strong message of compassion."),
            (70, "Sharing in your grief", "Expresses solidarity in the grieving process."),
            (71, "Sharing your sadness", "Expresses participation in the person’s sorrow."),
            (98, "You have my deepest sympathy", "Directly offers profound personal sympathy."),
            (100, "Your sorrow touches my heart", "Expresses personal compassion for another’s grief."),
        ],
    ),
    (
        "Collective (We / Our / Us)",
        [
            (1, "A loss felt by us all", "Acknowledges that others share the sorrow."),
            (48, "Our deepest sympathies", "A concise collective expression of profound sympathy."),
            (49, "Our heartfelt condolences", "A warm collective condolence message."),
            (50, "Our hearts are with you", "Collectively expresses emotional closeness and support."),
            (51, "Our hearts go out to you", "Collectively conveys deep compassion."),
            (52, "Our love is with you", "Collectively offers affection during bereavement."),
            (54, "Our sincere condolences", "A genuine and formal collective message."),
            (55, "Our sympathy is with you", "Collectively offers compassion and support."),
            (78, "This loss saddens us all", "Shows that the sorrow is widely shared."),
            (80, "We grieve alongside you", "Offers collective companionship in grief."),
            (81, "We keep you in our prayers", "Promises continued collective prayer."),
            (82, "We mourn your loss", "Collectively expresses sorrow over the death."),
            (83, "We send love and comfort", "Collectively offers affection and consolation."),
            (84, "We send our deepest sympathy", "Collectively sends profound compassion."),
            (85, "We stand with you in grief", "Expresses solidarity throughout mourning."),
            (86, "We’re deeply sorry for your loss", "Collectively expresses profound sorrow."),
            (87, "We’re heartbroken for you", "Collectively expresses intense sorrow and compassion."),
            (88, "We’re holding you in our hearts", "Offers tender collective emotional support."),
            (89, "We’re saddened by your loss", "Collectively acknowledges sadness over the death."),
            (90, "We’re so sorry for your loss", "Collectively expresses sorrow about the death."),
            (91, "We’re thinking of you", "Collectively expresses caring attention."),
            (99, "You remain in our prayers", "Promises ongoing collective spiritual remembrance."),
        ],
    ),
    (
        "Religious & spiritual",
        [
            (17, "God be with you in your grief", "Invokes divine presence during mourning."),
            (18, "God bless you in this sorrow", "Invokes divine care during sadness."),
            (34, "Love and prayers are with you", "Offers affection and continuing spiritual support."),
            (37, "May God comfort you", "A religious wish for divine consolation."),
            (38, "May God grant you peace", "A religious wish for divine peace."),
            (43, "May their soul rest in peace", "A religious wish for the deceased."),
            (53, "Our prayers are with you", "Collectively offers continuing spiritual support."),
            (60, "Prayers and sympathy to you", "Combines spiritual support with compassion."),
            (61, "Praying for peace and strength", "Seeks spiritual calm and resilience."),
            (62, "Praying for you and your family", "Offers prayer for the entire grieving family."),
            (63, "Praying for your comfort", "Seeks spiritual consolation for the bereaved."),
        ],
    ),
    (
        "Formal & concise",
        [
            (2, "Accept my heartfelt condolences", "Formally offers warm, sincere condolences."),
            (7, "Be assured of my sympathy", "Formally promises heartfelt support and concern."),
            (10, "Condolences to you and yours", "Extends sympathy to the bereaved family."),
            (12, "Deepest condolences on your loss", "Offers strong and formal sympathy."),
            (13, "Deepest sympathies to you", "Directly offers profound sympathy."),
            (16, "Extending sympathy at this time", "Offers formal support during bereavement."),
            (58, "Please accept my sympathy", "A formal expression of personal sympathy."),
            (64, "Profound sympathy for your loss", "Expresses exceptionally deep compassion."),
            (67, "Sending heartfelt condolences", "Offers warm and genuine condolences."),
            (72, "Sincere condolences to you", "Directly offers genuine condolences."),
            (95, "With deepest sympathy", "A concise, formal condolence message."),
            (96, "With heartfelt sympathy", "A brief message of sincere compassion."),
            (97, "With sincere sympathy", "A restrained, genuine expression of sympathy."),
        ],
    ),
    (
        "Wishes for comfort, peace & strength",
        [
            (9, "Comfort and peace be with you", "Offers continuing consolation and tranquility."),
            (14, "Every comfort to you and yours", "Wishes solace for the entire family."),
            (28, "I wish you strength and comfort", "Offers resilience and reassurance during mourning."),
            (35, "Love and strength to you", "Offers affection and resilience during grief."),
            (36, "May comfort surround you", "Wishes abundant reassurance and support."),
            (39, "May love surround you", "Wishes loving support throughout bereavement."),
            (40, "May memories bring you comfort", "Hopes memories ease the person’s grief."),
            (41, "May peace be with you", "Offers a gentle wish for peace."),
            (42, "May their memory comfort you", "Hopes remembrance provides consolation."),
            (44, "May you find comfort", "Wishes consolation during grief."),
            (56, "Peace and comfort to you", "A concise wish for consolation and calm."),
            (57, "Peace to you as you mourn", "Offers calm and comfort during mourning."),
            (66, "Sending comfort and strength", "Wishes emotional support during bereavement."),
            (74, "Strength and peace to you", "Wishes resilience and calm during bereavement."),
            (92, "Wishing you comfort and peace", "Offers consolation and calm during grief."),
            (93, "Wishing you healing and comfort", "Hopes grief gradually becomes more bearable."),
            (94, "Wishing you peace and strength", "Offers calm and resilience after loss."),
        ],
    ),
    (
        "Hearing the news",
        [
            (11, "Deep sorrow at your loss", "Conveys profound sadness about the death."),
            (26, "I was deeply saddened to hear", "Expresses profound sadness upon learning of death."),
            (27, "I was heartbroken to hear", "Expresses intense sadness upon hearing the news."),
            (33, "I’m sorry to hear this sad news", "Responds sympathetically to news of death."),
            (73, "So sorry for this painful loss", "Recognizes both the death and resulting pain."),
            (77, "This is such heartbreaking news", "Responds with sorrow to news of death."),
            (79, "This news breaks my heart", "Shows intense sorrow upon hearing the news."),
        ],
    ),
    (
        "Brief & traditional",
        [
            (65, "Rest in peace", "A traditional farewell to the deceased."),
            (75, "There are no words", "Acknowledges that the loss defies expression."),
            (76, "Thinking of you at this time", "Gently expresses care during mourning."),
        ],
    ),
]

CONFLICT = [
    ("Can we agree on one thing?", "builds from shared points"),
    ("Can we be honest kindly?", "encourages gentle honesty"),
    ("Can we check our assumptions?", "questions possible misreadings"),
    ("Can we clear the air?", "invites honest resolution"),
    ("Can we find common ground?", "seeks shared agreement"),
    ("Can we focus on solutions?", "shifts toward problem-solving"),
    ("Can we keep an open mind?", "encourages flexibility"),
    ("Can we lower the tension?", "asks to de-escalate"),
    ("Can we name the real issue?", "seeks the core problem"),
    ("Can we pause for a second?", "requests a brief break"),
    ("Can we reset the tone?", "asks for calmer interaction"),
    ("Can we revisit this gently?", "returns to topic calmly"),
    ("Can we slow down a bit?", "asks for a calmer pace"),
    ("Can we start over?", "offers a fresh beginning"),
    ("Can we take turns speaking?", "creates orderly discussion"),
    ("Can we talk about what happened?", "opens discussion of events"),
    ("Can we talk calmly?", "requests a calm conversation"),
    ("Can we talk this through?", "invites calm discussion"),
    ("Can we try again?", "offers another attempt"),
    ("Can we untangle this?", "offers to sort confusion"),
    ("Help me understand.", "asks for clarification calmly"),
    ("I can meet you halfway.", "offers compromise"),
    ("I can see your point.", "recognizes their reasoning"),
    ("I care about our relationship.", "prioritizes the connection"),
    ("I don’t want this to escalate.", "aims to prevent worsening"),
    ("I don’t want to make this worse.", "aims to prevent harm"),
    ("I get why that bothered you.", "shows understanding of impact"),
    ("I hear that you’re hurt.", "acknowledges emotional pain"),
    ("I hear what you’re saying.", "acknowledges their point"),
    ("I hear your concern.", "acknowledges the issue raised"),
    ("I hear your side.", "acknowledges their account"),
    ("I know I played a role.", "accepts partial responsibility"),
    ("I know this is hard.", "acknowledges difficulty"),
    ("I know this matters to you.", "acknowledges importance to them"),
    ("I may have misunderstood.", "admits possible misreading"),
    ("I regret how I said that.", "apologizes for delivery"),
    ("I respect that this matters.", "shows regard for importance"),
    ("I respect your feelings.", "shows regard for emotions"),
    ("I see the impact now.", "recognizes consequences"),
    ("I see where you’re coming from.", "recognizes their background reasoning"),
    ("I see why that felt unfair.", "validates unfairness felt"),
    ("I see why you’re upset.", "validates their feelings"),
    ("I understand why you’re angry.", "recognizes their anger"),
    ("I understand you’re frustrated.", "recognizes their frustration"),
    ("I understand your concern.", "shows comprehension of worry"),
    ("I value your perspective.", "shows respect for their view"),
    ("I want to be fair.", "signals balanced intent"),
    ("I want to be part of the fix.", "offers help in repair"),
    ("I want to fix this.", "shows commitment to repair"),
    ("I want to hear you out.", "invites them to speak"),
    ("I want to make this right.", "shows repair intent"),
    ("I want to move forward.", "focuses on progress"),
    ("I want to resolve this well.", "shows care for the process"),
    ("I want to respond better.", "commits to improvement"),
    ("I want to understand better.", "shows desire for clarity"),
    ("I want to understand your view.", "shows openness to their perspective"),
    ("I want us both heard.", "supports mutual voice"),
    ("I want us on the same page.", "seeks shared understanding"),
    ("I was wrong about that.", "admits being mistaken"),
    ("I’m sorry for my part.", "accepts responsibility"),
    ("I’m willing to listen.", "offers attention and openness"),
    ("Let’s address this directly.", "encourages straightforward discussion"),
    ("Let’s avoid personal attacks.", "sets respectful limits"),
    ("Let’s be clear about this.", "seeks clarity"),
    ("Let’s clear this up.", "aims to remove confusion"),
    ("Let’s figure this out.", "invites joint problem-solving"),
    ("Let’s find a solution together.", "suggests teamwork on the problem"),
    ("Let’s find a way forward.", "seeks next steps together"),
    ("Let’s focus on the issue.", "redirects to the problem"),
    ("Let’s keep listening.", "encourages continued attention"),
    ("Let’s keep this productive.", "maintains useful discussion"),
    ("Let’s keep this respectful.", "sets a civil tone"),
    ("Let’s look for a compromise.", "seeks middle ground"),
    ("Let’s make this constructive.", "pushes toward helpful dialogue"),
    ("Let’s not assume the worst.", "discourages negative assumptions"),
    ("Let’s not talk over each other.", "sets speaking boundaries"),
    ("Let’s solve the problem.", "centers on resolution"),
    ("Let’s stick to the facts.", "keeps discussion grounded"),
    ("Let’s take a step back.", "slows the conflict down"),
    ("Let’s try a different approach.", "suggests a new method"),
    ("Let’s work this out.", "focuses on resolving it"),
    ("What am I missing?", "invites correction or context"),
    ("What are we both wanting?", "identifies shared needs"),
    ("What are you hoping for?", "asks about desired outcome"),
    ("What can I do differently?", "asks how to improve"),
    ("What can we agree on?", "looks for shared points"),
    ("What can we learn from this?", "seeks growth from conflict"),
    ("What did you hear me say?", "checks understanding"),
    ("What do you need from me?", "asks how to help"),
    ("What do you need right now?", "asks about immediate needs"),
    ("What feels unresolved?", "asks what remains unsettled"),
    ("What matters most here?", "focuses on priorities"),
    ("What needs to change?", "asks for necessary changes"),
    ("What outcome feels fair?", "asks about fairness"),
    ("What would a good outcome be?", "asks for desired resolution"),
    ("What would feel respectful?", "asks about respectful treatment"),
    ("What would help here?", "asks for a useful next step"),
    ("What would help you feel heard?", "asks how to validate them"),
    ("What would make this better?", "asks for improvement ideas"),
    ("What would you like instead?", "asks for an alternative"),
]

FRAGMENTS = [
    ("A little too late.", "Phrase lacking sentence structure."),
    ("A very strange idea.", "Noun phrase as fragment."),
    ("Across the room.", "Prepositional phrase standing alone."),
    ("After all that.", "Phrase missing complete thought."),
    ("After the movie ended.", "Time clause lacking main idea."),
    ("Although she tried hard.", "Incomplete thought needing completion."),
    ("As a result of the storm.", "Prepositional phrase fragment."),
    ("As if nothing happened.", "Clause fragment."),
    ("As soon as possible.", "Phrase lacking subject and verb."),
    ("At the very least.", "Prepositional phrase standing alone."),
    ("Because I was late.", "Dependent clause standing alone."),
    ("Before we left.", "Introductory clause without sentence."),
    ("Beyond repair.", "Adjective phrase fragment."),
    ("By the end of the day.", "Prepositional phrase fragment."),
    ("During the meeting.", "Time phrase as fragment."),
    ("Especially on weekends.", "Adverbial phrase fragment."),
    ("Even though it hurt.", "Subordinate clause used alone."),
    ("Far from perfect.", "Adjective phrase fragment."),
    ("For example.", "Transition fragment, not sentence."),
    ("For no apparent reason.", "Prepositional phrase fragment."),
    ("Hoping for better weather.", "Participial fragment."),
    ("I need it as soon as possible.", "Turn phrase into sentence."),
    ("If necessary.", "Conditional phrase fragment."),
    ("If only for a moment.", "Phrase fragment."),
    ("If you need help.", "Conditional clause used alone."),
    ("In no time.", "Prepositional phrase fragment."),
    ("In the middle of nowhere.", "Prepositional phrase standing alone."),
    ("Incredibly frustrating.", "Adjective phrase without subject."),
    ("It is such a pity.", "Add subject and linking verb."),
    ("It was a very strange idea.", "Add subject and verb."),
    ("It was probably not enough.", "Expand into complete sentence."),
    ("Just around the corner.", "Phrase lacking finite verb."),
    ("Just my luck.", "Elliptical fragment."),
    ("Keeping to myself.", "Fragment with participle phrase."),
    ("Knowing the risks.", "Fragment with participle phrase."),
    ("Left without warning.", "Fragment missing a subject."),
    ("Like a dream.", "Comparison phrase used alone."),
    ("Like it never happened.", "Fragment with dependent phrase."),
    ("Looking for answers.", "Fragment with participle phrase."),
    ("Made of solid oak.", "Fragment missing a subject."),
    ("More than enough.", "Comparative phrase used alone."),
    ("More trouble than expected.", "Fragment lacking a verb."),
    ("Much too expensive.", "Fragment lacking a verb."),
    ("Near the station.", "Location phrase lacking clause."),
    ("Neither here nor there.", "Fragment used as a phrase."),
    ("No problem.", "Minor sentence fragment."),
    ("No way.", "Informal fragment, not full sentence."),
    ("Not a chance.", "Elliptical fragment."),
    ("Not for long.", "Fragment lacking a verb."),
    ("Not until tomorrow.", "Time phrase fragment."),
    ("Nowhere to hide.", "Fragment with infinitive phrase."),
    ("Of all the nerve.", "Exclamatory fragment."),
    ("On the other hand.", "Transitional fragment phrase."),
    ("Once the guests arrived.", "Dependent clause lacking main clause."),
    ("Only if you insist.", "Dependent-clause fragment."),
    ("Out of sight.", "Prepositional phrase fragment."),
    ("Over my dead body.", "Exclamatory fragment."),
    ("Over the horizon.", "Prepositional phrase fragment."),
    ("Over the weekend.", "Prepositional phrase fragment."),
    ("Owing to bad weather.", "Prepositional phrase fragment."),
    ("Probably not.", "Minor fragment missing full structure."),
    ("Quite a surprise.", "Noun phrase fragment."),
    ("Rather than complain.", "Subordinator phrase fragment."),
    ("Ready for anything.", "Adjective phrase without subject."),
    ("Running down the street.", "Participial phrase used alone."),
    ("She looked across the room.", "Add subject and verb."),
    ("She was ready for anything.", "Complete adjective phrase."),
    ("She was running down the street.", "Add subject and helping verb."),
    ("Since he apologized.", "Subordinate clause missing result."),
    ("So much noise.", "Noun phrase fragment."),
    ("Still not enough.", "Phrase lacking full clause."),
    ("Such a pity.", "Noun phrase fragment."),
    ("That he never called.", "Noun clause standing alone."),
    ("The best option.", "Noun phrase lacking predicate."),
    ("The man by the window.", "Noun phrase fragment."),
    ("The one in blue.", "Noun phrase fragment."),
    ("The reason for the delay.", "Noun phrase fragment."),
    ("Though not impossible.", "Clause fragment."),
    ("To be perfectly honest.", "Introductory infinitive fragment."),
    ("To get there on time.", "Infinitive phrase used alone."),
    ("To make matters worse.", "Introductory infinitive fragment."),
    ("Too little, too late.", "Phrase fragment."),
    ("Under heavy pressure.", "Prepositional phrase fragment."),
    ("Under the old bridge.", "Prepositional phrase fragment."),
    ("Unless you object.", "Incomplete conditional statement."),
    ("Until further notice.", "Prepositional phrase fragment."),
    ("What a mess.", "Exclamatory fragment without verb."),
    ("What a relief.", "Exclamatory fragment."),
    ("What he meant.", "Noun clause fragment."),
    ("When the rain stopped.", "Subordinate clause without main clause."),
    ("Whenever you’re ready.", "Dependent clause used alone."),
    ("Where the road ends.", "Clause fragment lacking main clause."),
    ("Whether we agree or not.", "Clause fragment missing completion."),
    ("Which was surprising.", "Relative clause as fragment."),
    ("While the baby slept.", "Dependent clause as fragment."),
    ("Who could blame her.", "Question fragment without completion."),
    ("Who wanted more coffee.", "Relative clause lacking main clause."),
    ("Whoever said that.", "Clause fragment lacking predicate."),
    ("Without a second thought.", "Prepositional phrase fragment."),
    ("Without any warning.", "Prepositional phrase fragment."),
]

SILENCES = [
    ("A funny thing happened today", "Share a light, quick story."),
    ("All good?", "Quick check-in."),
    ("Any big plans this weekend?", "Invite casual future talk."),
    ("Any hobbies you’re into lately?", "Ask about interests."),
    ("Any new shows you recommend?", "Ask for TV suggestions."),
    ("Any podcasts you like?", "Ask for podcast picks."),
    ("Any projects you’re excited about?", "Invite work or life updates."),
    ("Anything else on your mind?", "Invite additional thoughts."),
    ("Anything new with you?", "Open the floor gently."),
    ("Anything you’re looking forward to?", "Prompt positive anticipation."),
    ("As for me, I’ve been busy", "Offer a simple update."),
    ("By the way, how’s your week?", "Shift to an easy topic."),
    ("Can I ask you something?", "Signal a new question."),
    ("Can we circle back?", "Return to a topic."),
    ("Can you recommend a good book?", "Ask for reading ideas."),
    ("Could you say more?", "Ask for elaboration."),
    ("Did I explain that clearly?", "Confirm understanding."),
    ("Did you catch the game?", "Try a common shared topic."),
    ("Did you grow up around here?", "Ask about background."),
    ("Do you have any pets?", "Invite a warm subject."),
    ("Do you have siblings?", "Ask about family."),
    ("Do you like to cook?", "Start food conversation."),
    ("Do you want to change topics?", "Offer an easy out."),
    ("Do you work nearby?", "Ask about location and routine."),
    ("Does that make sense?", "Check in and re-engage."),
    ("Ever been to this place before?", "Ask about familiarity."),
    ("Ever tried a new hobby lately?", "Prompt recent changes."),
    ("Everything going okay today?", "Show care and invite sharing."),
    ("Feel free to take your time", "Reduce pressure to speak."),
    ("Funny weather we’re having", "Use a neutral opener."),
    ("How did you get into that?", "Ask for origin story."),
    ("How do you feel about it?", "Invite feelings and views."),
    ("How do you know them?", "Clarify connections."),
    ("How have things been lately?", "Invite a broader update."),
    ("How’s it going on your end?", "Check in casually."),
    ("How’s work been for you?", "Invite professional updates."),
    ("How’s your day treating you?", "Simple check-in question."),
    ("How’s your family doing?", "Ask about loved ones."),
    ("How’s your schedule lately?", "Ask about busyness."),
    ("How’s your week been?", "Easy, low-stakes question."),
    ("I could use your advice", "Invite them to contribute."),
    ("I just remembered something", "Introduce a new thread."),
    ("I love hearing your take", "Encourage their opinion."),
    ("I noticed you mentioned that", "Return to earlier point."),
    ("I’m curious what you think", "Ask for their perspective."),
    ("I’m happy to listen", "Encourage them to speak."),
    ("I’m not sure what to say", "Name the moment honestly."),
    ("I’ve been meaning to ask you", "Open a prepared question."),
    ("Is it always this busy?", "Comment on the setting."),
    ("Is now a good time?", "Check readiness to talk."),
    ("Is there anything I can do?", "Offer help and engagement."),
    ("Is there anything new?", "Invite updates."),
    ("It’s been a long day", "Share a relatable feeling."),
    ("Let me think for a second", "Buy time naturally."),
    ("Let’s switch gears", "Change topic smoothly."),
    ("Mind if I ask a question?", "Polite lead-in to talk."),
    ("Mind if we take a pause?", "Normalize a brief silence."),
    ("Need a moment?", "Offer space."),
    ("Nice to finally meet you", "Reset the interaction warmly."),
    ("Not much to add on my end", "Acknowledge pause without tension."),
    ("On a different note", "Transition to a new topic."),
    ("So, how do you spend your time?", "Ask about daily life."),
    ("So, what brings you here?", "Ask about purpose or context."),
    ("So, what do you do?", "Ask about their work."),
    ("So, what’s been keeping you busy?", "Invite recent activities."),
    ("So, what’s new?", "Open-ended restart."),
    ("Sorry, I got quiet there", "Address silence politely."),
    ("Tell me more about that", "Invite elaboration."),
    ("That reminds me of something", "Bridge to a related story."),
    ("That’s a good question", "Acknowledge and gather thoughts."),
    ("That’s fair", "Validate without adding pressure."),
    ("That’s interesting—why?", "Prompt deeper explanation."),
    ("The last thing I watched was", "Offer a conversation hook."),
    ("This is a nice spot", "Comment on surroundings."),
    ("We can talk about something else", "Offer a gentle redirect."),
    ("What are you into these days?", "Ask about current interests."),
    ("What do you do for fun?", "Invite personal interests."),
    ("What do you like to do weekends?", "Ask about routines."),
    ("What got you interested in that?", "Ask for motivation."),
    ("What have you been up to?", "General update prompt."),
    ("What kind of music do you like?", "Start a music topic."),
    ("What’s been challenging lately?", "Invite honest sharing."),
    ("What’s been on your mind?", "Invite deeper sharing."),
    ("What’s one thing you’ve learned recently?", "Prompt reflection."),
    ("What’s something you enjoy?", "Invite preferences."),
    ("What’s something you’re proud of?", "Prompt positive reflection."),
    ("What’s the best part of your day?", "Invite a highlight."),
    ("What’s the latest with you?", "Ask for recent news."),
    ("What’s your favorite food?", "Easy, friendly question."),
    ("What’s your favorite place nearby?", "Ask for local recommendations."),
    ("What’s your favorite way to relax?", "Invite self-care talk."),
    ("What’s your go-to comfort show?", "Invite light preferences."),
    ("What’s your take on this?", "Ask for their opinion."),
    ("What’s your usual routine?", "Prompt everyday talk."),
    ("Where are you from originally?", "Ask about hometown."),
    ("Where do you like to travel?", "Invite travel talk."),
    ("Where would you go for a day trip?", "Prompt easy travel ideas."),
    ("Who’s someone you admire?", "Prompt values and stories."),
    ("Would you like some water?", "Offer a small kindness."),
    ("Would you like to hear a story?", "Offer a light anecdote."),
]

INSTRUCTIONS = [
    ("After completing that,", "Introduces the next action"),
    ("After that,", "Continues with another step"),
    ("Afterward,", "Signals a later step"),
    ("Ahead of time,", "Suggests doing something earlier"),
    ("As a first step,", "Introduces the opening action"),
    ("At the outset,", "Introduces the beginning"),
    ("At this point,", "Marks the current stage"),
    ("At this stage,", "Marks the current point"),
    ("Be careful to", "Calls for caution"),
    ("Be certain to", "Emphasizes certainty"),
    ("Be sure not to", "Warns against an action"),
    ("Be sure to", "Stresses an important action"),
    ("Before anything else,", "Sets the very first task"),
    ("Before you begin,", "Introduces preparation"),
    ("Before you start,", "Gives a pre-step instruction"),
    ("Begin by", "Introduces the opening action"),
    ("Check", "Tells to verify something"),
    ("Choose", "Tells to pick one"),
    ("Click", "Tells to select digitally"),
    ("Close", "Tells to shut something"),
    ("Compare", "Tells to note differences"),
    ("Connect", "Tells to join things"),
    ("Continue by", "Gives the next action"),
    ("Count", "Tells to total items"),
    ("Do not", "Gives a direct prohibition"),
    ("Do the following:", "Introduces listed actions"),
    ("Don’t forget to", "Warns against omission"),
    ("Enter", "Tells to type or go in"),
    ("Examine", "Tells to inspect carefully"),
    ("Finally,", "Introduces the last step"),
    ("Follow these steps:", "Introduces instructions"),
    ("Follow this procedure:", "Introduces a process"),
    ("Following that,", "Introduces the next stage"),
    ("For best results,", "Introduces advice for success"),
    ("For starters,", "Begins with an opening step"),
    ("From there,", "Continues from the prior step"),
    ("Go ahead and", "Encourages the next action"),
    ("Go on to", "Directs the next step"),
    ("Here’s what to do:", "Introduces instructions clearly"),
    ("If needed,", "Adds an optional step"),
    ("In advance,", "Calls for preparation"),
    ("In order to do that,", "Introduces required action"),
    ("In the next step,", "Introduces the following stage"),
    ("Initially,", "Marks the starting point"),
    ("Insert", "Tells to put inside"),
    ("Inspect", "Tells to check closely"),
    ("It’s important to", "Highlights importance"),
    ("Leave out", "Tells to omit something"),
    ("Look over", "Tells to inspect briefly"),
    ("Make sure to", "Emphasizes a needed action"),
    ("Measure", "Tells to find size"),
    ("Moving on,", "Transitions to the next part"),
    ("Never", "Forbids an action"),
    ("Next,", "Moves to the following step"),
    ("Now,", "Shifts to the next instruction"),
    ("Once finished,", "Moves on after finishing"),
    ("Once that’s done,", "Moves on after completion"),
    ("Once you begin,", "Starts the process"),
    ("Open", "Tells to access or uncover"),
    ("Optionally,", "Marks an optional step"),
    ("Pause", "Tells to stop briefly"),
    ("Place", "Directs where to put"),
    ("Press", "Tells to push something"),
    ("Prior to starting,", "Sets up an earlier action"),
    ("Proceed by", "Tells how to continue"),
    ("Read", "Tells to look at text"),
    ("Refrain from", "Tells someone not to act"),
    ("Remember to", "Reminds the listener"),
    ("Remove", "Tells to take away"),
    ("Review", "Tells to examine again"),
    ("Select", "Tells to choose an option"),
    ("Skip", "Tells to leave out"),
    ("Start by", "Tells what to do first"),
    ("Step one:", "Labels the first step"),
    ("Stop", "Tells to cease action"),
    ("Subsequently,", "Introduces a later action"),
    ("Switch off", "Tells to cut power"),
    ("Switch on", "Tells to activate power"),
    ("Take care to", "Urges careful action"),
    ("The first step is to", "Names the initial action"),
    ("The following step is to", "Names the next action"),
    ("The next step is to", "Introduces the following action"),
    ("Then,", "Adds the next action"),
    ("Thereafter,", "Signals what comes later"),
    ("To begin with,", "Introduces the first instruction"),
    ("To continue,", "Introduces the next part"),
    ("To prepare,", "Signals preparation"),
    ("To start,", "Introduces the first step"),
    ("Under no circumstances", "Strongly forbids something"),
    ("Use the following steps:", "Introduces a method"),
    ("Wait", "Tells to pause"),
    ("When necessary,", "Adds a condition"),
    ("When that’s done,", "Moves to the next step"),
    ("Where appropriate,", "Adds situational guidance"),
    ("Write", "Tells to record words"),
    ("You have to", "Expresses obligation"),
    ("You must", "Gives a strong instruction"),
    ("You need to", "States necessity"),
    ("You should", "Gives advice or direction"),
    ("You’ll need to", "States a requirement"),
]

ENDCONVO = [
    ("All right then...", "Signals the end politely."),
    ("Anyway, I should go.", "Signals the conversation is ending."),
    ("At any rate, I should go.", "Polite transition to ending."),
    ("For now, I’ll leave it there.", "Stops here temporarily."),
    ("For now, let’s leave it there.", "Suggests stopping for now."),
    ("I have to be off.", "Need to leave now."),
    ("I have to bounce.", "Casual way to leave."),
    ("I have to dash.", "Need to leave quickly."),
    ("I have to get going.", "Need to leave now."),
    ("I have to go now.", "Directly ends the conversation."),
    ("I have to head out.", "Need to leave now."),
    ("I have to hop off.", "Need to leave the call."),
    ("I have to leave it there.", "Need to stop here."),
    ("I have to run.", "Need to leave now."),
    ("I have to split.", "Need to leave now."),
    ("I must be going.", "Polite, slightly formal exit."),
    ("I must go now.", "Directly ends the conversation."),
    ("I need to be going.", "Signals departure politely."),
    ("I need to get back to work.", "Ending to resume work."),
    ("I need to get moving.", "Need to leave and continue."),
    ("I need to go now.", "Directly ends the conversation."),
    ("I need to head out.", "Need to leave the conversation."),
    ("I need to jump off.", "Need to leave the call."),
    ("I need to let you go.", "Ending a phone conversation politely."),
    ("I need to sign off.", "Ending an online conversation."),
    ("I need to take off.", "Need to leave quickly."),
    ("I ought to go.", "Polite way to leave."),
    ("I should be going.", "Signals departure politely."),
    ("I should be on my way.", "Polite leave-taking phrase."),
    ("I should get going.", "Time to leave politely."),
    ("I should go now.", "Soft direct ending."),
    ("I should head off.", "Time for me to leave."),
    ("I should let you go.", "Polite way to end the talk."),
    ("I should probably go.", "Softens the decision to leave."),
    ("I think I’ll call it a day.", "Ending for the day."),
    ("I think that’s enough for now.", "Ends for the moment."),
    ("I think we’ll leave it there.", "Suggests ending the discussion."),
    ("I won’t keep you.", "Shows respect for their time."),
    ("I’d better get going.", "Time for me to leave."),
    ("I’ll catch you later.", "Friendly way to end."),
    ("I’ll leave it there.", "Stops the discussion here."),
    ("I’ll leave you to it.", "Stops talking so they continue."),
    ("I’ll let you get back to it.", "Ending so they can continue."),
    ("I’ll talk to you later.", "Ends now, promises later talk."),
    ("I’m going to call it a day.", "Ending for the day."),
    ("I’m going to call it a night.", "Ending for the night."),
    ("I’m going to get going.", "Time for me to leave."),
    ("I’m going to hop off.", "Leaving the call now."),
    ("I’m going to leave you to it.", "Ending so they continue."),
    ("I’m going to let you go.", "Polite phone-call ending."),
    ("I’m going to sign off.", "Ending an online exchange."),
    ("I’m going to take off.", "Need to leave now."),
    ("I’ve got to go.", "Need to leave now."),
    ("Let’s leave it there.", "Suggests ending at this point."),
    ("Let’s pick this up later.", "Ends now, resumes later."),
    ("Let’s talk later.", "Ends now, suggests another time."),
    ("Right then...", "Signals wrapping up."),
    ("So, catch you later.", "Casual friendly closing."),
    ("So, I have to run.", "Signals immediate departure."),
    ("So, I must be going.", "Polite, slightly formal exit."),
    ("So, I need to head out.", "Signals leaving now."),
    ("So, I need to sign off.", "Ends an online conversation."),
    ("So, I should be off.", "Polite leave-taking signal."),
    ("So, I should let you go.", "Polite move toward ending."),
    ("So, I won’t keep you.", "Shows respect for their time."),
    ("So, I’d better get going.", "Polite signal to leave."),
    ("So, I’d better go.", "Softens the need to leave."),
    ("So, I’ll leave you to it.", "Ends while excusing yourself."),
    ("So, I’ll talk to you later.", "Ends now, promises later talk."),
    ("So, I’m going to head out.", "Signals leaving now."),
    ("So, I’m going to hop off.", "Leaving the call now."),
    ("So, I’m going to wrap up.", "Signals the end now."),
    ("So, let’s talk later.", "Ends now, suggests later."),
    ("So, talk soon.", "Friendly brief closing."),
    ("So, we’ll leave it there.", "Ends the discussion here."),
    ("Take care.", "Warm, common closing."),
    ("Talk to you soon.", "Warm closing for later contact."),
    ("That does it for now.", "Ends for the moment."),
    ("That said, I should go.", "Moves from point to exit."),
    ("That should do it.", "Signals completion and ending."),
    ("That’ll do for now.", "Enough for the moment."),
    ("Time for me to go.", "Direct statement of departure."),
    ("Time to get going.", "Signals it’s time to leave."),
    ("Time to head out.", "Signals it’s time to leave."),
    ("Time to wrap up.", "Signals the end now."),
    ("Until later.", "Goodbye for now."),
    ("Until next time.", "Brief closing until later."),
    ("Very well, I should go.", "I ought to leave now."),
    ("Very well, I’ll stop there.", "I will end here."),
    ("We can pick this up later.", "Ends now, resumes later."),
    ("We’ll have to leave it there.", "Need to stop here."),
    ("Well, I should leave you to it.", "I should let you continue."),
    ("Well, I won’t keep you.", "I will not delay you."),
    ("Well, I’d better be off.", "I should leave now."),
    ("Well, I’ll leave you to it.", "I will let you continue."),
    ("Well, I’ll let you be.", "I will stop bothering you."),
    ("Well, let’s leave it at that.", "Let’s end the discussion there."),
    ("Well, that’s enough for now.", "That is enough for now."),
    ("Well, that’s it for now.", "That is all for now."),
    ("You take care now.", "Friendly goodbye and well-wish."),
]

SECTIONS = [
    (
        53,
        "condolences",
        "100 Best Ways to Say &ldquo;My condolences&rdquo;",
        "Sympathy phrases grouped by tone; numbered 1–100 as on your sheet.",
        "grouped",
        CONDOLENCE_GROUPS,
    ),
    (
        54,
        "conflict",
        "100 Sentence Starters for Resolving Conflict",
        "De-escalation and repair phrases, numbered 1–100.",
        CONFLICT,
    ),
    (
        55,
        "fragments",
        "100 Examples of Sentence Fragments and Fixes",
        "Common fragments with grammar notes, numbered 1–100.",
        FRAGMENTS,
    ),
    (
        56,
        "silences",
        "100 Phrases for Handling Awkward Silences",
        "Conversation restart lines, numbered 1–100.",
        SILENCES,
    ),
    (
        57,
        "instructions",
        "100 Sentence Starters for Giving Instructions",
        "Step-by-step directive openers, numbered 1–100.",
        INSTRUCTIONS,
    ),
    (
        58,
        "endconvo",
        "100 Sentence Starters for Ending Conversations",
        "Polite exit phrases, numbered 1–100.",
        ENDCONVO,
    ),
]
