#!/usr/bin/env python3
"""Generate HTML sections 8-19 for Writing-Word-Banks.html."""

def section(num, sid, title, note, items):
    lines = [
        f'      <section id="{sid}">',
        f'        <h2>{num}. {title}</h2>',
        f'        <p class="note">{note}</p>',
        '        <div class="entry filterable">',
        '          <ul class="def-list">',
    ]
    for n, term, meaning in items:
        term_esc = term.replace("&", "&amp;").replace("<", "&lt;")
        meaning_esc = meaning.replace("&", "&amp;").replace("<", "&lt;")
        lines.append(f'            <li><strong>{n}. {term_esc}</strong> \u2013 {meaning_esc}</li>')
    lines += [
        '          </ul>',
        '        </div>',
        '      </section>',
        '',
    ]
    return "\n".join(lines)


suddenly = [
    (1, "abrupt", "sudden and unexpected"),
    (2, "abruptly", "in a sudden, unexpected way"),
    (3, "all at once", "happening at the same time"),
    (4, "all in a moment", "very quickly"),
    (5, "all in one go", "all at once"),
    (6, "all of a piece", "all at once"),
    (7, "all of a sudden", "suddenly; without warning"),
    (8, "all together", "all at once"),
    (9, "at a bound", "suddenly; in one leap"),
    (10, "at a glance", "immediately; at first sight"),
    (11, "at a jump", "suddenly; in one leap"),
    (12, "at a stroke", "all at once"),
    (13, "at first blush", "at first sight; immediately"),
    (14, "at first sight", "immediately upon seeing"),
    (15, "at once", "immediately; right then"),
    (16, "at the outset", "at the beginning; right away"),
    (17, "at the start", "from the beginning"),
    (18, "bang", "suddenly; with a jolt"),
    (19, "before I knew it", "so quickly it surprised me"),
    (20, "before you know it", "sooner than expected"),
    (21, "forthwith", "immediately; without delay"),
    (22, "from the get-go", "from the very start"),
    (23, "immediate", "happening at once"),
    (24, "immediately", "at once; without waiting"),
    (25, "in a burst", "suddenly and briefly"),
    (26, "in a flash", "very quickly and unexpectedly"),
    (27, "in a flurry", "suddenly with much activity"),
    (28, "in a frenzy", "suddenly with wild activity"),
    (29, "in a heartbeat", "almost immediately"),
    (30, "in a hurry", "with urgency"),
    (31, "in a jiffy", "in a very short time"),
    (32, "in a moment", "very soon; shortly"),
    (33, "in a rush", "very quickly"),
    (34, "in a second", "very quickly; almost instantly"),
    (35, "in a shock", "suddenly; startlingly"),
    (36, "in a snap", "very quickly"),
    (37, "in a split second", "in a very brief moment"),
    (38, "in a spurt", "suddenly and briefly"),
    (39, "in a trice", "very quickly"),
    (40, "in a whirl", "suddenly; in confusion"),
    (41, "in a whirlwind", "very suddenly and intensely"),
    (42, "in a wink", "in an instant"),
    (43, "in an eyeblink", "in an instant"),
    (44, "in an instant", "in a very short time"),
    (45, "in no time", "very quickly"),
    (46, "in one breath", "all at once"),
    (47, "in one fell swoop", "all at once"),
    (48, "in one instant", "in a single instant"),
    (49, "in one moment", "in a single moment"),
    (50, "in one quick motion", "in a single swift motion"),
    (51, "in one quick move", "in a single swift action"),
    (52, "in one second", "in a single second"),
    (53, "in one stroke", "all at once"),
    (54, "in one sudden motion", "in a single abrupt motion"),
    (55, "in one sudden move", "in a single abrupt action"),
    (56, "in one swift motion", "in a single swift motion"),
    (57, "in one swift move", "in a single swift action"),
    (58, "in quick succession", "one after another quickly"),
    (59, "in rapid succession", "one after another quickly"),
    (60, "in short order", "very quickly"),
    (61, "in the next breath", "immediately afterward"),
    (62, "instantaneous", "happening immediately"),
    (63, "instantly", "immediately; without delay"),
    (64, "just like that", "suddenly; without explanation"),
    (65, "like a shot", "very quickly and unexpectedly"),
    (66, "like lightning", "extremely fast, without warning"),
    (67, "off the bat", "immediately; right away"),
    (68, "on the spot", "immediately, without preparation"),
    (69, "out of nowhere", "appearing unexpectedly"),
    (70, "out of the blue", "without warning or reason"),
    (71, "posthaste", "with great speed"),
    (72, "promptly", "without delay"),
    (73, "quickly", "in a short time"),
    (74, "rapidly", "at a fast speed"),
    (75, "right away", "immediately"),
    (76, "right now", "immediately; at this moment"),
    (77, "right off", "immediately; at the start"),
    (78, "right then", "at that exact moment"),
    (79, "straightaway", "right away; without delay"),
    (80, "swiftly", "quickly; in a short time"),
    (81, "then and there", "immediately, on the spot"),
    (82, "unannounced", "without being announced"),
    (83, "unanticipated", "not expected beforehand"),
    (84, "unawares", "without being aware"),
    (85, "unexpectedly", "without being expected"),
    (86, "unforeseen", "not anticipated or expected"),
    (87, "unpredictably", "in an unexpected way"),
    (88, "with a bang", "suddenly and loudly"),
    (89, "with a click", "suddenly; instantly"),
    (90, "with a crash", "suddenly and noisily"),
    (91, "with a jerk", "suddenly; with a sharp movement"),
    (92, "with a jolt", "suddenly; with a shock"),
    (93, "with a lurch", "suddenly; with an unsteady motion"),
    (94, "with a snap", "suddenly; quickly"),
    (95, "with a start", "suddenly, with surprise"),
    (96, "with a thud", "suddenly with a dull sound"),
    (97, "without forewarning", "without advance warning"),
    (98, "without notice", "without prior warning"),
    (99, "without preamble", "without introduction or warning"),
    (100, "without warning", "with no advance notice"),
]

abnormal = [
    (1, "aberrant", "departing from what is normal"),
    (2, "alien", "strange; unfamiliar"),
    (3, "anomalous", "not normal; irregular"),
    (4, "atypical", "not typical; not usual"),
    (5, "bizarre", "very strange or unusual"),
    (6, "curious", "strange; arousing interest"),
    (7, "defective", "having a fault; flawed"),
    (8, "deficient", "lacking something needed"),
    (9, "deformed", "changed from normal form"),
    (10, "deviant", "departing from accepted norms"),
    (11, "deviating", "moving away from the usual"),
    (12, "different", "not the same; unusual"),
    (13, "disproportionate", "not in proper proportion"),
    (14, "distorted", "twisted from the normal shape"),
    (15, "dubious", "doubtful; questionable"),
    (16, "eccentric", "oddly unconventional"),
    (17, "eerie", "strange and unsettling"),
    (18, "erratic", "unpredictable; irregular"),
    (19, "exceptional", "unusual; not typical"),
    (20, "excessive", "more than is normal"),
    (21, "extraordinary", "very unusual; remarkable"),
    (22, "extreme", "far from the usual"),
    (23, "fantastic", "strangely unreal; extraordinary"),
    (24, "faulty", "not working properly; defective"),
    (25, "fishy", "seemingly wrong; suspicious"),
    (26, "flawed", "having a defect; imperfect"),
    (27, "foreign", "not familiar; strange"),
    (28, "freakish", "extremely unusual; odd"),
    (29, "ill-suited", "not suitable; inappropriate"),
    (30, "immoderate", "excessive; not within normal limits"),
    (31, "imperfect", "not perfect; flawed"),
    (32, "improper", "not correct; not appropriate"),
    (33, "inappropriate", "not suitable; not proper"),
    (34, "inapt", "not suitable or appropriate"),
    (35, "incongruous", "not fitting; out of place"),
    (36, "inconsistent", "not consistent; varying"),
    (37, "inordinate", "unusually large; excessive"),
    (38, "irregular", "not regular; not following a pattern"),
    (39, "malformed", "badly formed; misshapen"),
    (40, "misaligned", "not properly aligned"),
    (41, "misfit", "not fitting in; unsuitable"),
    (42, "misplaced", "not in the right place"),
    (43, "misshaped", "shaped wrongly; not normal"),
    (44, "misshapen", "not having a normal shape"),
    (45, "mysterious", "hard to understand or explain"),
    (46, "newfangled", "unusually new; not traditional"),
    (47, "not normal", "different from what is normal"),
    (48, "not typical", "different from what is typical"),
    (49, "novel", "new and unusual"),
    (50, "odd", "strange or unexpected"),
    (51, "off", "not quite right; unusual"),
    (52, "offbeat", "unconventional; not mainstream"),
    (53, "out of balance", "not balanced; uneven"),
    (54, "out of line", "not acceptable; improper"),
    (55, "out of place", "not fitting the situation"),
    (56, "out of step", "not in agreement; not aligned"),
    (57, "out of sync", "not synchronized; not aligned"),
    (58, "out of the norm", "not normal; atypical"),
    (59, "out of the ordinary", "not usual; uncommon"),
    (60, "out of tune", "not in harmony; off"),
    (61, "out of whack", "not working properly; off"),
    (62, "outlandish", "strangely unusual; bizarre"),
    (63, "peculiar", "unusual in a noticeable way"),
    (64, "queer", "strange; odd"),
    (65, "questionable", "doubtful; not certain"),
    (66, "quirky", "unusually distinctive; odd"),
    (67, "rare", "not common; unusual"),
    (68, "remarkable", "unusual enough to be noticed"),
    (69, "scarce", "not common; hard to find"),
    (70, "shady", "suspicious; not trustworthy"),
    (71, "shaky", "not firm; unstable"),
    (72, "singular", "unusual; distinctive"),
    (73, "sketchy", "not reliable; questionable"),
    (74, "spooky", "strange and unsettling"),
    (75, "strange", "unfamiliar or surprising"),
    (76, "substandard", "below an accepted standard"),
    (77, "surreal", "strangely dreamlike; unreal"),
    (78, "suspect", "not to be trusted; questionable"),
    (79, "unbalanced", "not stable; not in equilibrium"),
    (80, "unbecoming", "not appropriate; unseemly"),
    (81, "uncommon", "not commonly found or done"),
    (82, "unconventional", "not based on convention"),
    (83, "undue", "more than is appropriate"),
    (84, "unfitting", "not appropriate; unsuitable"),
    (85, "unorthodox", "not following traditional rules"),
    (86, "unpredictable", "not able to be predicted"),
    (87, "unreliable", "not dependable; inconsistent"),
    (88, "unseemly", "not proper; inappropriate"),
    (89, "unsound", "not healthy or reliable"),
    (90, "unstable", "not steady; likely to change"),
    (91, "unsteady", "not steady; shaky"),
    (92, "unsuitable", "not suitable; not appropriate"),
    (93, "untrustworthy", "not worthy of trust"),
    (94, "untypical", "not typical; uncharacteristic"),
    (95, "unusual", "not typical; out of the ordinary"),
    (96, "warped", "bent or twisted out of shape"),
    (97, "wayward", "not following the expected course"),
    (98, "weird", "strange; not normal"),
    (99, "wobbly", "unsteady; likely to wobble"),
    (100, "wrong", "not correct; not right"),
]

impactverbs = [
    (1, "Accelerate", "To increase the speed and scope of projects."),
    (2, "Achieve", "To successfully reach an objective through effort."),
    (3, "Administer", "To manage and direct a program or organization."),
    (4, "Advance", "To move a project or cause forward purposefully."),
    (5, "Advocate", "To publicly recommend or support a specific cause."),
    (6, "Amplify", "To increase the scale, volume, or impact."),
    (7, "Analyze", "To examine data or information in detail."),
    (8, "Architect", "To design and structure a complex system."),
    (9, "Articulate", "To express complex ideas clearly and effectively."),
    (10, "Assess", "To evaluate the nature, quality, or ability."),
    (11, "Attain", "To succeed in achieving a difficult goal."),
    (12, "Audit", "To officially inspect accounts or organizational procedures."),
    (13, "Augment", "To make something greater by adding to it."),
    (14, "Author", "To originate or create a plan or document."),
    (15, "Bolster", "To support, strengthen, or prop something up."),
    (16, "Brand", "To create a distinctive identity for a product."),
    (17, "Build", "To construct by putting parts or materials together."),
    (18, "Capitalize", "To use a situation to gain an advantage."),
    (19, "Catalyze", "To cause or accelerate a significant action."),
    (20, "Champion", "To vigorously support or defend a chosen cause."),
    (21, "Clarify", "To make a situation or statement less confused."),
    (22, "Collaborate", "To work jointly on an activity or project."),
    (23, "Command", "To have authority and control over a group."),
    (24, "Conceptualize", "To form a concept or an idea of."),
    (25, "Consolidate", "To combine things into a more effective whole."),
    (26, "Construct", "To build or erect something from scratch."),
    (27, "Consult", "To seek expert information or professional advice."),
    (28, "Coordinate", "To organize elements to work together efficiently."),
    (29, "Create", "To bring something into existence; to originate."),
    (30, "Critique", "To evaluate a theory or practice analytically."),
    (31, "Cultivate", "To develop a skill, quality, or relationship."),
    (32, "Customize", "To modify something for a particular task."),
    (33, "Delegate", "To entrust a task or responsibility to another."),
    (34, "Deliver", "To produce the promised or expected result."),
    (35, "Demonstrate", "To show the truth by providing proof."),
    (36, "Design", "To conceive and plan out in detail."),
    (37, "Develop", "To grow something to be more advanced."),
    (38, "Devise", "To plan or invent a complex procedure."),
    (39, "Diagnose", "To identify the nature of a problem."),
    (40, "Direct", "To manage or guide project or team operations."),
    (41, "Drive", "To propel and provide impetus for a project."),
    (42, "Elevate", "To raise to a more important or impressive level."),
    (43, "Empower", "To give someone authority or power to act."),
    (44, "Engineer", "To skillfully arrange for something to occur."),
    (45, "Enhance", "To intensify or further improve the quality."),
    (46, "Envision", "To imagine a future possibility; to visualize."),
    (47, "Establish", "To set up on a firm or permanent basis."),
    (48, "Evaluate", "To form an idea of the value of."),
    (49, "Exceed", "To go beyond what is prescribed; to surpass."),
    (50, "Execute", "To carry out or complete a plan."),
    (51, "Expand", "To become or make larger or more extensive."),
    (52, "Expedite", "To make a process happen more quickly."),
    (53, "Facilitate", "To make an action or process easier."),
    (54, "Forge", "To create a strong and lasting relationship."),
    (55, "Formulate", "To create a strategy or proposal methodically."),
    (56, "Foster", "To encourage the development of something desirable."),
    (57, "Galvanize", "To shock or excite someone into action."),
    (58, "Generate", "To produce or create revenue, ideas, or results."),
    (59, "Guide", "To show the way; to direct or advise."),
    (60, "Harness", "To control and make use of resources."),
    (61, "Identify", "To establish or indicate what something is."),
    (62, "Implement", "To put a decision or plan into effect."),
    (63, "Inaugurate", "To begin or introduce a new system."),
    (64, "Influence", "To affect the character or behavior of."),
    (65, "Innovate", "To introduce new methods, ideas, or products."),
    (66, "Inspire", "To fill someone with the urge to act."),
    (67, "Institute", "To establish a formal practice or system."),
    (68, "Integrate", "To combine things to become a whole."),
    (69, "Interpret", "To explain the meaning of complex information."),
    (70, "Launch", "To start or set in motion an enterprise."),
    (71, "Lead", "To bein charge or command of ateam."),
    (72, "Leverage", "To use something to its maximum advantage."),
    (73, "Manage", "To be in charge of; to handle successfully."),
    (74, "Mediate", "To intervene in a dispute to resolve it."),
    (75, "Mentor", "To advise and train a junior colleague."),
    (76, "Mobilize", "To organize people to act in concert."),
    (77, "Modernize", "To adapt something to modern needs or habits."),
    (78, "Negotiate", "To bring about a result by discussion."),
    (79, "Optimize", "To make the best or most effective use of."),
    (80, "Organize", "To arrange systematically; to coordinate actions."),
    (81, "Originate", "To create or initiate something entirely new."),
    (82, "Overhaul", "To make comprehensive repairs or improvements."),
    (83, "Persuade", "To induce someone to act through reasoning."),
    (84, "Pioneer", "To be the first to apply a method."),
    (85, "Preside", "To be in a position of authority."),
    (86, "Prioritize", "To treat something as most important."),
    (87, "Reconcile", "To make two ideas or accounts compatible."),
    (88, "Rectify", "To correct something that is wrong."),
    (89, "Redefine", "To define something again or differently."),
    (90, "Refine", "To improve something by making small changes."),
    (91, "Reinforce", "To strengthen or support with additional material."),
    (92, "Resolve", "To find a solution to a problem."),
    (93, "Restructure", "To organize a system or company differently."),
    (94, "Revolutionize", "To change something radically or fundamentally."),
    (95, "Scrutinize", "To examine or inspect closely and thoroughly."),
    (96, "Secure", "To succeed in obtaining something with difficulty."),
    (97, "Spearhead", "To lead an attack, movement, or initiative."),
    (98, "Strategize", "To devise a plan to achieve a goal."),
    (99, "Streamline", "To make a process or system more efficient."),
    (100, "Synthesize", "To combine elements into a new whole."),
]

awkward = [
    (1, "Abashed", "Embarrassed and self-conscious."),
    (2, "Abrupt", "Sudden and unexpectedly curt."),
    (3, "Accidental", "Happening by chance; unintended."),
    (4, "Affected", "Artificially posed; not genuine."),
    (5, "Agitated", "Nervous and unable to relax."),
    (6, "Aloof", "Distant; socially detached."),
    (7, "Ambivalent", "Uncertain; mixed feelings."),
    (8, "Amiss", "Not quite right; off."),
    (9, "Angular", "Sharp-comered; lacking smoothness."),
    (10, "Anomalous", "Deviating from what's normal."),
    (11, "Baffling", "Confusing; hard to understand."),
    (12, "Bizarre", "Strangely unusual or odd."),
    (13, "Blundering", "Clumsy; making careless mistakes."),
    (14, "Bumbling", "Awkwardly clumsy; inept."),
    (15, "Cagey", "Hesitant; guarded in speech."),
    (16, "Careless", "Not giving enough attention."),
    (17, "Clumsy", "Lacking coordination or grace."),
    (18, "Constrained", "Restricted; not free or natural."),
    (19, "Contrived", "Artificially arranged; forced."),
    (20, "Cringeworthy", "So embarrassing it hurts."),
    (21, "Difficult", "Hard to manage or handle."),
    (22, "Discomfiting", "Making someone uneasy."),
    (23, "Disconcerting", "Unsettling; throwing off balance."),
    (24, "Disjointed", "Lacking coherence; disconnected."),
    (25, "Disoriented", "Confused about place or situation."),
    (26, "Disquieting", "Causing worry or unease."),
    (27, "Distracted", "Unable to focus; preoccupied."),
    (28, "Dorky", "Uncool in a harmless way."),
    (29, "Doubtful", "Uncertain; not confident."),
    (30, "Dull", "Lacking interest or sharpness."),
    (31, "Eccentric", "Unconventionally strange."),
    (32, "Embarrassing", "Causing shame or self-consciousness."),
    (33, "Encumbered", "Burdened; weighed down."),
    (34, "Enduring", "Persisting longer than expected."),
    (35, "Exposed", "Left unprotected; vulnerable."),
    (36, "Faltering", "Hesitating; losing steadiness."),
    (37, "Fidgety", "Restless; unable to sit still."),
    (38, "Flustered", "Agitated and confused."),
    (39, "Forced", "Not natural; overly deliberate."),
    (40, "Fraught", "Tense; full of stress."),
    (41, "Fumbling", "Handling things clumsily."),
    (42, "Gangly", "Tall and awkwardly thin."),
    (43, "Gauche", "Socially tactless; lacking grace."),
    (44, "Gawky", "Clumsy and ungainly."),
    (45, "Giddy", "Lightheaded; unsteady or silly."),
    (46, "Goofy", "Silly in an ungainly way."),
    (47, "Grating", "Irritating; rubbing the wrong way."),
    (48, "Halting", "Stop-start; lacking flow."),
    (49, "Haphazard", "Random; lacking plan."),
    (50, "Hesitant", "Slow to act; uncertain."),
    (51, "Lll", "at-ease - Uncomfortable; not relaxed."),
    (52, "Inelegant", "Lacking grace or polish."),
    (53, "Inept", "Not skilled; incompetent."),
    (54, "Inexpert", "Not experienced; unskilled."),
    (55, "Insecure", "Not confident; uncertain."),
    (56, "Jarring", "Harshly out of place."),
    (57, "Jerky", "Not smooth; abrupt in motion."),
    (58, "Jittery", "Nervous; trembling slightly."),
    (59, "Klutzy", "Clumsy; prone to mishaps."),
    (60, "Knotty", "Complicated; hard to untangle."),
    (61, "Labored", "Done with difficulty; strained."),
    (62, "Lanky", "Long-limbed and ungainly."),
    (63, "Lopsided", "Uneven; unbalanced."),
    (64, "Lumbering", "Moving heavily and clumsily."),
    (65, "Maladroit", "Clumsy; tactless."),
    (66, "Mangled", "Badly handled; botched."),
    (67, "Misaligned", "Not properly lined up."),
    (68, "Misfiring", "Not working as intended."),
    (69, "Misguided", "Based on poor judgment."),
    (70, "Mishandled", "Handled poorly; bungled."),
    (71, "Mismatched", "Not well paired; incongruent."),
    (72, "Misplaced", "In the wrong place or time."),
    (73, "Nerve", "racking - Causing intense anxiety."),
    (74, "Nervous", "Anxious; easily unsettled."),
    (75, "Obtrusive", "Noticeably out of place."),
    (76, "Off", "balance - Unsteady; lacking stability."),
    (77, "Off", "putting - Unpleasant; discouraging."),
    (78, "Out of sync", "Not coordinated; misaligned."),
    (79, "Painful", "Hard to endure; embarrassing."),
    (80, "Perplexing", "Puzzling; confusing."),
    (81, "Plodding", "Slow and heavy in movement."),
    (82, "Poorly timed", "Happening at an unsuitable moment."),
    (83, "Puzzling", "Hard to explain or understand."),
    (84, "Questionable", "Doubtful; open to suspicion."),
    (85, "Rigid", "Stiff; lacking flexibility."),
    (86, "Rocky", "Unstable; full of difficulties."),
    (87, "Rough", "Not smooth; uneven."),
    (88, "Rude", "Impolite; socially improper."),
    (89, "Shaky", "Unsteady; lacking confidence."),
    (90, "Shambling", "Walking clumsily; shuffling."),
    (91, "Slapdash", "Hasty and careless."),
    (92, "Sloppy", "Messy; lacking neatness."),
    (93, "Stiff", "Formal; lacking ease."),
    (94, "Strained", "Tense; not relaxed."),
    (95, "Stumbling", "Tripping; proceeding unsteadily."),
    (96, "Tactless", "Insensitive; lacking social skill."),
    (97, "Tense", "Emotionally tight; uneasy."),
    (98, "Tricky", "Difficult; requiring care."),
    (99, "Unbalanced", "Not stable; uneven."),
    (100, "Uncouth", "Rude; lacking refinement."),
]

funwords = [
    (1, "akimbo", "with hands on hips and elbows turned outward."),
    (2, "anemone", "a brightly colored sea creature or flower."),
    (3, "appaloosa", "a horse with a spotted coat."),
    (4, "bamboozle", "to trick or deceive."),
    (5, "bandicoot", "a small marsupial native to Australia."),
    (6, "befuddle", "to confuse or perplex."),
    (7, "blubber", "to cry noisily and uncontrollably."),
    (8, "boondoggle", "a wasteful or impractical project."),
    (9, "brouhaha", "a noisy stir or fuss,"),
    (10, "bumbershoot", "an umbrella."),
    (11, "canoodle", "to cuddle or fondle affectionately."),
    (12, "carbuncle", "a red, swollen infection or a bright red gemstone,"),
    (13, "catamaran", "a boat with two parallel hulls."),
    (14, "chicanery", "the use of trickery to achieve a purpose."),
    (15, "claptrap", "absurd or nonsensical talk."),
    (16, "clishmaclaver", "gossip or idle talk."),
    (17, "concoction", "a mixture of various ingredients."),
    (18, "coochie", "coo - playful teasing or baby talk."),
    (19, "cumbersome", "large, heavy, and difficult to manage."),
    (20, "dingbat", "a silly or eccentric person."),
    (21, "dingleberry", "a small piece of clinging debris."),
    (22, "dollop", "a shapeless mass or blob of something."),
    (23, "doodlebug", "a type of insect or a guided missile."),
    (24, "doohickey", "an unnamed gadget or device."),
    (25, "doozy", "something remarkable or outstanding."),
    (26, "dunderhead", "a stupid or foolish person."),
    (27, "fandango", "a lively Spanish dance."),
    (28, "fiddle", "faddle - trivial or nonsensical fuss."),
    (29, "fiddlesticks", "an exclamation of annoyance."),
    (30, "flabbergasted", "shocked or greatly surprised."),
    (31, "flibbertigibbet", "a frivolous or overly talkative person."),
    (32, "flummery", "meaningless or insincere talk."),
    (33, "flummox", "to perplex or bewilder."),
    (34, "frippery", "unnecessary decoration or ornamentation."),
    (35, "fuddy", "duddy - a person who is old-fashioned or fussy."),
    (36, "gibberish", "meaningless speech or nonsense."),
    (37, "gigglemug", "a person who is always smiling."),
    (38, "gobbledygook", "overly complex or technical language."),
    (39, "gongoozle", "to stare idly at something."),
    (40, "googly", "a type of deceptive cricket ball,"),
    (41, "goombah", "a close friend or associate."),
    (42, "guffaw", "a loud, boisterous laugh."),
    (43, "higgledy", "piggledy - in a disorderly manner."),
    (44, "hocus", "pocus - meaningless talk or deception."),
    (45, "hoo", "ha - a commotion or uproar."),
    (46, "hootenanny", "an informal musical gathering."),
    (47, "hubbub", "a chaotic noise or situation."),
    (48, "hullabaloo", "a loud noise or fuss."),
    (49, "jabberwocky", "nonsensical speech or writing."),
    (50, "jackanapes", "a mischievous or impudent person."),
    (51, "jiggery", "pokery - dishonest manipulation."),
    (52, "kaleidoscope", "a constantly changing pattern or sequence."),
    (53, "kaput", "broken or useless."),
    (54, "kerfuffle", "a commotion or fuss."),
    (55, "lackadaisical", "lacking enthusiasm or effort."),
    (56, "lickety", "split - very quickly."),
    (57, "lollapalooza", "an extraordinary event or thing."),
    (58, "lugubrious", "exaggeratedly mournful or gloomy."),
    (59, "mishmash", "a confused mixture of things."),
    (60, "mollycoddle", "to treat someone with excessive indulgence."),
    (61, "mumbo jumbo", "meaningless or confusing language."),
    (62, "murmuration", "a flock of starlings flying in formation."),
    (63, "namby", "pamby - weak or indecisive,"),
    (64, "nincompoop", "a foolish or silly person."),
    (65, "noodle", "to think or brainstorm."),
    (66, "oodles", "a large quantity of something."),
    (67, "pettifogger", "a lawyer who deals with petty cases."),
    (68, "piffle", "trivial nonsense."),
    (69, "pilfer", "to steal things of little value."),
    (70, "pipsqueak", "a person regarded as insignificant."),
    (71, "quagmire", "a difficult or precarious situation."),
    (72, "quirky", "having an unusual or peculiar trait."),
    (73, "ramshackle", "poorly constructed or in a state of disrepair."),
    (74, "razzmatazz", "elaborate display or showiness."),
    (75, "rigmarole", "a long, complicated process."),
    (76, "scallywag", "a mischievous or cheeky person."),
    (77, "scuttlebutt", "rumor or gossip."),
    (78, "scrumdiddlyumptious", "delicious or delightful."),
    (79, "shenanigans", "playful mischief or trickery."),
    (80, "skedaddle", "to depart quickly."),
    (81, "skullduggery", "underhanded or deceitful behavior."),
    (82, "slapdash", "done carelessly or hurriedly."),
    (83, "smorgasbord", "a wide variety of choices."),
    (84, "snickerdoodle", "a type of cookie with cinnamon and sugar."),
    (85, "snootful", "enough alcohol to make one drunk."),
    (86, "squabble", "a noisy quarrel."),
    (87, "thingamajig", "an item whose name is forgotten."),
    (88, "tintinnabulation", "the ringing of bells."),
    (89, "toodle", "oo - a lighthearted way to say goodbye."),
    (90, "topsy", "turvy - upside down or chaotic,"),
    (91, "wackadoodle", "eccentric or wacky."),
    (92, "whatchamacallit", "a thing whose name is forgotten."),
    (93, "whippersnapper", "a young and inexperienced person."),
    (94, "widdershins", "moving counterclockwise."),
    (95, "wishy", "washy - lacking in strength or clarity."),
    (96, "wobble", "to move unsteadily."),
    (97, "wombat", "a burrowing marsupial from Australia."),
    (98, "zany", "comical or unconventional."),
    (99, "zephyr", "a gentle breeze."),
    (100, "zippity", "doo-dah - an expression of happiness."),
]

person = [
    (1, "absent", "minded - often forgetful or distracted"),
    (2, "adaptable", "able to adjust easily"),
    (3, "adventurous", "willing to try exciting things"),
    (4, "affectionate", "showing love openly"),
    (5, "ambitious", "eager to succeed"),
    (6, "analytical", "good at examining ideas logically"),
    (7, "arrogant", "having too much pride"),
    (8, "assertive", "expressing yourself firmly"),
    (9, "bad", "tempered - often angry or irritable"),
    (10, "big", "hearted - very generous and kind"),
    (11, "blunt", "direct and sometimes rude"),
    (12, "bossy", "always telling others what to do"),
    (13, "broad", "minded - tolerant of different ideas"),
    (14, "calm", "not easily upset"),
    (15, "caring", "kind and concerned for others"),
    (16, "cheerful", "noticeably happy and positive"),
    (17, "childish", "silly in an immature way"),
    (18, "cold", "hearted - lacking sympathy or kindness"),
    (19, "compassionate", "showing sympathy and care"),
    (20, "composed", "calm and self-controlled"),
    (21, "considerate", "thoughtful of other people's needs"),
    (22, "courteous", "polite and respectful"),
    (23, "decisive", "able to decide quickly"),
    (24, "determined", "firmly resolved to succeed"),
    (25, "diligent", "showing steady careful effort"),
    (26, "diplomatic", "skilled at handling people sensitively"),
    (27, "disciplined", "showing controlled behavior"),
    (28, "driven", "strongly motivated to achieve"),
    (29, "earnest", "serious and sincere"),
    (30, "easy", "going - relaxed and not easily upset"),
    (31, "empathetic", "able to understand feelings deeply"),
    (32, "energetic", "full of energy"),
    (33, "fair", "minded - judging people impartially"),
    (34, "forgiving", "willing to stop blaming"),
    (35, "frank", "honest and direct"),
    (36, "free", "spirited - independent and unconventional"),
    (37, "generous", "willing to give freely"),
    (38, "gentle", "kind and mild in manner"),
    (39, "good", "natured - kind and pleasant by nature"),
    (40, "hard", "headed - practical and unsentimental"),
    (41, "hard", "working - puts in a lot of effort"),
    (42, "headstrong", "determined to do your own way"),
    (43, "high", "spirited - lively and energetic"),
    (44, "honest", "truthful and fair"),
    (45, "hot", "headed - acting angrily without thinking"),
    (46, "humble", "not proud or arrogant"),
    (47, "immature", "not fully emotionally developed"),
    (48, "impulsive", "acting without much thought"),
    (49, "indecisive", "unable to decide easily"),
    (50, "insensitive", "not aware of others' feelings"),
    (51, "kind", "hearted - naturally caring and sympathetic"),
    (52, "laid", "back - very relaxed and easygoing"),
    (53, "level", "headed - calm and sensible under pressure"),
    (54, "long", "suffering - patient despite difficulties"),
    (55, "low", "key - calm and not showy"),
    (56, "loyal", "faithful and supportive"),
    (57, "mature", "emotionally and mentally developed"),
    (58, "narrow", "minded - unwilling to accept other views"),
    (59, "obedient", "willing to follow rules"),
    (60, "open", "minded - willing to consider new ideas"),
    (61, "optimistic", "expecting good things"),
    (62, "outgoing", "friendly and sociable"),
    (63, "patient", "able to wait calmly"),
    (64, "perceptive", "quick to notice things"),
    (65, "persistent", "continuing despite difficulty"),
    (66, "pessimistic", "expecting bad outcomes"),
    (67, "polite", "showing good manners"),
    (68, "practical", "focused on useful action"),
    (69, "principled", "guided by strong morals"),
    (70, "pushy", "too forceful with others"),
    (71, "quick", "tempered - easily angered"),
    (72, "quick", "witted - mentally sharp and clever"),
    (73, "quiet", "not talkative or noisy"),
    (74, "reckless", "careless about risk"),
    (75, "reserved", "quiet and restrained"),
    (76, "resilient", "recovering quickly from setbacks"),
    (77, "respectful", "showing respect to others"),
    (78, "self", "centered - mainly concerned with oneself"),
    (79, "self", "confident - sure of your own abilities"),
    (80, "self", "disciplined - able to control yourself"),
    (81, "self", "effacing - modest and not attention-seeking"),
    (82, "self", "important - having an exaggerated sense of importance"),
    (83, "sharp", "tongued - harsh or biting in speech"),
    (84, "short", "tempered - angered very easily"),
    (85, "single", "minded - focused on one aim"),
    (86, "slow", "witted - not quick to understand"),
    (87, "soft", "spoken - speaks in a gentle quiet way"),
    (88, "strong", "minded - firm in opinions and decisions"),
    (89, "strong", "willed - determined and hard to influence"),
    (90, "tactful", "careful not to offend"),
    (91, "talkative", "liking to talk a lot"),
    (92, "thick", "skinned - not easily offended"),
    (93, "tolerant", "accepting of differences or difficulties"),
    (94, "trustworthy", "deserving trust"),
    (95, "warm", "hearted - kind and affectionate"),
    (96, "weak", "willed - easily influenced by others"),
    (97, "well", "adjusted - emotionally stable and healthy"),
    (98, "well", "mannered - polite and respectful"),
    (99, "wise", "showing deep good judgment"),
    (100, "witty", "clever and funny"),
]

decisions = [
    (1, "accept an offer", "choose to agree"),
    (2, "act on impulse", "decide suddenly without planning"),
    (3, "adopt a policy", "choose a policy officially"),
    (4, "approve a plan", "accept a proposed plan"),
    (5, "arrive at a decision", "reach a conclusion or choice"),
    (6, "backtrack on", "withdraw a previous decision"),
    (7, "balance the risks", "consider possible dangers"),
    (8, "bite the bullet", "decide to face difficulty"),
    (9, "break the deadlock", "end decision stalemate"),
    (10, "call the shots", "make the important decisions"),
    (11, "change your mind", "decide differently"),
    (12, "choose a path", "select a direction"),
    (13, "choose between", "select from alternatives"),
    (14, "come to a decision", "finally decide something"),
    (15, "commit to", "decide firmly on"),
    (16, "consider the alternatives", "think about other options"),
    (17, "consult with others", "discuss before deciding"),
    (18, "decide against", "choose not to do"),
    (19, "decide on", "choose after consideration"),
    (20, "decline an offer", "choose not to accept"),
    (21, "defer a decision", "postpone choosing"),
    (22, "delay a decision", "wait before choosing"),
    (23, "draw a conclusion", "form a judgment from evidence"),
    (24, "evaluate the options", "assess possible choices"),
    (25, "exercise judgment", "use careful decision skills"),
    (26, "factor in", "include as relevant"),
    (27, "figure out", "determine the answer"),
    (28, "find a way forward", "identify the next step"),
    (29, "find common ground", "reach shared agreement"),
    (30, "follow your instincts", "act on inner sense"),
    (31, "form a judgment", "make an evaluative decision"),
    (32, "gather information", "collect facts before deciding"),
    (33, "give it some thought", "consider it carefully"),
    (34, "give the go", "ahead - authorize proceeding"),
    (35, "give the green light", "approve proceeding"),
    (36, "go ahead with", "proceed with the choice"),
    (37, "grant approval", "officially agree to something"),
    (38, "hand down a ruling", "issue an official decision"),
    (39, "hash it out", "discuss until settled"),
    (40, "have second thoughts", "begin to doubt a decision"),
    (41, "have the final say", "make the last decision"),
    (42, "hedge your bets", "avoid one clear choice"),
    (43, "hold off on", "delay deciding or acting"),
    (44, "in two minds", "uncertain between choices"),
    (45, "issue a decision", "announce a formal choice"),
    (46, "jump to conclusions", "decide too quickly"),
    (47, "keep an open mind", "stay willing to reconsider"),
    (48, "keep your options open", "avoid deciding too soon"),
    (49, "leave it to", "let someone else decide"),
    (50, "left to decide", "remaining to be chosen"),
    (51, "look at the big picture", "consider the overall situation"),
    (52, "make a choice", "select one option"),
    (53, "make a decision", "choose a course of action"),
    (54, "make a judgment call", "decide using personal judgment"),
    (55, "make a ruling", "give an official decision"),
    (56, "make a snap decision", "decide very quickly"),
    (57, "make up your mind", "decide finally"),
    (58, "meet halfway", "compromise in deciding"),
    (59, "move forward with", "continue with the decision"),
    (60, "narrow it down", "reduce the options"),
    (61, "on balance", "all things considered"),
    (62, "on the fence", "unable to choose"),
    (63, "opt for", "choose one option"),
    (64, "pending a decision", "awaiting a final choice"),
    (65, "play it by ear", "decide as events unfold"),
    (66, "postpone a decision", "move the choice later"),
    (67, "pull the trigger", "decide to start action"),
    (68, "put it to a vote", "decide by voting"),
    (69, "reach a conclusion", "decide after considering facts"),
    (70, "reach a decision", "arrive at a final choice"),
    (71, "reassess the situation", "evaluate again"),
    (72, "reconsider your position", "think again about your view"),
    (73, "rethink the plan", "consider the plan again"),
    (74, "review your options", "look again at choices"),
    (75, "revisit the decision", "consider the decision again"),
    (76, "rule out", "eliminate from consideration"),
    (77, "seek advice", "ask others for guidance"),
    (78, "select an option", "choose one possibility"),
    (79, "set priorities", "rank what matters most"),
    (80, "settle on a plan", "choose a plan"),
    (81, "shortlist the options", "select top possibilities"),
    (82, "sleep on it", "delay deciding until later"),
    (83, "stick with", "continue choosing the same"),
    (84, "still undecided", "not having chosen yet"),
    (85, "take a decision", "make an official choice"),
    (86, "take a vote", "decide through voting"),
    (87, "take into account", "include in consideration"),
    (88, "take time to decide", "avoid rushing a choice"),
    (89, "talk it through", "discuss to reach a decision"),
    (90, "think it over", "consider carefully before deciding"),
    (91, "torn between", "unable to choose between"),
    (92, "trust your judgment", "rely on your own assessment"),
    (93, "under consideration", "being thought about"),
    (94, "use discretion", "decide with careful restraint"),
    (95, "vote on", "decide by formal voting"),
    (96, "wait and see", "delay judgment for now"),
    (97, "weigh the options", "compare possible choices carefully"),
    (98, "weigh the pros and cons", "compare advantages and disadvantages"),
    (99, "withhold judgment", "avoid forming a conclusion"),
    (100, "yet to be decided", "not decided yet"),
]

literally = [
    (1, "actually", "In fact; really; as a matter of truth."),
    (2, "as it happens", "In reality; by coincidence; in actual circumstances."),
    (3, "at bottom", "Fundamentally; in the most basic sense."),
    (4, "at face value", "According to the plain, stated meaning."),
    (5, "authentically", "In a genuine, true-to-life way."),
    (6, "barely figurative", "Almost not figurative; close to exact."),
    (7, "bona fide", "Genuine; real; not fake or pretended."),
    (8, "by the book", "Exactly according to rules or instructions."),
    (9, "categorically", "Without exception; in absolute terms."),
    (10, "concretely", "In a definite, specific, tangible way."),
    (11, "correctly speaking", "With strict accuracy in wording or meaning."),
    (12, "de facto", "In reality, regardless of formal status."),
    (13, "dead", "on - Exactly right; precisely accurate."),
    (14, "definitely", "Certainly; without doubt; clearly true."),
    (15, "demonstrably", "In a provable, verifiable manner."),
    (16, "directly", "Without mediation; in a straightforward way."),
    (17, "downright", "Thoroughly; utterly; without reservation."),
    (18, "effectively", "In practice; for all intents and purposes."),
    (19, "empirically", "Based on observation or experiment; verifiably."),
    (20, "exactly", "Precisely; without deviation; just so."),
    (21, "explicitly", "Stated clearly and directly; unambiguously."),
    (22, "factually", "According to facts; not imagined or invented."),
    (23, "fairly", "To a reasonable degree; somewhat accurately."),
    (24, "flat", "out - Completely and plainly; without qualification."),
    (25, "for real", "Genuinely; not joking; truly."),
    (26, "for sure", "Certainly; without uncertainty."),
    (27, "for the record", "To state officially; as a matter of fact."),
    (28, "frankly", "In an honest, direct manner."),
    (29, "genuinely", "Truly; sincerely; without pretense."),
    (30, "god's honest truth", "Absolute truth; said with strong sincerity."),
    (31, "hard fact", "An undeniable, objective truth."),
    (32, "historically", "In actual past events; as recorded."),
    (33, "honest", "to-goodness - Real; genuine; not exaggerated."),
    (34, "in actuality", "In fact; in reality."),
    (35, "in all honesty", "Truthfully; without deceit or exaggeration."),
    (36, "in concrete terms", "In specific, definite terms; not abstract."),
    (37, "in essence", "In the most important, basic sense."),
    (38, "in fact", "Used to emphasize truth or reality."),
    (39, "in literal terms", "Using the exact, non-figurative meaning."),
    (40, "in plain english", "Simply and clearly; without jargon."),
    (41, "in point of fact", "In reality; indeed; actually."),
    (42, "in practice", "In real-world application; actually."),
    (43, "in reality", "As things truly are; not imagined."),
    (44, "in so many words", "Expressed directly; explicitly stated."),
    (45, "in strict terms", "With exactness; by precise definition."),
    (46, "indisputably", "Beyond dispute; unquestionably true."),
    (47, "inevitably", "As a necessary result; unavoidably."),
    (48, "infallibly", "Without error; always correctly."),
    (49, "just so", "Exactly; precisely in that way."),
    (50, "latterly", "In recent times; as of late."),
    (51, "legitimately", "Rightfully; genuinely; in a valid way."),
    (52, "manifestly", "Plainly; obviously; clearly shown."),
    (53, "matter", "of-factly - In a straightforward, factual manner."),
    (54, "meaningfully", "In a way that conveys real sense."),
    (55, "metaphor", "free - Without metaphor; strictly non-figurative."),
    (56, "more precisely", "With greater exactness; to be accurate."),
    (57, "most assuredly", "Certainly; without any doubt."),
    (58, "naked truth", "The plain, unadorned truth."),
    (59, "necessarily", "As a logical requirement; inevitably."),
    (60, "no exaggeration", "Said without overstatement; truly."),
    (61, "no joke", "Seriously; not an exaggeration."),
    (62, "not figuratively", "In a non-metaphorical, exact sense."),
    (63, "notionally", "By definition or concept; in name."),
    (64, "objectively", "Based on facts; not personal feelings."),
    (65, "on the nose", "Exactly; precisely; perfectly matched."),
    (66, "on the record", "Publicly and officially stated; factual."),
    (67, "outright", "Completely; without reservation; plainly."),
    (68, "palpably", "In a way that is easily perceived."),
    (69, "plainly", "Clearly; obviously; without ambiguity."),
    (70, "positively", "Certainly; definitely; without doubt."),
    (71, "practically", "For practical purposes; almost; effectively."),
    (72, "precisely", "Exactly; with exact detail."),
    (73, "properly", "Correctly; in the right manner."),
    (74, "provably", "In a way that can be proven."),
    (75, "purely", "Solely; entirely; without mixture."),
    (76, "quite", "To a considerable degree; fairly."),
    (77, "really", "In truth; actually; genuinely."),
    (78, "rightly", "Correctly; with justification; properly."),
    (79, "rigidly", "Strictly; without flexibility or deviation."),
    (80, "rigorously", "With strict accuracy and thoroughness."),
    (81, "same as saying", "Equivalent in meaning; effectively stated."),
    (82, "sincerely", "Genuinely; without pretense or irony."),
    (83, "so to speak", "As an expression; not strictly exact."),
    (84, "straight", "Directly; honestly; without evasion."),
    (85, "straight", "up - Honestly; plainly; without exaggeration."),
    (86, "strictly", "In exact terms; without exception."),
    (87, "strictly speaking", "In precise terms; by exact definition."),
    (88, "substantially", "In essence; largely; for the most part."),
    (89, "technically", "By strict definition; in exact terms."),
    (90, "to be exact", "Used to specify precise information."),
    (91, "to be frank", "Used to signal honest, direct speech."),
    (92, "to be precise", "Used to add exact detail."),
    (93, "truly", "In fact; genuinely; without exaggeration."),
    (94, "truthfully", "In a truthful, honest manner."),
    (95, "unambiguously", "Clearly; with only one possible meaning."),
    (96, "undeniably", "Impossible to deny; certainly true."),
    (97, "unmistakably", "Clearly recognizable; not open to doubt."),
    (98, "unquestionably", "Without question; certainly; indisputably."),
    (99, "verifiably", "In a way that can be checked."),
    (100, "veritably", "Truly; in effect; practically."),
]

and_words = [
    (1, "accordingly", "As a result; therefore."),
    (2, "add to that", "Additionally; to include another point."),
    (3, "additionally", "In addition; also."),
    (4, "after that", "Then; subsequently."),
    (5, "afterward", "Later; following that."),
    (6, "along with", "Together with; as well as."),
    (7, "alongside", "Together with; next to."),
    (8, "also", "In addition; too."),
    (9, "alternatively", "As another option; instead."),
    (10, "and then", "Next; after that."),
    (11, "as a consequence", "As a result; therefore."),
    (12, "as a result", "Therefore; consequently."),
    (13, "as an aside", "Introducing a minor extra comment."),
    (14, "as for", "Regarding; conceming."),
    (15, "as such", "In that capacity; therefore."),
    (16, "as well as", "In addition to; plus."),
    (17, "at the same time", "Simultaneously; meanwhile."),
    (18, "be that as it may", "Nevertheless; even so."),
    (19, "besides", "In addition; also."),
    (20, "by contrast", "In contrast; however."),
    (21, "by the same token", "For the same reason; similarly."),
    (22, "by the way", "Introducing an extra, often unrelated point."),
    (23, "come to think of it", "On reflection; actually."),
    (24, "concurrently", "At the same time; simultaneously."),
    (25, "consequently", "As a result; therefore."),
    (26, "conversely", "In contrast; on the other hand."),
    (27, "coupled with", "Combined with; together with."),
    (28, "despite that", "Even so; nevertheless."),
    (29, "ditto", "The same as previously mentioned."),
    (30, "else", "In addition; otherwise."),
    (31, "equally", "To the same degree; likewise."),
    (32, "even so", "Nevertheless; despite that."),
    (33, "except", "Not including; other than."),
    (34, "for example", "Introducing an illustration."),
    (35, "for instance", "Introducing an example."),
    (36, "further", "To a greater extent; additionally."),
    (37, "furthermore", "Moreover; in addition."),
    (38, "hence", "For this reason; therefore."),
    (39, "however", "But; in contrast."),
    (40, "in addition", "Also; furthermore."),
    (41, "in any case", "Anyway; regardless."),
    (42, "in contrast", "Showing differences; however."),
    (43, "in fact", "Actually; to emphasize truth."),
    (44, "in other words", "Restating more clearly."),
    (45, "in parallel", "At the same time; concurrently."),
    (46, "in summary", "To sum up; briefly."),
    (47, "in the meantime", "Meanwhile; during that time."),
    (48, "in turn", "As a result; subsequently."),
    (49, "including", "Containing as part of a whole."),
    (50, "indeed", "In fact; certainly."),
    (51, "instead", "As an alternative; rather."),
    (52, "just as", "In the same way; similarly."),
    (53, "lastly", "Finally; at the end."),
    (54, "likewise", "In the same way; also."),
    (55, "meanwhile", "At the same time; in the meantime."),
    (56, "moreover", "In addition; furthermore."),
    (57, "nevertheless", "Despite that; even so."),
    (58, "next", "After that; subsequently."),
    (59, "nonetheless", "Nevertheless; even so."),
    (60, "not to mention", "Adding emphasis to an additional point."),
    (61, "notwithstanding", "Despite; in spite of."),
    (62, "on the contrary", "Opposite of what was expected."),
    (63, "on the other hand", "Introducing a contrasting point."),
    (64, "on top of it", "Additionally; moreover."),
    (65, "on top of that", "Additionally; moreover."),
    (66, "or", "Introducing an alternative choice."),
    (67, "or else", "Otherwise; if not."),
    (68, "otherwise", "If not; or else."),
    (69, "plus", "And; in addition."),
    (70, "provided that", "Only if; on condition that."),
    (71, "rather", "Instead; more accurately."),
    (72, "regardless", "Anyway, without considering that."),
    (73, "same with", "Similarly; also applies to."),
    (74, "similarly", "In a similar way; likewise."),
    (75, "simultaneously", "At the same time."),
    (76, "since then", "From that time until now."),
    (77, "so", "Therefore; as a result."),
    (78, "still", "Nevertheless; even so."),
    (79, "subsequently", "Afterward; later."),
    (80, "such as", "For example; like."),
    (81, "then", "Next; after that."),
    (82, "thereafter", "After that; from then on."),
    (83, "thereby", "By that means; as a result."),
    (84, "therefore", "For that reason; consequently."),
    (85, "thus", "As a result; therefore."),
    (86, "to boot", "In addition; moreover."),
    (87, "to conclude", "To finish; in summary."),
    (88, "to sum up", "In summary; briefly."),
    (89, "together with", "Along with; plus."),
    (90, "too", "Also; as well."),
    (91, "ultimately", "In the end; finally."),
    (92, "until", "Up to the time when."),
    (93, "what's more", "Moreover; additionally."),
    (94, "when", "At the time that."),
    (95, "whereas", "While, in contrast."),
    (96, "while", "During the time that; whereas."),
    (97, "with that", "After saying this; then."),
    (98, "with this in mind", "Considering this; therefore."),
    (99, "withal", "Moreover; in addition."),
    (100, "yet", "However; nevertheless."),
]

smart = [
    (1, "Adept", "Highly skilled or proficient."),
    (2, "Adroit", "Clever or skillful with hands or mind."),
    (3, "Aesthetic", "Concerned with beauty or artistic impact."),
    (4, "Alacrity", "Brisk and cheerful readiness."),
    (5, "Ambivalent", "Having mixed or conflicting feelings."),
    (6, "Anachronistic", "Belonging to a different time period."),
    (7, "Anecdotal", "Based on personal stories rather than facts."),
    (8, "Apathetic", "Showing or feeling little interest or concern."),
    (9, "Aplomb", "Self-confidence or assurance."),
    (10, "Arduous", "Requiring great effort; difficult."),
    (11, "Assuage", "To ease or lessen pain or distress."),
    (12, "Astute", "Clever and perceptive."),
    (13, "Auspicious", "Indicating a favorable outcome."),
    (14, "Banal", "Lacking originality; boring."),
    (15, "Bellicose", "Inclined to fight or argue."),
    (16, "Benevolent", "Well-meaning and kindly."),
    (17, "Blithe", "Casual or cheerful indifference."),
    (18, "Brevity", "Concise and exact use of words."),
    (19, "Cacophony", "A harsh, discordant mixture of sounds."),
    (20, "Candor", "Being open and honest."),
    (21, "Capricious", "Sudden changes in mood or behavior."),
    (22, "Caveat", "A warning or proviso."),
    (23, "Circumspect", "Cautious and considering all circumstances."),
    (24, "Cogent", "Clear, logical, and convincing."),
    (25, "Colloquial", "Informal or conversational language."),
    (26, "Concur", "To agree with."),
    (27, "Conundrum", "A confusing and difficult problem."),
    (28, "Copacetic", "Completely satisfactory; fine."),
    (29, "Cordial", "Warm and friendly."),
    (30, "Cursory", "Hasty and superficial."),
    (31, "Debacle", "A sudden and complete failure."),
    (32, "Deference", "Respectful submission or yielding."),
    (33, "Deft", "Neatly skillful and quick."),
    (34, "Delineate", "To describe precisely."),
    (35, "Demure", "Modest and reserved."),
    (36, "Didactic", "Intended to instruct."),
    (37, "Disparate", "Essentially different in kind."),
    (38, "Disseminate", "Spread widely (especially ideas)."),
    (39, "Dogmatic", "Stubbornly opinionated."),
    (40, "Dubious", "Doubtful or uncertain."),
    (41, "Ebullient", "Cheerful and full of energy."),
    (42, "Eclectic", "From a variety of sources."),
    (43, "Egregious", "Outstandingly bad."),
    (44, "Eloquent", "Fluent and persuasive in speech."),
    (45, "Elucidate", "To make clear."),
    (46, "Empirical", "Based on observation or experience."),
    (47, "Enigmatic", "Mysterious and difficult to understand."),
    (48, "Ephemeral", "Lasting a very short time."),
    (49, "Equanimity", "Mental calmness and composure."),
    (50, "Esoteric", "Understood by a select few."),
    (51, "Euphemism", "Mild word replacing a harsh one."),
    (52, "Exacerbate", "To make worse."),
    (53, "Facetious", "Joking often inappropriately."),
    (54, "Fastidious", "Very attentive to detail."),
    (55, "Fortuitous", "Happening by chance; lucky."),
    (56, "Furtive", "Secretive or stealthy."),
    (57, "Garrulous", "Excessively talkative. ;"),
    (58, "Gregarious", "Fond of company; sociable."),
    (59, "Harbinger", "Sign of something to come."),
    (60, "Hubris", "Excessive pride or self-confidence."),
    (61, "Idiosyncratic", "Peculiar or individual."),
    (62, "Ineffable", "Too great for words."),
    (63, "Inexorable", "Impossible to stop or prevent."),
    (64, "Infallible", "Incapable of making mistakes."),
    (65, "Ingenuous", "Innocent and unsuspecting."),
    (66, "Insidious", "Subtly harmful."),
    (67, "Intrepid", "Fearless and adventurous."),
    (68, "Juxtapose", "To place side by side for contrast."),
    (69, "Lethargic", "Sluggish and apathetic."),
    (70, "Lucid", "Expressed clearly and easy to understand."),
    (71, "Magnanimous", "Generous in forgiving."),
    (72, "Malevolent", "Wishing harm to others."),
    (73, "Mellifluous", "Sweet-sounding or pleasant to hear."),
    (74, "Meticulous", "Very careful and precise."),
    (75, "Misanthrope", "A person who dislikes humankind."),
    (76, "Mitigate", "To make less severe."),
    (77, "Moot", "Open to debate."),
    (78, "Myriad", "A countless or great number."),
    (79, "Nebulous", "Vague or unclear."),
    (80, "Nefarious", "Wicked or criminal."),
    (81, "Nonchalant", "Calm and unconcerned."),
    (82, "Noxious", "Harmful or poisonous."),
    (83, "Obfuscate", "To confuse or obscure."),
    (84, "Obsequious", "Overly submissive or eager to please."),
    (85, "Omnipotent", "All-powerful."),
    (86, "Ostentatious", "Showy and pretentious."),
    (87, "Paradox", "A contradictory but true statement."),
    (88, "Pedantic", "Overly concerned with details."),
    (89, "Pejorative", "Expressing disapproval."),
    (90, "Perfunctory", "Done routinely with little interest."),
    (91, "Perspicacious", "Having keen understanding."),
    (92, "Placate", "To calm or appease."),
    (93, "Precocious", "Advanced for one's age."),
    (94, "Proclivity", "A natural tendency."),
    (95, "Quintessential", "The perfect example of something."),
    (96, "Rancor", "Bitter resentment."),
    (97, "Recalcitrant", "Stubbornly disobedient."),
    (98, "Sagacious", "Wise and insightful."),
    (99, "Salient", "Most noticeable or important. h"),
    (100, "Sanguine", "Optimistic or positive."),
]

materials = [
    (1, "acrylic", "synthetic plastic or fiber"),
    (2, "bamboo", "hard fast-growing plant material"),
    (3, "biodegradable", "able to break down naturally"),
    (4, "brick", "hard baked clay block"),
    (5, "brittle", "breaks easily under pressure"),
    (6, "bumpy", "covered with raised lumps"),
    (7, "burlap", "coarse woven sackcloth"),
    (8, "chalky", "dry and powder-like"),
    (9, "clayey", "like clay in texture"),
    (10, "clear", "easy to see through"),
    (11, "cloudy", "not clear or transparent"),
    (12, "coarse", "rough in texture"),
    (13, "corrugated", "shaped into ridges and grooves"),
    (14, "crinkly", "full of small wrinkles"),
    (15, "crisp", "firm and easily broken"),
    (16, "denim", "strong cotton twill fabric"),
    (17, "dense", "closely packed and heavy"),
    (18, "downy", "covered with soft fluff"),
    (19, "dull", "not bright or shiny"),
    (20, "durable", "lasting a long time"),
    (21, "elastic", "stretching and returning easily"),
    (22, "feathery", "light and soft textured"),
    (23, "fibrous", "made of many fibers"),
    (24, "fine", "delicate or very small"),
    (25, "flexible", "able to bend easily"),
    (26, "fluffy", "light and soft"),
    (27, "fragile", "easily broken or damaged"),
    (28, "fuzzy", "covered with soft fibers"),
    (29, "gaseous", "existing as gas"),
    (30, "glossy", "shiny and reflective"),
    (31, "grainy", "having a gritty texture"),
    (32, "granular", "made of small grains"),
    (33, "greasy", "covered with oily substance"),
    (34, "gritty", "containing small rough particles"),
    (35, "grooved", "marked with long channels"),
    (36, "gummy", "soft and sticky"),
    (37, "hairy", "covered with hairlike fibers"),
    (38, "hard", "firm and not easily bent"),
    (39, "heavy", "weighing a lot"),
    (40, "hemp", "strong coarse plant fiber"),
    (41, "hollow", "empty inside"),
    (42, "jute", "strong plant fiber"),
    (43, "latex", "milky rubbery liquid substance"),
    (44, "leather", "animal skin made durable"),
    (45, "leathery", "tough like leather"),
    (46, "light", "not heavy for its size"),
    (47, "linen", "fabric made from flax"),
    (48, "liquid", "flowing like a fluid"),
    (49, "lumpy", "full of uneven lumps"),
    (50, "lustrous", "having a soft shine"),
    (51, "marble", "hard polished stone"),
    (52, "matte", "dull and not shiny"),
    (53, "mesh", "material with open holes"),
    (54, "metal", "hard shiny material"),
    (55, "metallic", "like metal in appearance"),
    (56, "muddy", "wet and dirty like mud"),
    (57, "natural", "existing without human making"),
    (58, "nonporous", "not allowing liquid through"),
    (59, "nylon", "strong synthetic fiber"),
    (60, "oily", "containing or coated with oil"),
    (61, "opaque", "not letting light through"),
    (62, "organic", "from living matter"),
    (63, "papery", "thin and like paper"),
    (64, "pebbled", "having a small bumpy texture"),
    (65, "pitted", "marked with small holes"),
    (66, "plastic", "made of synthetic polymer"),
    (67, "porous", "full of tiny holes"),
    (68, "powdery", "like fine dry powder"),
    (69, "resilient", "quickly regaining original shape"),
    (70, "ridged", "having raised lines"),
    (71, "rigid", "stiff and not flexible"),
    (72, "rough", "having an uneven surface"),
    (73, "rubber", "elastic waterproof material"),
    (74, "rubbery", "elastic like rubber"),
    (75, "slick", "smooth and slippery"),
    (76, "slippery", "easy to slide on"),
    (77, "smooth", "even and free from roughness"),
    (78, "soft", "easy to press or bend"),
    (79, "spongy", "soft and full of holes"),
    (80, "sticky", "tending to adhere to surfaces"),
    (81, "stiff", "hard to bend or move"),
    (82, "strong", "able to withstand force"),
    (83, "tacky", "slightly sticky to touch"),
    (84, "textile", "woven fabric material"),
    (85, "thick", "having a large width"),
    (86, "thin", "having little width"),
    (87, "translucent", "letting some light through"),
    (88, "transparent", "letting light pass clearly"),
    (89, "unpolished", "not smoothed or shined"),
    (90, "untreated", "not chemically processed"),
    (91, "velour", "soft plush fabric"),
    (92, "velvety", "soft and smooth like velvet"),
    (93, "vinyl", "durable plastic material"),
    (94, "viscous", "thick and slow-flowing"),
    (95, "waxy", "smooth and slightly greasy"),
    (96, "weak", "easily damaged or broken"),
    (97, "wooden", "made of wood"),
    (98, "woody", "made of or like wood"),
    (99, "woolly", "covered with woollike fibers"),
    (100, "wrinkled", "marked with small folds"),
]

sounds = [
    (1, "baa", "the cry of a sheep"),
    (2, "bang", "a sudden loud explosive sound"),
    (3, "bark", "a short explosive cry"),
    (4, "beat", "a regular striking sound"),
    (5, "beep", "a short electronic sound"),
    (6, "dbleat", "a wavering animal cry"),
    (7, "bonk", "a light blunt impact sound"),
    (8, "boom", "a deep resonant sound"),
    (9, "burp", "a belching sound"),
    (10, "buzz", "a low humming sound"),
    (11, "cackle", "a loud harsh laugh"),
    (12, "caw", "a harsh bird cry"),
    (13, "chirp", "a short cheerful bird sound"),
    (14, "chuckle", "a quiet amused laugh"),
    (15, "clang", "a loud metallic ringing sound"),
    (16, "clatter", "a series of loud rattling sounds"),
    (17, "click", "a short sharp sound"),
    (18, "coo", "a soft murmuring sound"),
    (19, "cough", "a sudden throat-clearing sound"),
    (20, "crackle", "a series of tiny sharp sounds"),
    (21, "crash", "a loud breaking or smashing sound"),
    (22, "croak", "a rough low sound"),
    (23, "drip", "the sound of falling drops"),
    (24, "drone", "a continuous low monotonous sound"),
    (25, "echo", "a reflected repeated sound"),
    (26, "fizz", "a soft hissing bubbling sound"),
    (27, "gasp", "a sudden intake sound"),
    (28, "giggle", "a light silly laugh"),
    (29, "groan", "a deep sound of suffering"),
    (30, "growl", "a low rough threatening sound"),
    (31, "grunt", "a short low guttural sound"),
    (32, "guffaw", "a loud hearty laugh"),
    (33, "gulp", "a loud swallowing sound"),
    (34, "gurgle", "a bubbling liquid sound"),
    (35, "hiss", "a sharp sibilant sound"),
    (36, "hoot", "a deep owl-like cry"),
    (37, "howl", "a long mournful cry"),
    (38, "hum", "a low steady sound"),
    (39, "jingle", "a light ringing sound"),
    (40, "knock", "a sharp striking sound"),
    (41, "mew", "a small weak cry"),
    (42, "miaow", "the cry of a cat"),
    (43, "moan", "a low sound of pain"),
    (44, "moo", "the cry of a cow"),
    (45, "murmur", "a low continuous soft sound"),
    (46, "neigh", "the cry of a horse"),
    (47, "oink", "the cry of a pig"),
    (48, "pant", "a quick heavy breathing sound"),
    (49, "patter", "a light rapid tapping sound"),
    (50, "peep", "a small high sound"),
    (51, "ping", "a short high metallic sound"),
    (52, "pitter", "patter - light repeated tapping sounds"),
    (53, "plop", "a soft sound into liquid"),
    (54, "pop", "a small sudden explosive sound"),
    (55, "purr", "a low vibrating sound"),
    (56, "rap", "a quick sharp knock"),
    (57, "rattle", "a rapid knocking sound"),
    (58, "ring", "a clear resonant sound"),
    (59, "roar", "a deep loud prolonged sound"),
    (60, "rumble", "a deep rolling sound"),
    (61, "rustle", "a soft crackling movement sound"),
    (62, "screech", "a harsh high-pitched sound"),
    (63, "shriek", "a sharp piercing cry"),
    (64, "shuffle", "a dragging foot sound"),
    (65, "sigh", "a long audible breath"),
    (66, "slurp", "a noisy sucking sound"),
    (67, "snap", "a quick cracking sound"),
    (68, "snarl", "a harsh angry sound"),
    (69, "sneeze", "a sudden explosive nasal sound"),
    (70, "snicker", "a suppressed disrespectful laugh"),
    (71, "sniffle", "a repeated nose-drawing sound"),
    (72, "snort", "a forceful sound through the nose"),
    (73, "sob", "a broken crying sound"),
    (74, "splash", "a liquid striking sound"),
    (75, "splutter", "a series of spitting sounds"),
    (76, "sputter", "a series of uneven popping sounds"),
    (77, "squeal", "a long high-pitched cry"),
    (78, "swish", "a soft sweeping sound"),
    (79, "tap", "a light striking sound"),
    (80, "throb", "a strong rhythmic sound"),
    (81, "thud", "a dull heavy impact sound"),
    (82, "ting", "a light clear metallic sound"),
    (83, "tinkle", "a series of light rings"),
    (84, "fitter", "a nervous restrained laugh"),
    (85, "trill", "a rapid quavering sound"),
    (86, "twang", "a sharp vibrating sound"),
    (87, "vroom", "a car engine sound"),
    (88, "wail", "a long sad cry"),
    (89, "warble", "a frilling musical sound"),
    (90, "whack", "a heavy striking sound"),
    (91, "wheeze", "a whistling breathing sound"),
    (92, "whine", "a high complaining sound"),
    (93, "whir", "a low spinning sound"),
    (94, "whirr", "a soft rapid rotating sound"),
    (95, "whisper", "a very soft breathy sound"),
    (96, "whoosh", "a rushing air sound"),
    (97, "yammer", "a loud complaining sound"),
    (98, "yap", "a sharp repeated bark"),
    (99, "yell", "a loud sharp cry"),
    (100, "yelp", "a short sharp cry"),
]

SECTIONS = [
    (8, "suddenly", "100 Best Synonyms for &ldquo;Suddenly&rdquo;", "Alternatives for sudden or immediate timing, numbered 1\u2013100.", suddenly),
    (9, "abnormal", "100 Best Synonyms for &ldquo;Abnormal&rdquo;", "Words for strange, atypical, or off-pattern things, numbered 1\u2013100.", abnormal),
    (10, "impactverbs", "100 High-Impact Verbs for Action-Takers", "Strong verbs for leaders and doers, numbered 1\u2013100.", impactverbs),
    (11, "awkward", "100 Words to Use Instead of &ldquo;Awkward&rdquo;", "Alternatives when a moment or person feels uncomfortable, numbered 1\u2013100.", awkward),
    (12, "funwords", "100 Fun-to-Say Words", "Playful vocabulary worth saying out loud, numbered 1\u2013100.", funwords),
    (13, "person", "100 Words to Describe a Person", "Character traits and qualities, numbered 1\u2013100.", person),
    (14, "decisions", "100 Collocations for Decision Making", "Common decision-making phrases, numbered 1\u2013100.", decisions),
    (15, "literally", "100 Words to Use Instead of &ldquo;Literally&rdquo;", "Alternatives for emphasis without overusing literally, numbered 1\u2013100.", literally),
    (16, "and", "100 Words to Use Instead of &ldquo;And&rdquo;", "Connectors and transitions beyond and, numbered 1\u2013100.", and_words),
    (17, "smart", "100 Smart Words", "Precise, intelligent-sounding vocabulary, numbered 1\u2013100.", smart),
    (18, "materials", "100 Words to Describe Materials", "Texture and material descriptors, numbered 1\u2013100.", materials),
    (19, "sounds", "100 One-Word Substitutions to Describe Sounds", "Single words for common sounds, numbered 1\u2013100.", sounds),
]

if __name__ == "__main__":
    from pathlib import Path
    out = []
    for num, sid, title, note, items in SECTIONS:
        out.append(section(num, sid, title, note, items))
    Path(__file__).with_name("_new_sections.html").write_text("\n".join(out) + "\n", encoding="utf-8")

