#!/usr/bin/env python3
"""Generate HTML batch 3: sections 26-34 + sunset word supplement for section 23."""
from pathlib import Path


def section(num, sid, title, note, items):
    lines = [
        f'      <section id="{sid}">',
        f'        <h2>{num}. {title}</h2>',
        f'        <p class="note">{note}</p>',
        '        <div class="entry filterable">',
        '          <ul class="def-list">',
    ]
    for n, term, meaning in items:
        term_esc = term.replace("&", "&amp;")
        meaning_esc = meaning.replace("&", "&amp;")
        lines.append(f'            <li><strong>{n}. {term_esc}</strong> \u2013 {meaning_esc}</li>')
    lines += [
        '          </ul>',
        '        </div>',
        '      </section>',
        '',
    ]
    return "\n".join(lines)


def sunset_supplement(items):
    lines = [
        '        <div class="entry filterable">',
        '          <h3>Sunset descriptors (1\u2013100)</h3>',
        '          <p class="note" style="margin:0 0 0.35rem;font-size:0.86rem;">Single words for describing sunsets; numbered as on your sheet.</p>',
        '          <ul class="def-list">',
    ]
    for n, term, meaning in items:
        term_esc = term.replace("&", "&amp;")
        meaning_esc = meaning.replace("&", "&amp;")
        lines.append(f'            <li><strong>{n}. {term_esc}</strong> \u2013 {meaning_esc}</li>')
    lines += [
        '          </ul>',
        '        </div>',
    ]
    return "\n".join(lines)


imaginative = [
    (1, "accomplished", "highly skilled and creative"),
    (2, "adaptable", "flexible in creative thinking"),
    (3, "adventurous", "willing to try new ideas"),
    (4, "allusive", "rich in indirect references"),
    (5, "animated", "full of lively expression"),
    (6, "artistic", "showing creative skill or taste"),
    (7, "audacious", "fearlessly original and bold"),
    (8, "bold", "showing daring originality"),
    (9, "boundary-pushing", "going beyond usual limits"),
    (10, "brainy", "smart in a creative way"),
    (11, "brilliant", "exceptionally clever and original"),
    (12, "clever", "showing quick inventive thinking"),
    (13, "colorful", "full of vivid interesting detail"),
    (14, "conceptual", "focused on ideas and concepts"),
    (15, "creative", "full of original ideas"),
    (16, "cutting-edge", "highly new and innovative"),
    (17, "daring", "boldly original or inventive"),
    (18, "distinctive", "clearly different and original"),
    (19, "dramatic", "vivid and emotionally expressive"),
    (20, "dreamlike", "resembling a vivid dream"),
    (21, "dreamy", "full of imaginative thoughts"),
    (22, "dynamic", "energetic and full of ideas"),
    (23, "eccentric", "unconventionally imaginative or odd"),
    (24, "elaborate", "highly detailed and inventive"),
    (25, "evocative", "bringing clear images to mind"),
    (26, "expansive", "wide-ranging in ideas"),
    (27, "experimental", "trying new creative approaches"),
    (28, "expressive", "showing ideas or feelings vividly"),
    (29, "fanciful", "guided by imagination rather than reality"),
    (30, "fantastical", "highly imaginative and unreal"),
    (31, "far-seeing", "showing imaginative foresight"),
    (32, "fertile-minded", "rich in ideas"),
    (33, "figurative", "using imaginative language"),
    (34, "forward-thinking", "thinking in fresh future-focused ways"),
    (35, "freewheeling", "loose, lively, and inventive"),
    (36, "fresh", "new and original in style"),
    (37, "generative", "able to produce new ideas"),
    (38, "genius-level", "showing extraordinary creative ability"),
    (39, "gifted", "naturally talented and creative"),
    (40, "groundbreaking", "introducing bold new ideas"),
    (41, "idiosyncratic", "distinctively original and unusual"),
    (42, "impressionistic", "suggestive rather than exact"),
    (43, "individualistic", "expressing personal originality"),
    (44, "ingenious", "cleverly inventive and skillful"),
    (45, "innovative", "introducing fresh ideas or methods"),
    (46, "inspired", "filled with creative energy"),
    (47, "intuitive", "guided by creative instinct"),
    (48, "inventive", "good at creating new ideas"),
    (49, "lively", "full of energy and ideas"),
    (50, "lush", "richly detailed and vivid"),
    (51, "lyrical", "musical and imaginatively expressive"),
    (52, "magical", "full of wonder and invention"),
    (53, "masterful", "showing great creative skill"),
    (54, "metaphoric", "using imaginative comparisons"),
    (55, "multifaceted", "showing many creative aspects"),
    (56, "mythic", "having grand imaginative quality"),
    (57, "nimble-minded", "quick and creatively flexible"),
    (58, "novel", "new, unusual, and original"),
    (59, "nuanced", "showing fine imaginative detail"),
    (60, "offbeat", "unusual in an appealing way"),
    (61, "opulent", "richly elaborate and imaginative"),
    (62, "original", "new and unlike others"),
    (63, "ornate", "richly detailed and decorative"),
    (64, "otherworldly", "strangely imaginative and unreal"),
    (65, "out-of-the-box", "thinking in unusual ways"),
    (66, "picturesque", "visually vivid and striking"),
    (67, "pioneering", "introducing new creative approaches"),
    (68, "playful", "lightly creative and inventive"),
    (69, "poetic", "expressive in an imaginative way"),
    (70, "progressive", "favoring new and original ideas"),
    (71, "prolific", "producing many ideas or works"),
    (72, "provocative", "sparking fresh thought or ideas"),
    (73, "quick-witted", "mentally agile and inventive"),
    (74, "quirky", "unusually playful and inventive"),
    (75, "resourceful", "good at finding clever solutions"),
    (76, "revolutionary", "bringing major new ideas"),
    (77, "rich", "full and varied in ideas"),
    (78, "romantic", "idealistic and richly imaginative"),
    (79, "self-expressive", "showing personal creative expression"),
    (80, "singular", "strikingly unusual or original"),
    (81, "speculative", "exploring imagined possibilities"),
    (82, "spellbinding", "captivating through vivid imagination"),
    (83, "stylized", "creatively shaped rather than realistic"),
    (84, "suggestive", "hinting at vivid ideas"),
    (85, "surreal", "strangely dreamlike and imaginative"),
    (86, "symbolic", "expressing ideas through symbols"),
    (87, "talented", "having strong creative ability"),
    (88, "textured", "richly layered and detailed"),
    (89, "thought-provoking", "making people think creatively"),
    (90, "trailblazing", "pioneering in creative ways"),
    (91, "unconventional", "not following usual patterns"),
    (92, "utopian", "imagining an ideal future"),
    (93, "versatile", "able to create in many ways"),
    (94, "vibrant", "full of life and originality"),
    (95, "vision-filled", "full of vivid ideas"),
    (96, "visionary", "thinking boldly about possibilities"),
    (97, "vivid", "producing strong mental images"),
    (98, "well-conceived", "thought out with originality"),
    (99, "whimsical", "playfully imaginative or quirky"),
    (100, "wide-ranging", "covering many imaginative ideas"),
]

dark = [
    (1, "ashen", "pale gray; dull and dark"),
    (2, "aubergine", "very dark purple"),
    (3, "black", "very dark; without light"),
    (4, "blacked-out", "made dark by cutting lights"),
    (5, "blackened", "made black or very dark"),
    (6, "blackish", "somewhat black; very dark"),
    (7, "blackness", "complete or near-complete darkness"),
    (8, "blanketed", "covered over, often with darkness"),
    (9, "blotted out", "hidden completely from view"),
    (10, "blue-black", "black with a blue tone"),
    (11, "charcoal", "dark gray-black"),
    (12, "cheerless", "lacking brightness or cheer"),
    (13, "chocolate", "dark brown color"),
    (14, "cloaked", "covered or hidden"),
    (15, "clouded", "made dark or unclear"),
    (16, "cloudy", "darkened by clouds"),
    (17, "coal-black", "black like coal"),
    (18, "darkened", "made less bright"),
    (19, "darkness", "absence of light"),
    (20, "deep", "intense or very dark in color"),
    (21, "dim", "not bright; low in light"),
    (22, "dimly lit", "lit with low light"),
    (23, "dimming", "becoming less bright"),
    (24, "dull", "not bright; lacking light"),
    (25, "dusky", "darkish, like at dusk"),
    (26, "ebony", "deep black"),
    (27, "eclipsed", "darkened by blocking light"),
    (28, "eerie", "strangely dark and unsettling"),
    (29, "eggplant", "very dark purple"),
    (30, "enshrouded", "wrapped in darkness or fog"),
    (31, "enveloped", "surrounded and covered"),
    (32, "faint", "barely visible; low light"),
    (33, "faintly lit", "lit only a little"),
    (34, "foggy", "filled with fog; low visibility"),
    (35, "foreboding", "suggesting something bad; dark"),
    (36, "gloom", "partial darkness; dimness"),
    (37, "gloomy", "dark and depressing"),
    (38, "gray", "darkish; lacking brightness"),
    (39, "green-black", "black with a green tone"),
    (40, "grim", "dark and harsh in mood"),
    (41, "growing dim", "becoming darker"),
    (42, "gunmetal", "dark gray metallic"),
    (43, "half-lit", "partly lit; partly dark"),
    (44, "haunted", "eerie, as if by ghosts"),
    (45, "hazy", "not clear; slightly dark"),
    (46, "hidden", "not visible; concealed"),
    (47, "immersed", "deeply surrounded by darkness"),
    (48, "indigo", "deep blue-purple"),
    (49, "indistinct", "not clearly seen"),
    (50, "inky", "as dark as ink"),
    (51, "iron-gray", "dark gray like iron"),
    (52, "jet", "deep black"),
    (53, "lead-gray", "dull dark gray"),
    (54, "lightless", "without any light"),
    (55, "lights-out", "with lights turned off"),
    (56, "low-light", "having little available light"),
    (57, "low-lit", "lit only a little"),
    (58, "macabre", "darkly gruesome"),
    (59, "mahogany", "reddish dark brown"),
    (60, "maroon", "dark red-brown"),
    (61, "menacing", "dark and threatening"),
    (62, "midnight", "very dark; like midnight"),
    (63, "misty", "hazy; hard to see"),
    (64, "murk", "darkness; gloom"),
    (65, "murky", "dark and unclear"),
    (66, "navy", "very dark blue"),
    (67, "near-black", "almost black"),
    (68, "obscure", "hard to see; not clear"),
    (69, "occluded", "blocked from view or light"),
    (70, "off-black", "almost black; not pure black"),
    (71, "ominous", "darkly threatening; ill-boding"),
    (72, "oppressive", "heavy and dark in feeling"),
    (73, "overcast", "darkened by cloud cover"),
    (74, "oxblood", "very dark red-brown"),
    (75, "penumbra", "partial shadow; dim area"),
    (76, "pitch-black", "completely without light"),
    (77, "plum", "dark purple color"),
    (78, "poorly lit", "not well illuminated"),
    (79, "raven", "glossy black"),
    (80, "shade", "area of reduced light"),
    (81, "shaded", "kept from direct light"),
    (82, "shadow", "dark area where light is blocked"),
    (83, "shadowy", "full of shadows; hard to see"),
    (84, "shady", "in shade; not bright"),
    (85, "shrouded", "covered in darkness or mist"),
    (86, "smoky", "hazy and darkened"),
    (87, "somber", "dark or dull in tone"),
    (88, "sooty", "blackened with soot"),
    (89, "stygian", "extremely dark and gloomy"),
    (90, "sunless", "without sunlight"),
    (91, "tenebrous", "dark; shadowy"),
    (92, "twilit", "like twilight; dim"),
    (93, "umbra", "darkest part of a shadow"),
    (94, "uncanny", "strangely unsettling; eerie"),
    (95, "unclear", "not easy to see"),
    (96, "underlit", "lit from below; shadowy"),
    (97, "unilluminated", "not lit up"),
    (98, "unlit", "not illuminated"),
    (99, "veiled", "partly hidden from sight"),
    (100, "violet-black", "black with violet tone"),
]

chaos = [
    (1, "administrative disarray", "disorder in management or administration"),
    (2, "agitation", "restless disturbance or excitement"),
    (3, "anarchy", "absence of authority or order"),
    (4, "babel", "a confusion of voices or sounds"),
    (5, "bedlam", "noisy confusion and uproar"),
    (6, "bewilderment", "deep confusion and uncertainty"),
    (7, "breakdown", "a collapse of order or function"),
    (8, "brouhaha", "a noisy fuss or uproar"),
    (9, "bustle", "busy, noisy activity"),
    (10, "calamity", "a serious disastrous event"),
    (11, "catastrophe", "a sudden disastrous event"),
    (12, "clutter", "a messy accumulation of things"),
    (13, "collapse", "a sudden failure of order"),
    (14, "commotion", "noisy confusion or disturbance"),
    (15, "confusion", "a state of uncertainty and disorder"),
    (16, "craziness", "wild, irrational disorder"),
    (17, "crisis", "a dangerous, unstable turning point"),
    (18, "disarray", "a state of messy disorder"),
    (19, "disaster", "a damaging, disorderly event"),
    (20, "disorder", "a lack of order or control"),
    (21, "disorderliness", "a lack of order or neatness"),
    (22, "disorganization", "a lack of orderly arrangement"),
    (23, "disorientation", "loss of clear direction or order"),
    (24, "disruption", "a break in normal order"),
    (25, "disturbance", "a disruption of peace or order"),
    (26, "economic turmoil", "serious disorder in the economy"),
    (27, "entropy", "a measure of disorder"),
    (28, "ferment", "a state of excited unrest"),
    (29, "fiasco", "a complete, messy failure"),
    (30, "fracas", "a noisy quarrel or disturbance"),
    (31, "fragmentation", "breaking into disconnected parts"),
    (32, "frenzy", "wild, uncontrolled excitement or activity"),
    (33, "furor", "a sudden public uproar"),
    (34, "furore", "a sudden public uproar"),
    (35, "fuss", "unnecessary excitement or disorder"),
    (36, "general confusion", "widespread lack of clarity"),
    (37, "havoc", "widespread damage and disorder"),
    (38, "hodgepodge", "a confused mixture of varied things"),
    (39, "hotchpotch", "a confused mixture of varied things"),
    (40, "hubbub", "busy noise and confusion"),
    (41, "hullabaloo", "a noisy fuss or commotion"),
    (42, "hurly-burly", "noisy activity and confusion"),
    (43, "instability", "lack of steadiness or order"),
    (44, "irregularity", "a departure from normal order"),
    (45, "jumble", "a confused, mixed-up collection"),
    (46, "kerfuffle", "a minor commotion or fuss"),
    (47, "lawless disorder", "disorder without legal control"),
    (48, "lawlessness", "a state without law or control"),
    (49, "madness", "wild foolishness or disorder"),
    (50, "maelstrom", "a violent, confused situation"),
    (51, "mass confusion", "confusion among many people"),
    (52, "mayhem", "wild disorder and confusion"),
    (53, "melee", "a confused fight or struggle"),
    (54, "mess", "an untidy or confused state"),
    (55, "messiness", "a state of being messy"),
    (56, "mishmash", "a confused mixture of things"),
    (57, "mix-up", "a confused mistake or disorder"),
    (58, "morass", "a complicated, confusing situation"),
    (59, "muddle", "a confused, disordered state"),
    (60, "operational disorder", "disorder in operations or work"),
    (61, "pandemonic disorder", "wild, noisy disorder"),
    (62, "pandemonium", "wild, noisy disorder"),
    (63, "perplexity", "a state of puzzled confusion"),
    (64, "political turmoil", "serious disorder in politics"),
    (65, "public disorder", "disturbance affecting public order"),
    (66, "quagmire", "a difficult, confused situation"),
    (67, "random disorder", "disorder without pattern"),
    (68, "randomness", "lack of pattern or order"),
    (69, "riot", "violent public disorder"),
    (70, "rioting", "violent public disorder"),
    (71, "ruckus", "a noisy disturbance"),
    (72, "scramble", "a confused, hurried struggle"),
    (73, "shambles", "a badly disordered situation"),
    (74, "snarl", "a complicated, confused mess"),
    (75, "social unrest", "public disturbance and dissatisfaction"),
    (76, "storm", "a violent disturbance or crisis"),
    (77, "swirl", "a confused, moving mass"),
    (78, "tangle", "a confused, complicated mess"),
    (79, "tempest", "a violent disturbance or uproar"),
    (80, "topsy-turviness", "a state of upside-down disorder"),
    (81, "topsy-turvy", "a confused, upside-down state"),
    (82, "tumult", "loud confusion or agitation"),
    (83, "turbulence", "unstable, disturbed movement or conditions"),
    (84, "turmoil", "great disturbance or confusion"),
    (85, "unmanageability", "difficulty being controlled or managed"),
    (86, "unpredictability", "lack of predictable order"),
    (87, "unrest", "a state of social disturbance"),
    (88, "unruliness", "resistance to control or discipline"),
    (89, "untidiness", "a messy lack of neatness"),
    (90, "upheaval", "a major, unsettling disruption"),
    (91, "uproar", "noisy public confusion or disturbance"),
    (92, "upset", "a disturbed or disrupted state"),
    (93, "violent disorder", "forceful, dangerous public unrest"),
    (94, "vortex", "a powerful swirl of confusion"),
    (95, "welter", "a confused mass or jumble"),
    (96, "whirlpool", "a forceful, confusing situation"),
    (97, "whirlwind", "a rapidly confusing situation"),
    (98, "wild disorder", "uncontrolled lack of order"),
    (99, "wildness", "uncontrolled, disorderly behavior"),
    (100, "wreck", "a ruined, disordered thing"),
]

sunsets = [
    (1, "aflame", "appearing to be on fire"),
    (2, "amber", "yellow-orange in color"),
    (3, "apricot", "pale orange-yellow color"),
    (4, "aquamarine", "pale blue-green color"),
    (5, "awe-inspiring", "causing wonder and admiration"),
    (6, "azure", "bright blue like the sky"),
    (7, "banded", "showing distinct horizontal bands"),
    (8, "beautiful", "very pleasing to look at"),
    (9, "blazing", "burning or shining fiercely"),
    (10, "breathtaking", "astonishingly beautiful"),
    (11, "brilliant", "extremely bright and impressive"),
    (12, "brooding", "darkly thoughtful or threatening"),
    (13, "calm", "still and peaceful"),
    (14, "carmine", "rich crimson red"),
    (15, "cerulean", "deep sky-blue color"),
    (16, "cloud-streaked", "marked with streaky clouds"),
    (17, "colorful", "full of vivid colors"),
    (18, "coppery", "having a copper-like color"),
    (19, "coral", "pinkish-orange in color"),
    (20, "crimson", "deep red"),
    (21, "dappled", "marked with patches of color"),
    (22, "darkening", "becoming less bright"),
    (23, "deep", "dark and strong in color"),
    (24, "dramatic", "striking and full of intensity"),
    (25, "dreamlike", "strangely beautiful and unreal"),
    (26, "dusky", "dim, shadowy, and darkening"),
    (27, "electric", "full of charged energy"),
    (28, "ethereal", "delicate and heavenly"),
    (29, "expansive", "wide and far-reaching"),
    (30, "fading", "gradually losing brightness"),
    (31, "fiery", "burning with strong red-orange color"),
    (32, "flaming", "burning brightly with flames"),
    (33, "flecked", "spotted with small marks"),
    (34, "gilded", "covered with golden light"),
    (35, "gleaming", "shining brightly and smoothly"),
    (36, "glinting", "flashing with reflected light"),
    (37, "glorious", "splendid and full of beauty"),
    (38, "glowing", "giving off soft warm light"),
    (39, "golden", "glowing with warm yellow light"),
    (40, "gorgeous", "very beautiful and attractive"),
    (41, "hazy", "covered with light mist"),
    (42, "heavenly", "extremely beautiful or sublime"),
    (43, "honeyed", "golden and sweet-toned"),
    (44, "hushed", "very quiet and subdued"),
    (45, "indigo", "deep blue-purple color"),
    (46, "intense", "very strong or extreme"),
    (47, "iridescent", "showing changing rainbow colors"),
    (48, "lavender", "light purple color"),
    (49, "layered", "arranged in visible bands"),
    (50, "lilac", "pale violet color"),
    (51, "luminous", "full of light; glowing"),
    (52, "magenta", "purplish-red color"),
    (53, "magnificent", "grand and beautiful"),
    (54, "majestic", "grand and dignified"),
    (55, "mauve", "pale purple color"),
    (56, "meditative", "encouraging quiet thought"),
    (57, "misty", "slightly blurred by haze"),
    (58, "moody", "full of changing feeling"),
    (59, "mottled", "marked with irregular spots"),
    (60, "multicolored", "having many colors"),
    (61, "opaline", "showing milky shifting colors"),
    (62, "orange", "bright reddish-yellow color"),
    (63, "otherworldly", "strangely beautiful and unreal"),
    (64, "painted", "colored as if by paint"),
    (65, "painterly", "having artistic visual richness"),
    (66, "panoramic", "showing a wide view"),
    (67, "pastel", "soft and pale in color"),
    (68, "peach", "soft pinkish-orange color"),
    (69, "pink", "light red in color"),
    (70, "prismatic", "showing many bright colors"),
    (71, "purple", "dark red-blue color"),
    (72, "quiet", "still and without disturbance"),
    (73, "radiant", "shining brightly and beautifully"),
    (74, "resplendent", "shining brilliantly; splendid"),
    (75, "restful", "bringing relaxation and peace"),
    (76, "romantic", "evoking love or tenderness"),
    (77, "rosy", "pink or red in color"),
    (78, "ruby", "deep vivid red"),
    (79, "russet", "reddish-brown in color"),
    (80, "sapphire", "deep bright blue"),
    (81, "scarlet", "bright red"),
    (82, "shimmering", "shining with wavering light"),
    (83, "smoky", "filled with grayish haze"),
    (84, "sparkling", "flashing with bright points"),
    (85, "spectacular", "extremely impressive to see"),
    (86, "stunning", "extremely beautiful or impressive"),
    (87, "sweeping", "broad and impressive"),
    (88, "tangerine", "strong orange color"),
    (89, "tranquil", "free from disturbance; calm"),
    (90, "twilight", "the soft light after sunset"),
    (91, "twilit", "lit by twilight"),
    (92, "vast", "very great in size"),
    (93, "velvety", "soft, rich, and smooth"),
    (94, "vermilion", "brilliant red-orange"),
    (95, "vibrant", "full of energy and color"),
    (96, "violet", "bluish-purple color"),
    (97, "vivid", "bright, intense, and clear"),
    (98, "warm", "having a rich glowing tone"),
    (99, "wine-dark", "dark like red wine"),
    (100, "wistful", "gently longing or sad"),
]

damage = [
    (1, "abrade", "wear away by rubbing"),
    (2, "abrasion", "a scrape or wearing away"),
    (3, "attrition", "gradual reduction by wearing down"),
    (4, "bash", "hit and damage forcefully"),
    (5, "batter", "damage by repeated blows"),
    (6, "blemish", "a mark that spoils appearance"),
    (7, "break", "a crack or fracture"),
    (8, "breakage", "damage from being broken"),
    (9, "bruise", "a mark from blunt injury"),
    (10, "burst", "break open from pressure"),
    (11, "chafe", "make sore by rubbing"),
    (12, "chip", "break a small piece from"),
    (13, "contaminate", "make impure or unsafe"),
    (14, "contuse", "bruise without breaking skin"),
    (15, "contusion", "a medical term for bruise"),
    (16, "corrosion", "destruction by chemical action"),
    (17, "crack", "a narrow split or break"),
    (18, "cripple", "severely impair or disable"),
    (19, "crush", "deform or break by pressure"),
    (20, "cut", "an opening made by slicing"),
    (21, "decay", "gradual rotting or decline"),
    (22, "defacement", "spoiling a surface or appearance"),
    (23, "defect", "a fault or imperfection"),
    (24, "degradation", "lowering of quality or condition"),
    (25, "dent", "a hollow mark from impact"),
    (26, "destruction", "complete ruining or wrecking"),
    (27, "deterioration", "decline in condition or quality"),
    (28, "detriment", "harm or disadvantage"),
    (29, "dilapidation", "state of serious disrepair"),
    (30, "ding", "a small dent or nick"),
    (31, "disfigurement", "spoiling of appearance"),
    (32, "disrepair", "poor condition from neglect"),
    (33, "erode", "wear away gradually"),
    (34, "erosion", "gradual wearing away"),
    (35, "fault", "a defect or weakness"),
    (36, "flatten", "make flat or destroy level"),
    (37, "flaw", "a defect or imperfection"),
    (38, "fracture", "a break in hard material"),
    (39, "fray", "unravel or wear at edges"),
    (40, "fraying", "damage shown by unraveling edges"),
    (41, "gash", "a long deep cut"),
    (42, "graze", "scrape the skin lightly"),
    (43, "harm", "injury or hurt caused"),
    (44, "havoc", "widespread destruction or disorder"),
    (45, "hurt", "pain, injury, or harm"),
    (46, "impair", "weaken or reduce effectiveness"),
    (47, "impairment", "reduction in quality or function"),
    (48, "injure", "cause physical or other harm"),
    (49, "injury", "physical or other harm"),
    (50, "lacerate", "tear or cut flesh deeply"),
    (51, "lesion", "an area of injured tissue"),
    (52, "loss", "something lost or reduced"),
    (53, "maim", "seriously injure permanently"),
    (54, "mangle", "damage severely by crushing"),
    (55, "mar", "spoil the appearance or quality"),
    (56, "marring", "spoiling the surface or appearance"),
    (57, "maul", "injure roughly and severely"),
    (58, "mutilate", "damage severely by cutting"),
    (59, "nick", "a small cut or chip"),
    (60, "perforate", "pierce with holes"),
    (61, "pierce", "make a hole through"),
    (62, "poison", "harm by toxic contamination"),
    (63, "pollute", "contaminate and harm"),
    (64, "pound", "strike repeatedly and damage"),
    (65, "puncture", "make a small hole in"),
    (66, "ravage", "severe destructive damage"),
    (67, "raze", "destroy completely to the ground"),
    (68, "rend", "tear apart violently"),
    (69, "rip", "a tear in material"),
    (70, "rot", "decay from decomposition"),
    (71, "ruin", "serious destruction or spoilage"),
    (72, "ruination", "the act or state of ruin"),
    (73, "rupture", "burst or break open"),
    (74, "rust", "corrosion of iron or steel"),
    (75, "scar", "a lasting mark after injury"),
    (76, "scrape", "a rough surface injury"),
    (77, "scratch", "a shallow surface mark"),
    (78, "scuff", "a surface mark from rubbing"),
    (79, "slash", "cut with a sweeping stroke"),
    (80, "slice", "cut into or through"),
    (81, "sore", "a painful injured place"),
    (82, "split", "a crack or division"),
    (83, "spoilage", "damage causing waste or decay"),
    (84, "spoiling", "making something worse or unusable"),
    (85, "taint", "contaminate or spoil"),
    (86, "tarnish", "spoil reputation or shine"),
    (87, "tear", "a rip in material"),
    (88, "total", "damage beyond repair"),
    (89, "trash", "damage or destroy carelessly"),
    (90, "trauma", "serious physical or emotional injury"),
    (91, "traumatize", "cause severe emotional injury"),
    (92, "undermine", "weaken gradually or secretly"),
    (93, "vandalize", "deliberately damage property"),
    (94, "weaken", "make less strong or effective"),
    (95, "weakening", "making less strong or effective"),
    (96, "wear", "gradual loss from use"),
    (97, "welt", "a raised mark from injury"),
    (98, "wound", "injury to living tissue"),
    (99, "wreck", "damage or ruin badly"),
    (100, "wrecking", "the act of ruining completely"),
]

textures = _textures_all = [
    (1, "beaded", "covered with small rounded drops"),
    (2, "bristly", "covered with stiff short hairs"),
    (3, "brittle", "hard and easily broken"),
    (4, "bumpy", "covered with raised lumps"),
    (5, "buttery", "smooth, soft, and rich"),
    (6, "chalky", "dry and powdery like chalk"),
    (7, "clammy", "cold and slightly damp"),
    (8, "clayey", "thick and sticky like clay"),
    (9, "coarse", "rough and not fine"),
    (10, "corrugated", "formed into parallel ridges"),
    (11, "craggy", "rough with sharp uneven parts"),
    (12, "creamy", "smooth, rich, and soft"),
    (13, "crisp", "firm and easily broken"),
    (14, "crusty", "having a hard outer layer"),
    (15, "cushiony", "soft and springy like cushions"),
    (16, "damp", "slightly wet"),
    (17, "delicate", "fine and easily harmed"),
    (18, "dense", "closely compacted and thick"),
    (19, "downy", "covered with very soft fluff"),
    (20, "dry", "free from moisture"),
    (21, "dusty", "covered with fine dry particles"),
    (22, "elastic", "stretchy and springing back"),
    (23, "feathery", "light and soft like feathers"),
    (24, "fibrous", "made of threadlike fibers"),
    (25, "firm", "solid and slightly resistant"),
    (26, "flaky", "breaking into thin layers"),
    (27, "fluffy", "light, soft, and airy"),
    (28, "foamy", "full of small bubbles"),
    (29, "frosted", "covered with a dull film"),
    (30, "fuzzy", "covered with soft fine fibers"),
    (31, "glassy", "smooth and hard like glass"),
    (32, "glossy", "smooth and shiny"),
    (33, "gluey", "thick and very sticky"),
    (34, "gooey", "soft, sticky, and messy"),
    (35, "grainy", "having a rough grainy feel"),
    (36, "granular", "made of tiny grains"),
    (37, "greasy", "covered with oily slickness"),
    (38, "gritty", "containing small rough particles"),
    (39, "grooved", "marked with long channels"),
    (40, "gummy", "sticky and chewy"),
    (41, "hairy", "covered with hairlike strands"),
    (42, "hard", "firm and not easily pressed"),
    (43, "icy", "very cold and slick"),
    (44, "jagged", "having sharp uneven edges"),
    (45, "knobby", "having hard rounded lumps"),
    (46, "lacey", "delicate and open-patterned"),
    (47, "leathery", "tough and like leather"),
    (48, "lumpy", "full of uneven lumps"),
    (49, "malleable", "able to be shaped easily"),
    (50, "matte", "dull, not shiny"),
    (51, "matted", "tangled into a dense mass"),
    (52, "mealy", "dry, soft, and grainy"),
    (53, "meshy", "having a netlike structure"),
    (54, "metallic", "hard and smooth like metal"),
    (55, "moist", "slightly wet and soft"),
    (56, "muddy", "wet, soft, and dirty"),
    (57, "mushy", "soft and pulpy"),
    (58, "netted", "made with an open mesh"),
    (59, "nubby", "having small soft lumps"),
    (60, "oily", "having an oil-like feel"),
    (61, "padded", "softened with extra filling"),
    (62, "papery", "thin and dry like paper"),
    (63, "pebbled", "having a small bumpy surface"),
    (64, "pitted", "marked with small hollows"),
    (65, "pliable", "easily bent or shaped"),
    (66, "plush", "richly soft and thick"),
    (67, "polished", "made smooth and shiny"),
    (68, "porous", "full of tiny holes"),
    (69, "powdery", "dry and fine like powder"),
    (70, "prickly", "having many sharp points"),
    (71, "raspy", "rough and scraping"),
    (72, "resilient", "able to recover shape quickly"),
    (73, "ribbed", "having raised bands or lines"),
    (74, "ridged", "marked with raised lines"),
    (75, "rigid", "very stiff and unbending"),
    (76, "rough", "uneven and coarse to touch"),
    (77, "rubbery", "elastic and slightly tough"),
    (78, "rugged", "rough and uneven"),
    (79, "silky", "smooth like fine silk"),
    (80, "slack", "loose and not tight"),
    (81, "slimy", "wet, slippery, and unpleasant"),
    (82, "slippery", "easy to slide on"),
    (83, "smooth", "even and free from roughness"),
    (84, "soft", "pleasantly yielding to pressure"),
    (85, "spongy", "soft and full of holes"),
    (86, "springy", "bouncy and resilient"),
    (87, "sticky", "tending to cling to surfaces"),
    (88, "stringy", "forming long thin strands"),
    (89, "supple", "bending easily without breaking"),
    (90, "tacky", "slightly sticky to touch"),
    (91, "taut", "pulled tight and firm"),
    (92, "textured", "having a distinct surface feel"),
    (93, "unyielding", "not soft or flexible"),
    (94, "velutinous", "covered with fine soft hairs"),
    (95, "velvety", "soft and smooth like velvet"),
    (96, "viscous", "thick and slow-flowing"),
    (97, "waxy", "smooth and slightly greasy"),
    (98, "wet", "covered or soaked with liquid"),
    (99, "wrinkled", "marked with small folds"),
    (100, "yielding", "soft and giving way"),
]

_materials_terms = {
    "brittle", "bumpy", "chalky", "clayey", "coarse", "corrugated", "crisp", "dense", "downy",
    "elastic", "feathery", "fibrous", "fluffy", "fuzzy", "glossy", "grainy", "granular", "greasy",
    "gritty", "grooved", "gummy", "hairy", "hard", "leathery", "lumpy", "matte", "metallic",
    "muddy", "oily", "papery", "pebbled", "pitted", "porous", "powdery", "resilient", "ridged",
    "rigid", "rough", "rubbery", "slick", "slippery", "smooth", "soft", "spongy", "sticky",
    "tacky", "velvety", "viscous", "waxy", "wrinkled",
}
textures = [(n, t, m) for n, t, m in _textures_all if t.lower() not in _materials_terms]

yeah = [
    (1, "Absolutely", "complete agreement; no doubt"),
    (2, "Accepted", "agreed to; taken as true"),
    (3, "Affirmative", "formal yes; positive response"),
    (4, "Aha", "recognition; yes, I see"),
    (5, "Aight", "informal okay; yes"),
    (6, "Alright", "okay; yes; acceptable"),
    (7, "Amen", "so be it; agreed"),
    (8, "Assuredly", "certainly; without question"),
    (9, "Ay", "yes; archaic or dialectal"),
    (10, "Aye", "yes; especially in voting"),
    (11, "Bet", "slang: okay; definitely"),
    (12, "Bett", "slang: yes; for sure"),
    (13, "By all means", "certainly; go ahead; yes"),
    (14, "Can do", "yes; I can do that"),
    (15, "Certainly", "without doubt; yes"),
    (16, "Confirmed", "verified; yes, it's settled"),
    (17, "Copy", "understood; acknowledged"),
    (18, "Correct", "that is right; yes"),
    (19, "Course", "of course; naturally"),
    (20, "Damn right", "emphatic agreement; yes"),
    (21, "Definitely", "for sure; unquestionably"),
    (22, "Done", "agreed; it's taken care of"),
    (23, "Duly noted", "acknowledged; understood"),
    (24, "Eh-hem", "polite acknowledgment; yes"),
    (25, "Exactly", "precisely; that's right"),
    (26, "Fair", "reasonable; agreed"),
    (27, "Fine", "okay; acceptable; yes"),
    (28, "For sure", "certainly; definitely yes"),
    (29, "Gladly", "yes; with pleasure"),
    (30, "Good", "approved; yes"),
    (31, "Got it", "understood; acknowledged"),
    (32, "Granted", "admitted; accepted as true"),
    (33, "Great", "approval; yes"),
    (34, "Heck yes", "enthusiastic yes"),
    (35, "I agree", "I share your view"),
    (36, "I do", "yes; I will; I agree"),
    (37, "I hear you", "I understand and agree"),
    (38, "I'm in", "count me in; yes"),
    (39, "Indeed", "certainly; truly yes"),
    (40, "Indubitably", "without doubt; certainly"),
    (41, "K", "texting: okay; yes"),
    (42, "Kay", "okay; yes"),
    (43, "Keen", "willing; yes"),
    (44, "Legit", "true; agreed"),
    (45, "Make sense", "yes; that's logical"),
    (46, "Makes sense", "agreed; it's reasonable"),
    (47, "Most assuredly", "certainly; emphatic yes"),
    (48, "My pleasure", "yes; happy to help"),
    (49, "Naturally", "of course; as expected"),
    (50, "No doubt", "certainly; yes"),
    (51, "No problem", "sure; that's fine"),
    (52, "Nods", "nonverbal yes; agreement"),
    (53, "Noted", "acknowledged; understood"),
    (54, "Of course", "certainly; obviously yes"),
    (55, "Oh yes", "emphatic agreement"),
    (56, "Ok", "okay; yes"),
    (57, "Okay", "all right; yes"),
    (58, "Okey-dokey", "cheerful agreement; yes"),
    (59, "Okie-dokie", "playful yes; okay"),
    (60, "On it", "yes; I'll handle it"),
    (61, "Ooh yeah", "excited agreement; yes"),
    (62, "Perfect", "exactly right; yes"),
    (63, "Please do", "yes; go ahead"),
    (64, "Positively", "certainly; yes"),
    (65, "Precisely", "exactly; yes"),
    (66, "Quite", "yes; to a degree"),
    (67, "Right", "correct; yes"),
    (68, "Right on", "approval; yes"),
    (69, "Roger", "received; understood; yes"),
    (70, "Roger that", "understood; acknowledged"),
    (71, "Same here", "I agree; me too"),
    (72, "Say no more", "understood; yes"),
    (73, "Shore", "dialectal sure; yes"),
    (74, "Si", "Spanish yes; informal borrowing"),
    (75, "Sounds good", "agreed; that works"),
    (76, "Spot on", "exactly right; yes"),
    (77, "Sure", "yes; certainly"),
    (78, "Sure thing", "definitely; yes"),
    (79, "Surely", "certainly; yes"),
    (80, "Totally", "completely; yes"),
    (81, "Totes", "slang: totally; yes"),
    (82, "True", "that's correct; yes"),
    (83, "Uh-huh", "informal yes; agreement"),
    (84, "Uhuh", "casual yes; agreement"),
    (85, "Understood", "acknowledged; I get it"),
    (86, "Unquestionably", "without doubt; yes"),
    (87, "Very well", "formal agreement; yes"),
    (88, "Will do", "yes; I'll do it"),
    (89, "Word", "slang agreement; true"),
    (90, "Works for me", "agreed; acceptable"),
    (91, "Yah", "informal yes; variant"),
    (92, "Yap", "dialectal yes; agreement"),
    (93, "Yar", "dialectal yes; piratey yes"),
    (94, "Yarp", "humorous yes; deadpan"),
    (95, "Yas", "enthusiastic slang yes"),
    (96, "Yass", "emphatic slang yes"),
    (97, "Yea", "yes; especially in voting"),
    (98, "Yep", "informal yes"),
    (99, "Yes", "affirmative response"),
    (100, "Yessir", "yes, sir; respectful"),
]

explore = [
    (1, "analyze", "examine parts to understand"),
    (2, "approach", "begin to consider or examine"),
    (3, "ascertain", "find out with certainty"),
    (4, "ask about", "seek information concerning"),
    (5, "assess", "examine to judge value"),
    (6, "browse", "look through casually"),
    (7, "chart", "map or describe systematically"),
    (8, "check out", "examine or visit casually"),
    (9, "comb", "search thoroughly through"),
    (10, "consider", "think about carefully"),
    (11, "cover", "deal with a subject"),
    (12, "cross", "go from one side to another"),
    (13, "cruise", "travel around casually"),
    (14, "delve into", "investigate deeply"),
    (15, "determine", "discover by investigation"),
    (16, "dig into", "investigate thoroughly"),
    (17, "dip into", "read or examine briefly"),
    (18, "discover", "find something previously unknown"),
    (19, "dissect", "analyze closely in parts"),
    (20, "drill into", "examine details deeply"),
    (21, "drive through", "travel by car through"),
    (22, "evaluate", "examine and judge worth"),
    (23, "examine", "look at closely and carefully"),
    (24, "experiment with", "try to learn what happens"),
    (25, "fathom", "understand after deep examination"),
    (26, "ferret out", "search out hidden information"),
    (27, "find out", "discover information"),
    (28, "flip through", "look through pages quickly"),
    (29, "follow up", "investigate further after initial information"),
    (30, "forage", "search widely for supplies or facts"),
    (31, "go into", "discuss or examine in detail"),
    (32, "go over", "review or examine carefully"),
    (33, "go through", "examine or experience systematically"),
    (34, "hike through", "walk through to see"),
    (35, "hunt", "search actively for something"),
    (36, "inquire about", "ask for information concerning"),
    (37, "inquire into", "ask about and investigate"),
    (38, "inspect", "look over carefully"),
    (39, "interview", "question to gather information"),
    (40, "investigate", "examine carefully to find facts"),
    (41, "journey through", "travel across or within"),
    (42, "leaf through", "turn pages and examine briefly"),
    (43, "learn", "gain knowledge about"),
    (44, "look around", "inspect a place casually"),
    (45, "look beneath", "investigate below the surface"),
    (46, "look inside", "examine the interior"),
    (47, "look into", "investigate or examine"),
    (48, "look over", "examine in a general way"),
    (49, "look up", "search for information about"),
    (50, "make one's way through", "move through carefully or gradually"),
    (51, "map", "chart or investigate an area"),
    (52, "meander through", "wander through without direct route"),
    (53, "move through", "travel within or across"),
    (54, "navigate", "find a route through"),
    (55, "parse", "analyze structure or meaning"),
    (56, "penetrate", "enter into or understand deeply"),
    (57, "peruse", "read or examine carefully"),
    (58, "pilot", "try on a small scale"),
    (59, "plumb", "examine deeply or measure depth"),
    (60, "probe", "investigate deeply or searchingly"),
    (61, "prospect", "search an area for resources"),
    (62, "pursue", "follow or investigate further"),
    (63, "query", "ask about for information"),
    (64, "quest for", "search determinedly for"),
    (65, "question", "ask about to investigate"),
    (66, "range", "move widely over an area"),
    (67, "read up on", "study by reading about"),
    (68, "reconnoiter", "survey an area for information"),
    (69, "research", "investigate systematically for information"),
    (70, "review", "examine again or assess"),
    (71, "rifle through", "search quickly through things"),
    (72, "roam", "move around without fixed direction"),
    (73, "rummage", "search untidily through things"),
    (74, "sample", "try a small amount"),
    (75, "scan", "look over quickly"),
    (76, "scout", "search an area for information"),
    (77, "scrutinize", "examine very closely"),
    (78, "search", "look carefully for something"),
    (79, "seek", "try to find or discover"),
    (80, "sift", "examine carefully to select facts"),
    (81, "skim", "look over quickly for essentials"),
    (82, "study", "learn about through careful attention"),
    (83, "survey", "look over broadly or systematically"),
    (84, "take apart", "analyze by separating elements"),
    (85, "test", "try to learn or judge"),
    (86, "tour", "travel through to see places"),
    (87, "trace", "follow the course of something"),
    (88, "track", "follow signs or progress"),
    (89, "travel", "go through or across places"),
    (90, "traverse", "travel across or through"),
    (91, "try", "attempt or sample something"),
    (92, "unpack", "analyze by explaining details"),
    (93, "venture across", "travel across uncertain terrain"),
    (94, "venture further", "go deeper into unknown territory"),
    (95, "venture into", "enter and investigate uncertainly"),
    (96, "visit", "go to see a place"),
    (97, "walk around", "move about to inspect casually"),
    (98, "walk through", "go over step by step"),
    (99, "wander", "move around casually or aimlessly"),
    (100, "work through", "examine step by step"),
]

moving = [
    (1, "absorbing", "fully holding attention"),
    (2, "aching", "full of emotional pain"),
    (3, "adorable", "inspiring affection"),
    (4, "affecting", "stirring emotions strongly"),
    (5, "appealing", "attractive or pleasing"),
    (6, "arresting", "commanding emotional attention"),
    (7, "beautiful", "pleasing and emotionally affecting"),
    (8, "captivating", "holding interest completely"),
    (9, "charming", "pleasantly delightful"),
    (10, "comforting", "giving emotional relief"),
    (11, "compelling", "powerfully persuasive or engaging"),
    (12, "consequential", "important in effect"),
    (13, "consoling", "easing sadness"),
    (14, "delicate", "subtle and gentle"),
    (15, "devastating", "causing overwhelming sadness"),
    (16, "devotional", "showing deep love"),
    (17, "distressing", "causing worry or sadness"),
    (18, "dramatic", "emotionally intense"),
    (19, "earnest", "serious and heartfelt"),
    (20, "eloquent", "beautifully expressive"),
    (21, "emotional", "full of strong feeling"),
    (22, "engaging", "pleasantly drawing interest"),
    (23, "evocative", "bringing strong feelings to mind"),
    (24, "expressive", "showing feeling clearly"),
    (25, "fascinating", "extremely interesting"),
    (26, "fervent", "showing intense feeling"),
    (27, "fraught", "filled with emotion or tension"),
    (28, "full-blooded", "vivid and passionate"),
    (29, "gentle", "soft and mild"),
    (30, "grand", "impressive in scale or feeling"),
    (31, "grave", "serious and weighty"),
    (32, "gripping", "holding attention intensely"),
    (33, "gut-wrenching", "deeply upsetting emotionally"),
    (34, "haunting", "lingering in the mind"),
    (35, "healing", "helping emotional recovery"),
    (36, "heart-rending", "causing intense sadness"),
    (37, "heartbreaking", "causing great sorrow"),
    (38, "heartfelt", "sincerely felt"),
    (39, "heartrending", "deeply distressing and touching"),
    (40, "hopeful", "inspiring optimism"),
    (41, "insightful", "showing deep understanding"),
    (42, "inspiring", "encouraging and uplifting"),
    (43, "intense", "very strong emotionally"),
    (44, "invigorating", "giving energy or spirit"),
    (45, "irresistible", "too attractive to resist"),
    (46, "keen", "intense or deeply felt"),
    (47, "kindly", "gentle and considerate"),
    (48, "layered", "having several emotional levels"),
    (49, "loaded", "full of emotional meaning"),
    (50, "lovely", "beautiful and pleasing"),
    (51, "loving", "showing deep affection"),
    (52, "magnetic", "strongly attractive"),
    (53, "majestic", "grand and impressive"),
    (54, "meaningful", "full of emotional significance"),
    (55, "meditative", "deeply thoughtful and calm"),
    (56, "melting", "softening the heart"),
    (57, "memorable", "worth remembering strongly"),
    (58, "mesmerizing", "fascinating intensely"),
    (59, "momentous", "very important emotionally"),
    (60, "monumental", "greatly important or affecting"),
    (61, "mournful", "expressing sorrow"),
    (62, "movingly sad", "touchingly sorrowful"),
    (63, "noble", "showing high moral feeling"),
    (64, "nuanced", "showing fine distinctions"),
    (65, "overwhelming", "very intense emotionally"),
    (66, "passionate", "full of intense feeling"),
    (67, "pathetic", "arousing pity or sadness"),
    (68, "piercing", "sharply affecting feelings"),
    (69, "poignant", "deeply sad and touching"),
    (70, "powerful", "having strong emotional impact"),
    (71, "profound", "deeply felt or meaningful"),
    (72, "reassuring", "reducing worry or fear"),
    (73, "resonant", "evoking deep response"),
    (74, "restorative", "renewing strength or spirit"),
    (75, "reverent", "showing deep respect"),
    (76, "riveting", "extremely compelling"),
    (77, "rousing", "awakening strong feeling"),
    (78, "sad", "causing sorrow"),
    (79, "sentimental", "showing tender emotion"),
    (80, "sincere", "genuine in feeling"),
    (81, "soul-stirring", "deeply affecting emotionally"),
    (82, "stirring", "emotionally arousing"),
    (83, "striking", "impressively noticeable"),
    (84, "tear-jerking", "making people cry"),
    (85, "tearful", "bringing tears"),
    (86, "tender", "gentle and affectionate"),
    (87, "thrilling", "causing excitement"),
    (88, "touching", "causing deep emotion"),
    (89, "tragic", "causing sorrow or distress"),
    (90, "unfeigned", "genuine and not pretended"),
    (91, "unflinching", "direct and unsparing"),
    (92, "uplifting", "making people feel hopeful"),
    (93, "vivid", "producing clear strong feelings"),
    (94, "warm", "showing affection or kindness"),
    (95, "weepy", "likely to cause tears"),
    (96, "weighty", "important and serious"),
    (97, "wholehearted", "fully sincere"),
    (98, "winsome", "sweetly charming"),
    (99, "wrenching", "causing emotional pain"),
    (100, "zealous", "full of eager feeling"),
]

colors = [
    (1, "amber", "a warm golden yellow"),
    (2, "amethyst", "a violet-purple gemstone color"),
    (3, "apricot", "a pale yellow-orange color"),
    (4, "aqua", "a light blue-green color"),
    (5, "aquamarine", "a pale sea-blue green"),
    (6, "ash", "a pale gray color"),
    (7, "azure", "a bright blue color"),
    (8, "baby blue", "a very light blue"),
    (9, "beige", "a pale sandy brown"),
    (10, "black", "the darkest color"),
    (11, "blue", "the color of clear sky"),
    (12, "blush", "a very soft pink"),
    (13, "brick", "a muted reddish brown"),
    (14, "brown", "a dark earthy color"),
    (15, "burgundy", "a dark wine red"),
    (16, "cerulean", "a clear sky-blue color"),
    (17, "chestnut", "a rich reddish brown"),
    (18, "chocolate", "a rich dark brown"),
    (19, "cobalt", "a strong deep blue"),
    (20, "coral", "a pink-orange color"),
    (21, "cream", "a pale yellowish white"),
    (22, "crimson", "a deep vivid red"),
    (23, "cyan", "a greenish blue color"),
    (24, "denim", "a medium muted blue"),
    (25, "dove gray", "a soft light gray"),
    (26, "ebony", "a rich black color"),
    (27, "ecru", "a light grayish beige"),
    (28, "eggplant", "a very dark purple"),
    (29, "eggshell", "a warm pale off-white"),
    (30, "emerald", "a vivid jewel green"),
    (31, "espresso", "a very dark brown"),
    (32, "fawn", "a light yellowish brown"),
    (33, "flaxen", "a pale yellow color"),
    (34, "garnet", "a dark wine-red color"),
    (35, "gray", "a color between black and white"),
    (36, "green", "the color of grass"),
    (37, "greige", "a mix of gray and beige"),
    (38, "gunmetal", "a dark metallic gray"),
    (39, "hazel", "a greenish brown color"),
    (40, "heliotrope", "a pinkish purple color"),
    (41, "honey", "a warm golden color"),
    (42, "ice blue", "a very pale blue"),
    (43, "indigo", "a deep blue-purple color"),
    (44, "ivory", "an off-white color"),
    (45, "jade", "a medium bluish green"),
    (46, "jet", "a deep glossy black"),
    (47, "khaki", "a dusty yellow-brown color"),
    (48, "lavender", "a pale purple color"),
    (49, "lemon", "a bright yellow color"),
    (50, "lilac", "a light pinkish purple"),
    (51, "lime", "a bright yellow-green color"),
    (52, "linen", "a pale beige-white color"),
    (53, "magenta", "a vivid purplish pink"),
    (54, "mahogany", "a deep reddish brown"),
    (55, "maroon", "a dark brownish red"),
    (56, "mauve", "a pale grayish purple"),
    (57, "mint", "a pale cool green"),
    (58, "moss", "a soft earthy green"),
    (59, "mustard", "a dull yellow color"),
    (60, "navy", "a very dark blue"),
    (61, "obsidian", "a dark glassy black"),
    (62, "ochre", "an earthy yellow-brown color"),
    (63, "off-white", "not quite pure white"),
    (64, "olive", "a muted yellow-green color"),
    (65, "onyx", "a deep black color"),
    (66, "orange", "the color of oranges"),
    (67, "peach", "a soft pinkish orange"),
    (68, "pearl", "a soft lustrous white"),
    (69, "periwinkle", "a pale blue-purple color"),
    (70, "pink", "a pale red color"),
    (71, "plum", "a dark reddish purple"),
    (72, "purple", "a rich red-blue color"),
    (73, "raspberry", "a deep pinkish red"),
    (74, "red", "the color of blood"),
    (75, "robin's-egg blue", "a pale greenish blue"),
    (76, "rose", "a soft pinkish red"),
    (77, "royal blue", "a vivid deep blue"),
    (78, "rust", "a reddish orange-brown"),
    (79, "sage", "a muted gray-green color"),
    (80, "salmon", "a pale pink-orange color"),
    (81, "scarlet", "a bright red color"),
    (82, "sepia", "a reddish-brown color"),
    (83, "sienna", "a reddish brown color"),
    (84, "silver", "a shiny light gray"),
    (85, "sky blue", "a pale clear blue"),
    (86, "slate", "a cool medium gray"),
    (87, "tan", "a light brown color"),
    (88, "taupe", "a grayish brown color"),
    (89, "teal", "a blue-green color"),
    (90, "turquoise", "a bright blue-green color"),
    (91, "ultramarine", "a vivid deep blue"),
    (92, "umber", "a dark brown color"),
    (93, "vermilion", "a brilliant orange-red color"),
    (94, "violet", "a bluish-purple color"),
    (95, "viridian", "a deep bluish green"),
    (96, "walnut", "a deep brown color"),
    (97, "white", "the lightest color"),
    (98, "wine", "a dark purplish red"),
    (99, "wisteria", "a soft pale purple"),
    (100, "yellow", "the color of lemons"),
]


def main():
    out = Path(__file__).with_name("_batch3_sections.html")
    parts = [
        sunset_supplement(sunsets),
        section(26, "imaginative", "100 Best Synonyms for &ldquo;Imaginative&rdquo;",
                "Creative and original alternatives, numbered 1\u2013100.", imaginative),
        section(27, "dark", "100 Words to Use Instead of &ldquo;Dark&rdquo;",
                "Atmosphere, lighting, and shadow words, numbered 1\u2013100.", dark),
        section(28, "chaos", "100 Best Synonyms for &ldquo;Chaos&rdquo;",
                "Disorder and turmoil alternatives, numbered 1\u2013100.", chaos),
        section(29, "damage", "100 Best Synonyms for &ldquo;Damage&rdquo;",
                "Harm, injury, and destruction words, numbered 1\u2013100.", damage),
        section(30, "textures", "100 Words to Describe Textures",
                "Touch and surface feel. Words already in Materials (section 18) are omitted here; numbering matches your sheet.", textures),
        section(31, "yeah", "100 Other Words for &ldquo;Yeah&rdquo;",
                "Agreement and affirmation for dialogue, numbered 1\u2013100.", yeah),
        section(32, "explore", "100 Best Synonyms for &ldquo;Explore&rdquo;",
                "Investigation and discovery verbs, numbered 1\u2013100.", explore),
        section(33, "moving", "100 Best Synonyms for &ldquo;Moving&rdquo;",
                "Emotionally affecting (not physical motion), numbered 1\u2013100.", moving),
        section(34, "colors", "100 Words to Describe Colors",
                "Color names and hues, numbered 1\u2013100.", colors),
    ]
    out.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print("written", out.name)


if __name__ == "__main__":
    main()
